### ISSUE TITLE
ajax call proxy

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#1]
http://ryankirkman.com/2012/03/30/pass-through-cross-domain-proxy-jquery.html

**Comment by zbycz** [comment]
Zajímavý tip, ale asi bych řešil PHP proxí. A pokud vím tak osm api má CORS nastavený dobře.

Zavírám.

**Comment by walley** [comment]
no ja potrebuju proxy nebo neco podobneho na svoje api, takze to znovu otevru, momentalne treba nefunguji ty rozcestniky protoze ajax nedokaze z githubu zavolat api.openstreetmap.cz

**Comment by walley** [comment]
Tak uz sem si precetl vsechny issues a vim jak se to dela tak to zase zavru
