### ISSUE TITLE
Nahrávání fotek rozcestníků, info tabulí...

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#10]
Přenést z old.openstreetmap.cz

**Comment by walley** [comment]
zatim to udelam presne tak jak to je na old na nejakem klonu noveho webu a ten stary presmeruju.

jak bychom to chteli udelat po novu? nechat dialog nebo pracovat s hlavni mapou. to by se mi libilo vic, ale chtelo by to uz nejaky ten sidebar.

**Comment by mkyral** [comment]
Do menu přidat položku "Nástroje"/"Nahrát fotku rozcestníku".
Po vybrání volby by se vysunul panel (zleva nebo zprava). Byla by tam jen možnost nahrát fotografii. 
- Uživatel vybere fotografii, 
- Ta se ihned přenese na server 
- Na serveru se vygeneruje náhled a zjistí se, zda fotografie obsahuje gps souřadnice.
- Pokud ano, ukáže se poloha na mapě.
- V opačném případě je uživatel vyzván k přesunu fotky na správnou pozici
- Uživatel vyplní ref a další údaje a odešle na server

Nice to have: z OSM se zjistí, zda v okolí fotografie existuje nějaký rozcestník a rovnou se nabídne jeho ref.

**Comment by walley** [comment]
tak to potrebujeme primarne ten panel, uz vime kterej?

**Comment by mkyral** [comment]
Si nějaký vyber :-) Mrknul bych na issue #49 jestli by to nešlo nějak použít.

**Comment by walley** [comment]
ja neco vyberu a nebude se to zas nikomu libit:)

me se libil sidebar v2, ne ze bych teda nasel nejakej jinej(krome v1)
https://github.com/Turbo87/sidebar-v2

**Comment by mkyral** [comment]
Za mně klidně. S tou legendou se to pak nějak pořeší.

**Comment by walley** [comment]
prozatimni nahravani rozcestniku zprovozneno, zjevi se na old.openstreetmap.cz, je to clone githubu malinko oklestenej.

legenda se muze otvirat na druhe strane,

**Comment by zbycz** [comment]
Popup na nahrání je fajn. Do #28 jsem zmínil ten L.OSM.sidebar, který bych doporučoval. Kdybys chtěl, můžu ti navrhnout UI toho sidebaru jako obrázek, aby "se to líbilo" :D

**Comment by walley** [comment]
@zbycz tak zkousim rozjet L.OSM.sidebar ale to je opravdu na miru usite na osm.org, myslim ze vykousavat to z osm je ztrata casu, muzes to ale zkusit:). 

predstavoval sem si knihovnu, ktere reknu sidebar.show a ona mi ho zobrazi a ja do jeho divu nacpu co potrebuju.

**Comment by Krakonos** [comment]
K tématu nahrávání fotek: trošku mi vadí, že teď jde nahrát fotku do 5MB a víc ne (moje fotky jsou občas větší). Já to nějak zvládnu, ale bylo by lepší nechat nahrát kde co a případně zmenšit a normalizovat na serveru (včetně vytvoření náhledu).

**Comment by zbycz** [comment]
@walley mrknu na to a zkusím v průběhu týdne připravit - představuju si to stejně jako ty. A důležité že to musí fungovat i na mobilech :grimacing:

@Krakonos můžeš poladit na https://github.com/osmcz/old_osmcz :-)

**Comment by walley** [comment]
@Krakonos to je celkem dobrej napad, nejaky maximalni rozliseni a z toho vyplyvajici omezena velikost by se hodila.
budu vyrabet novou uploadovaci funkci, bude 2-fazova (1. nahrat, prozkoumat - vratit info user to zkontroluje a zmeni, 2. vlozit do db)

@zbycz oni pouzivaji leaflet panes, coz jim umoznuje tam jednoduse nacpat vyber vrstev se zobrazenou aktualni pozici, netvrdim ze to nepude vykousnout ven, ale bude to pulka osm.org stranky:)
co presne a kde parsuje //=require by me taky docela zajimalo.

**Comment by zbycz** [comment]
@walley Jo, už jí půlku používámee :-) Ten require parsuje componentjs - obsolete projekt..

**Comment by zbycz** [comment]
Sidebar k připomínkování zde: #71 - je docela fuška udělat to responsivně.

**Comment by zbycz** [comment]
Super, @mkyral ! Je to fakt vychytané.

btw, jakou má souvislost projekt "photodb" s "fotky rozcestníků"?

**Comment by mkyral** [comment]
No to je další krok. Ony tam nejsou jen rozcestníky, Chtěl jsem se právě poradit, že by se ta vrstva přejmenovala na "Databáze fotografií" nebo tak nějak.

Viz: https://openstreetmap.cz/databaze-fotografii-rozcestniku-a-poi
a následně: https://wiki.openstreetmap.org/wiki/Cs:PhotoDB

@walley @tkas @vop-cz : Co vy na to?

**Comment by mkyral** [comment]
BTW: pokud by měl někdo nějakou pěknou ikonku pro to tlačítko, která bude reprezentovat nejen rozcestníky, ale obecně fotografie (obrázky).

**Comment by mkyral** [comment]
@zbycz A jestli myslíš, že by se to tlačítko mělo zobrazovat stále, tak to jsem spíše proti. Protože bez zapnuté vrstvy sice můžu nahrát obrázek, ale uživatel třeba nebude vědět, že si musí zapnout vrstvu rozcestníků, aby tu fotku viděl a taky zapnutá vrstva při přidávání fotky hodně pomáhá zamezení tvorby duplicit. Vidím, že tam třeba už nějaká fotka je, můžu se na ni podívat a rozhodnout se, zda svou fotku přidám (protože mám lepší) nebo nepřidám (protože ta co tam už je, je lepší).

**Comment by tkas** [comment]
V soucasnosti (kdyz pominu wallyho piva a podobne :-( ) jsou to veci kolem tur. tras (pripadne cyklo,ski, apod). Pokud bude cil z toho delat skladku naprosto cehokoliv bez toho aby pak byla rozumna podpora pro vyuzitelnost tech veci, tak jsem proti snaze o zobecnovani.

**Comment by walley** [comment]
tech testovacich fotek na uzemi cr je tam tak do 5 kusu. 
obcas je smazu, kdyz na ne znovu narazim.
takze se netreba mracit :)

**Comment by severak** [comment]
(BTW - chtěl jsem fotit [mosty](https://api.openstreetmap.cz/table/hashtag/bridge:) v okolí prahy, zatím jsem nahrál jen jeden. Přehledových fotografií je zdá se [více](https://api.openstreetmap.cz/table/hashtag/prehledova:).)

**Comment by vop-cz** [comment]
...no vidis, a ja si zase myslim, ze by project PhotoDB mel byt do urcite miry obecnym. Do urcite miry tim, ze se na zakladni skupine fotek (rozcestniky) odladi jeho funkcionalty atp. a pak se postupne budou pridavat dalsi kategorie. Treba postovni schranky, krizky u cesty, pamatne stromy, budovy (necim pozoruhodne)...
A k tomu smerovaly i me maily v talk-cz, co jste si z nich delali srandu - vychazely z toho, ze by bylo potreba ty fotky s konkretnimi mapovymi prvky nejak parovat... ne pomoci "nejblizsich souradnic" ale pomoci uceloveho photodb:ref...

**Comment by mkyral** [comment]
Problém těch id je, že fotek může být více a každá má vlastní id. A zase ukládat do photoDB osm id asi taky není dobré, někdo jej může smazat a vytvořit znova jinde, ale s jiným id.

Jako nejlepší se mi jeví použití tagu image=*. Ten nám v aktivní vrstvě funguje. (Spolu s tagem wikimedia_commons=*)

Jediné co by to chtělo je nějaký doplněk do editoru, který umožní jednoduché napárování fotek na osm objekty.

**Comment by vop-cz** [comment]
Ad problém s id:
- už jsem to někde popisoval, nejde o unikání id fotky, ale o id OSM objektu vytvořené systémem PhotoDB (čili nejde o OSM id a to právě z tebou popsaného důvodu).
- v případě, že objekt nemá žádnou fotku v PhotoDB (zjednodušeně řečeno nezobrazuje se ve vrstvě fotek PhotoDB), využije uživatel při uploadu fotky možnost "vygenerovat PhotoDbId". Za určitých okolností to systém prostě udělá i sám, protože ví, že k uploadu došlo přes rozhraní "Tento objekt nemá fotku, chcete ji nahrát?". Toto PhotoDbId pak uživatel (nebo systém) přidá jako PhotoDb:ref=* do OSM mezi tagy daného objektu.
- v případě, že objekt už fotku má, uživatel (nebo systém na základě výše uvedené logiky) prostě nevygeneruje PhotoDbId a naopak k fotce uloží PhotoDbId objektu podle již dříve vytvořené (tedy již v databízi existující) fotky daného objektu, která PhotoDbId má (a objekt v OSM má uveden tag PhotoDb:ref=*)

Tedy ve výsledku tzn., že může být mnoho fotek k jednomu objektu (a autor mapy je pak může řadit podle různých kritérií etc.)

Současné párování rozcestníků je v podstatě to stejné, co jsem popsal výše, jen je to konkrétní aplikace na jednoúčelovou skupinu fotek a místo PhotoDbId je v databázi i v OSM tag ref=* (se všemi riziky a neuniverzálnostmi, které má, viz výskyt více ref=* na jednom OSM bodu (bod je zároveň rozcestník, ale také lampa se svým ref=* apod.)

Jinými slovy navrhuji zobecnění použití toho refu a to zavedením něčeho jako PhotoDbId. No a aby to mělo trochu řízený (s)pád, tak v PhotoDb bychom pak postupně otvírali obecné skupiny fotek (primární tagy), které je možné nahrávat. Nyní je to řekněme "rozcestník" a následně by to mohly být "most", "křížek u cesty", "poštovní schránka" atp.

**Comment by vop-cz** [comment]
BTW znamená to, že když bude v OSM bod "lampa veřejného osvětlení" a současně "rozcestník" a oba mají svůj ref=*, tedy v praxi asi něco jako rozcestník:ref=* a lampa:ref=*, tak bude mít tento bod jen jedno PhotoDbId a to i v případě, že bude v PhotoDb existovat skupina fotek "rozcestníky" i skupina "lampy" a objekt bude vyfocen dvakrát (jednou se zaměřením na rozcestník a jednou na lampu). Autor mapy si pak akorát musí ohlídat, jak toto zobrazit (ideálně obě fotky).

**Comment by walley** [comment]
vymyslel sem zpusob jak oddelit rozestniky od zbytku fotek.  viz osmcz/api#47
