### ISSUE TITLE
Opening hours script a další závislosti

### ISSUE THREAD

**Issue by Krakonos** [osmcz/osmcz#101]
Ahoj,

dnes se osmap.cz načítá dost pomalu, protože server openingh.openstreetmap.de dost dlouho timeoutuje (ipv4). Než se zobrazí mapa, trvá to dost dlouho (třeba 1-2 minuty, nepočítal jsem to). To je hloupé. 

Obecně bych navrhnul přesunout tento script a potenciálně další na jednotné místo, abychom minimalizovali počet cnd, které můžou selhat. Evidentně dosti zásadně závisíme na rawgitu, takže to je zjevné místo.

**Comment by zbycz** [comment]
Dobrý postřeh, taky jsem včera koukal že se to nějak neloadovalo.
Opravím to hned na rawgití CDNku.

Souhlas - měli bychom používat zejména cdn.rawgit - ta je spolehlivá. Mapboxí bude tuším ještě spolehlivější, neb jsou komereční a taky děsně dobří :)

//edit eergh, nedělají releasy do githubu, takže cdn.rawgit nejde. řešení viz commit.
