### ISSUE TITLE
Zjištění GPS souřadnic bodu

### ISSUE THREAD

**Issue by JuraK** [osmcz/osmcz#102]
Velmi užitečná funkce, která často chybí je jednoduché zjištění GPS souřadnic uživatelem vybraného bodu na mapě. Hodně mi to chybí např. při nahrávání rozcestníků, když nemám exif záznam, ale vím, kde byl rozcestník v mapě -> potřebuji z mapy zjistit GPS konkrétního bodu. Navrhoval bych vlevo přidat novou ikonu. Mohla by toho časem umět víc, jako například zjistit objekty v okolí bodu, jako to je na osm.org.

**Comment by zbycz** [comment]
Přidal jsem jednoduchý controlek vlevo dolů - viz demo.

Není to ideální, ale víc času na to nemám, třeba to někdo rozšíří :)

**Comment by mkyral** [comment]
Pěkné, ale tak nějak mi chybí možnost zkopírovat aktuální souřadnice do schránky.

**Comment by vop-cz** [comment]
Hlaseni: ta featura na demu na mobilnim prohlizeci nechodi...

**Comment by zbycz** [comment]
Reaguje to jen na myš. Je to hotový plugin a nemám čas ho teď upravovat.
Řešení - na mobilu skrýt, souhlas?

**Comment by vop-cz** [comment]
no dela to tam psi kusy... na druhou stranu, kdyz by to bylo funkcni a dostupne nekde z nejakych pokrocilych nastroju, tak proc ne... jednak odecitat aktualni souradnice (ale bez mysi jak definovane?), soucasne take premistit mapu na zadane souradnice...

**Comment by mkyral** [comment]
Imho tenhle [plugin](https://github.com/zimmicz/Leaflet-Coordinates-Control) se mi jeví lépe.

Souřadnice aktualizuje po kliknutí na mapu a po kliknutí na to okýnko je možné souřadnice zkopírovat. Ještě bych tam chtěl přidat více formátů souřadnic. Každá na jednom řádku.

**Comment by zbycz** [comment]
Jj, klidně ten předchozí vyhoď a dej tam tenhle. Souhlas.
Jediná vtipná věc co by šla zachovat je to zaokrouhlovací precision - to
prosím případně přidej i do tohohle:
https://github.com/osmcz/osmcz/blob/master/js/controls.js#L74-L79

**Comment by mkyral** [comment]
Tak jsem si s tím včera hrál, ještě to poladím a odpoledne z vlaku snad pošlu.

**Comment by mkyral** [comment]
Tak první verze hotova d9e5f31af572cd685fe4c0b1064f6a1964e05644. Může být takhle?

Po kliknutí kdekoli do mapy:
![gpscoor1](https://cloud.githubusercontent.com/assets/155542/14543833/647db97a-0296-11e6-923c-ab1ae024ec9a.png)

Po kliknutí na souřadnice:
![gpscoor2](https://cloud.githubusercontent.com/assets/155542/14543836/65977a44-0296-11e6-98a0-f9fd8ef1d655.png)

K otestování v demu.

**Comment by vop-cz** [comment]
Technicky vyborne - SUPER!

titulek "Gps" opravit na "GPS"

navrhul bych (minimalne pro mobilni verzi) zmensit zakladni okno trvale 
zobrazene v mape

zajimavy by byl uzivatelsky volitelny format zobrazenych souradnic (co si 
budeme nalhavat, geocachingovy format je uzivatelsky nejzadanejsi)

zajimavy by byl i opacny postup - zadas souradnice a ukaze ti puntik v mape.

vop

---------- Původní zpráva ----------

Od: Marián Kyral 

Datum: 14. 4. 2016 v 23:16:46

Předmět: Re: [osmcz/osmcz] Zjištění GPS souřadnic bodu (#102)

Tak první verze hotova d9e5f31
(https://github.com/osmcz/osmcz/commit/d9e5f31af572cd685fe4c0b1064f6a1964e05644)
. Může být takhle?

Po kliknutí kdekoli do mapy:

gpscoor1 
(https://cloud.githubusercontent.com/assets/155542/14543833/647db97a-0296-11e6-923c-ab1ae024ec9a.png)

Po kliknutí na souřadnice:

gpscoor2 
(https://cloud.githubusercontent.com/assets/155542/14543836/65977a44-0296-11e6-98a0-f9fd8ef1d655.png)

K otestování v demu.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub
(https://github.com/osmcz/osmcz/issues/102#issuecomment-210152006) 

#

**Comment by mkyral** [comment]
> titulek "Gps" opravit na "GPS"

Hotovo

> navrhul bych (minimalne pro mobilni verzi) zmensit zakladni okno trvale zobrazene v mape

Myslíš to "lat: lon:"? S optimalizací na mobily si moc rady nevím, to bych nechal na @zbycz 
Asi by to chtělo předělat na normální tlačítko. Kliknu na něj - rozbalí se a ukáže souřadnice. Kliknu podruhé, rozbalí se box s více formáty. Kliknu na křížek, souřadnice se sbalí do výchozího tlačítka.

> zajimavy by byl uzivatelsky volitelny format zobrazenych souradnic (co si budeme nalhavat, geocachingovy format je uzivatelsky nejzadanejsi)

Jo to by nebylo špatné. Nějaké tlačítko na přepnutí plus zapamatování si přes cookie/přihlášený osm účet. To ale taky zatím nevím jak se řeší.

> zajimavy by byl i opacny postup - zadas souradnice a ukaze ti puntik v mape.

To bych řešil jinde. Viz: https://github.com/osmcz/osmcz/issues/95#issuecomment-193195014
Přece jen parsování GPS souřadnic bude kapku složitější - variant zápisu je hodně (E před nebo za, mezi souřadnicemi může být mezera, čárka, středník...)

**Comment by zbycz** [comment]
Moc hezký, Mariáne!!
1. doporučoval bych v tom malém popupu zobrazit pouze "Lat/Lon: 50.123,16.05", aby to šlo dobře kopírovat. Typicky chci zkopírovat jen čísla bez textu.
2. tlačítko přepnutí může být přímo ten zobrazený formát souřadnice v rozbaleném popupu
3. doporučuju formát D.DDDD zaokrouhlovat na počet míst dle zoomu (`var precision = OSM.zoomPrecision(map.getZoom());  ... lng = lng.toFixed(precision)`)
4. vyhledávání souřadnic opravdu nechme na Lepší geocoder https://github.com/osmcz/osmcz/issues/95#issuecomment-193195014
   Parsování souřadnic mám napsané, kdyby se do toho někdo chtěl pustit..
5. řekněte až to budu moc nasadit na osmap.cz

**Comment by mkyral** [comment]
> vyhledávání souřadnic opravdu nechme na Lepší geocoder #95 (comment)
> Parsování souřadnic mám napsané, kdyby se do toho někdo chtěl pustit..

Tak nahoď. Kde to máš? Na co čekáš?

**Comment by zbycz** [comment]
ad na co čekáš) Musel jsem nahrát celý nový repozitář old_osmcz_2010 :-) 

Parsování souřadníc je tady: https://github.com/osmcz/old_osmcz_2010/blob/master/script/parseCoords.js

K vyzkoušení nahoře po kliknutí do search okna na: http://zby.cz/osmcz-2010/#50.14,20.1
Kupodivu ten starý portál možná uměl spoustu zajímavých věcí (routování,kategorie vrstev,nastavení průhlednosti,osm-data), škoda že jsem ho nikdy nedokončil. Vlastně možná díky bohu :))

**Comment by vop-cz** [comment]
**KOLIZE !!!** grafického prvku okna se souřadnicemi na mobilu:

Při otevření hledání (ikona lupy) dojde k vyjetí obrazovky klávesnice. Tím dojde k vytlačení popup okna s GPS a to vyjede tak vysoko, že zakryje první řádek výsledků vyhledávání... Viz následující obrázek:

![quickmemo _2016-04-15-13-41-01](https://cloud.githubusercontent.com/assets/12752832/14560573/fcd1d7fe-0310-11e6-955e-9ba001a7003c.jpg)

**Comment by vop-cz** [comment]
BTW - na výše uvedeném se podílí i horní lišta, která "krade" výšku a pak i titulek "Najeďte myší na bod" .... což si teď uvědomu je zobrazeno JEN V REŽIMU ZAPNUTÉ AKTIVNÍ VRSTVY...

mmnt, jdu udělt test s vypnutou aktivní vrstvou...

**Comment by vop-cz** [comment]
Takhle to vypadá bez zapnuté aktivní vrstvy (viz níže). Žádná velká sláva. Zajímalo by mě, zda někdy nekdo používá ta tlačítka +/- Já je tedy nikdy nepoužil... A to ani na desktopu...

Nicméně asi by bylo řešením, aby se to okno se souřadnicemi za určitých okolností vypínalo... Lzte dovodit případy, kdy to bude někdo chtít vidět, konec konců při výchozím zobrazení (při reloadu stránky) tam to okno s GPS není a nevadí mi to. Objeví se až ťuknu do mapy... Čili bychom mohli stanovit pravidlo, za jakých okolností by zůstalo otevřené a kdy by zase mizelo...

Případně by mohlo mít okno své "zavírátko"...

![quickmemo _2016-04-15-14-11-38](https://cloud.githubusercontent.com/assets/12752832/14561105/7b0defc4-0314-11e6-86b3-a75cc477312f.jpg)

**Comment by walley** [comment]
+- pouzivam ja. Bez toho jaksi neumim jednou rukou zoomovat. A to hledani by mohlo byt uplne nehore aby se rozbalovalo do volnyho mista.

**Comment by mkyral** [comment]
@vop-cz  @zbycz  - ty kaskádové styly jsou na zabití. Ať dělám, co dělám, nedokáži posunout to gps okno dolů nebo to hledání nahoru :-(

**Comment by mkyral** [comment]
Díky. Ale nedá se říct, že by se situace nějak extra zlepšila :-D
Pruh s gps souřadnicemi je překryt copyrightem a problém dále přetrvává. Je z toho pěkný guláš.

![osmcz_gps](https://cloud.githubusercontent.com/assets/155542/14579305/354505e6-03a4-11e6-8f97-c5012bc0df99.png)

**Comment by vop-cz** [comment]
ja bych zkusil vyjit z toho, ze pri vyhledavani adresy nepotrebuji zjistovat
GPS. 

Co to tak navazat na sebe - oboji je svym zpusobem hledani... Myslim navazt 
principialne - nemuzu mit zobrazene oboji soucasne...

vop

---------- Původní zpráva ----------

Od: Marián Kyral 

Datum: 16. 4. 2016 v 07:29:20

Předmět: Re: [osmcz/osmcz] Zjištění GPS souřadnic bodu (#102)

Díky. Ale nedá se říct, že by se situace nějak extra zlepšila :-D

Pruh s gps souřadnicemi je překryt copyrightem a problém dále přetrvává. Je 
z toho pěkný guláš.

osmcz_gps 
(https://cloud.githubusercontent.com/assets/155542/14579305/354505e6-03a4-11e6-8f97-c5012bc0df99.png)

—

You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
(https://github.com/osmcz/osmcz/issues/102#issuecomment-210739323) 

#

**Comment by zbycz** [comment]
Hledání je provizorní (aka #22) - zatím jsem ho jen pousnul výše. Jinak se s ním nenechte rozrušovat :-)

Použitelné to je, jen uživatel musí před vyhledávnáním zavřít GPS popup..

Textík "Najeďte myší na bod.." jsem úplně odebral - časem má smysl ho zobrazit first-time-use při zapnutí aktivní vrstvy.

**Comment by mkyral** [comment]
Ad #22) Zkouším ten pelias, momentálně mám rozpracováno zobrazení výběru v aktivní vrstvě. Večer zkusím poslat.

**Comment by mkyral** [comment]
Viděl bych to tak, že by byla jedna ikonka "Nástroje" na kterou když kliknu, tak se mi vysune více ikonek (každá ikonka jiný nástroj). Lišta by pak šla zase po skončení zase zasunout aby nezabírala tolik místa. Podobně jako se teď vysouvá vyhledávání.

**Comment by zbycz** [comment]
Tohle vypadá funkční a doporučoval bych zavřít. Mariáne, jak sis to představoval s těmi nástroji? je to ještě aktuální? (případně založíš nové issue?)

**Comment by mkyral** [comment]
No tak jak jsem to popsal. Případně bych to nějak zamontoval do panelu. Třeba tohle se mi líbí: https://northlandia.wordpress.com/2015/03/27/leaflet-draw-implementing-custom-tools/

**Comment by mkyral** [comment]
Zavírám, na nástroje otevřu další issue.
