### ISSUE TITLE
Přidat sdílení mapy (poslání odkazu)

### ISSUE THREAD

**Issue by nesnera** [osmcz/osmcz#103]
Pokud to jen trochu jde, při odkazování na polohu používáme osm.org (např. [sraz](https://www.openalt.org/sraz_2016_04_brno)). Bude-li pro to ekvivalentní nástroj na .cz, rád přejdu.
Asi to bude chtít pořešit potlačení uvítací obrazovky pro tyto případy.

**Comment by zbycz** [comment]
Je možné využívat ekvivalentní URL (taková tajná feature) pro marker:

Čili například tohle funguje: 
http://www.openstreetmap.cz/?mlat=49.20310&mlon=16.59584#map=19/49.20310/16.59584&layers=A

Tohle `http://www.openstreetmap.org/node/708859543` bohužel ještě neumíme, ale moc rád bych!

**Comment by zbycz** [comment]
Tak mi to nedalo a udělal jsem to - už jsem chtěl fakt dlouho :-) Funkční i bez "Aktivní vrstvy".
Až to nasadíme na web, pak bude přímo možné toto: `openstreetmap.cz/node/1601837931`

V dev verzích jako: http://rawgit.com/osmcz/osmcz/master/index.html?node=1601837931
Prosím @vop-cz @mkyral @Krakonos aj. o otestování. Dík!

**Comment by zbycz** [comment]
Klikáním v aktivní vrstvě se mění přímo URL.

**Comment by mkyral** [comment]
Tak to je hustý :+1:   @zbycz Díky moc

**Comment by vop-cz** [comment]
Jo... nejak to funguje...
tedy v praxi si zapnu aktivni vrstvu, pak si najdu POI (super), ale pak musim vykopirovat z URL. Jo?

Systemove velky pokrok, snazim se jeste zamyslet nad uzivatelskou privetivosti... zvlaste pak na mobilu...

Na mobilu vyzkouseno (nejede tam ta featura vlevo dole se souradnicemi, ale to sem nepatri). Kdyz si timto postuperm najdu POI, pak mi na mobilu prijde jako nejrychlejsi metoda sdileni podrzeni prstu na odkazu "osm ID" v liste rozkliknuteho POI (vyjede nabidka sdileni na urovni operacniho systemu). Potom by tedy bylo asi reseni, aby tam byla ta sekce resena jako:
Sdilet odkaz:
osm ID: node/1234
osmap.cz: node/1234

Existuje i jina varianta, ze budu mit moznost jako na mapy.cz pomoci nejake ikony (JavaScript procesu) bud vykopirovat nejake tinyURL, pripadne ze by ten script donutil operacni system udelat Ctrl+C ? Utopie?

BTW: na prikladu POI Praha je videt jeste jedna nedokonalost - lista detailu POI nabizi rozkliknout "Dalsi jmena", pak se jich vysype asi 40, ale uz to nejde zarolovat...

**Comment by zbycz** [comment]
řešení je sdílet celou aktuální adresu stránky ta obsahuje i informaci o zoom levelu a případných zapnutých vrstvách.

Ale souhlas že v poi-popupu by mohl být odkaz typu osmap.cz/node/123 - hotovo. Ten odkaz na osm.org už není třeba, stači třeba jen v expertním módu.

**Comment by zbycz** [comment]
> BTW: na prikladu POI Praha je videt jeste jedna nedokonalost - lista detailu POI nabizi rozkliknout "Dalsi jmena", pak se jich vysype asi 40, ale uz to nejde zarolovat...

Pokud to vadí, založ prosím issue (aka #108 ) :-) dík!

**Comment by vop-cz** [comment]
odkaz osmap.cz/node/1234 na demu nefunguje

404 Not Found

**Comment by zbycz** [comment]
Ano, to je správně - ještě to není nasazené na webu osmap.cz - zatím jen na rawgitu..
