### ISSUE TITLE
Nahrávání rozcestníků na old.osmcz - špatný odkaz na kct_tiles vrstvu

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#105]
V okně pro nahrávání rozcestníků se od určitého zoomu překryje mapu hnusná růžová barva. Dle všeho je to způsobené špatnou url kct_tiles vrstvy. Je použito http://openstreetmap.cz/kct_tiles/xxx, ale správně by mělo být http://tile.openstreetmap.cz/kct_tiles/xxx

![osmgp](https://cloud.githubusercontent.com/assets/155542/14472754/e1cf3e60-00f4-11e6-8d6b-e99dd2de9ae1.png)

**Comment by walley** [comment]
opraveno
