### ISSUE TITLE
Horní lišta na mobilu zabírá mrak místa

### ISSUE THREAD

**Issue by vop-cz** [osmcz/osmcz#107]
Predevsim pri praci s bocnimi listami je horni lusta vrazedny zabijak mista.

Napr.:

pri otevreni listy zjistuju, ze nevidim mapu (specificka situace si to muze vyzadovat)
![vyska](https://cloud.githubusercontent.com/assets/12752832/14501621/9ccf7934-01a7-11e6-86c8-0a0c13eecbc9.jpg)

takze otocim mobil nalezato a mapu sice vidim, ale horni lista ukrajuje uplne hruzostrasne mnozstvi mista
![sirka](https://cloud.githubusercontent.com/assets/12752832/14501663/cddd47cc-01a7-11e6-8844-b2240e48e3a3.jpg)

Navrhuju na mobilu tu horni listu maximalne potlacit, mozna vzdy pri lezatem provedeni (to zere misto uz z principu) a pri postaveni na vysku ji umoznit za nejakch okolnosti skryvat...?

_Pozn. na okraj - skutecne rozliseni toho mobilu a tech screenshotu je 1440x2392px, zde rozmer hrany 4x mensi_

**Comment by zbycz** [comment]
Bylo by to hodně předělání celého konceptu webu.

Na mobilu je to myšlené tak - že když máš sidebar - vlastně je to fullscreen content. A neměl bys vůbec vidět mapu - klidně to tak předělám, aby to nedráždilo. 

Ale hlavně - prostě mobil není počítač. Byla by velká chyba přizpůsobovat desktopový web mobilu - tam se používají UI kompenty jinak - viz jak to má google maps.

Zavírám protože si myslím že to je feature, nikoliv bug :-)
Pokud chceš dá se uvažovat, že lišta zmizí v "expertním režimu". Může na to udělat issue - hodilo by se.
