### ISSUE TITLE
Expertni mod - fullscreen bez horni listy

### ISSUE THREAD

**Issue by vop-cz** [osmcz/osmcz#109]
_Na zaklade drivejsi debaty v jinem issue #107 presouvam na pozdeji do Expertniho modu (at je tim mysleno cokoliv, napr. mod pri zalogovani OSM uzivatele, nebo po prepnuti v budoucim rozhrani Nastaveni):_

Predevsim pri praci s bocnimi listami je horni lista **na mobilnim zarizeni** vrazedny zabijak mista.

Napr.:

pri otevreni listy zjistuju, ze nevidim mapu (specificka situace si to muze vyzadovat)
![vyska](https://cloud.githubusercontent.com/assets/12752832/14501621/9ccf7934-01a7-11e6-86c8-0a0c13eecbc9.jpg)

takze otocim mobil nalezato a mapu sice vidim, ale horni lista ukrajuje uplne hruzostrasne mnozstvi mista
![sirka](https://cloud.githubusercontent.com/assets/12752832/14501663/cddd47cc-01a7-11e6-8844-b2240e48e3a3.jpg)

_Pozn. na okraj - skutecne rozliseni toho mobilu a tech screenshotu je 1440x2392px, zde rozmer hrany 4x mensi_

**Comment by mkyral** [comment]
Tak toto by mohl odstranit fullscreen režim #158 . Už jsem to testoval, ale má to ještě nějaké mouchy. Panely nejsou videt vůbec :-D

**Comment by mkyral** [comment]
Fullscreen režim nasazen ve verzi 0.17
