### ISSUE TITLE
Ukázat rozcestníky bez fotografie

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#11]
Bylo by fajn mít možnost zobrazit si rozcestníky, které nemají fotografii.

**Comment by mkyral** [comment]
Tak musím říct, že díky té Petrově vrstvě jsou teď rozcestníky bez fotky krásně vidět.

![chybejici_rozcestniky](https://cloud.githubusercontent.com/assets/155542/12228434/bbe93a0e-b83b-11e5-825d-6782308960ca.png)

**Comment by zbycz** [comment]
Jestli to takto dostačuje, tak prosím issue zavři.

**Comment by mkyral** [comment]
Mně stačí, když tak se to zase může otevřít ;-)

**Comment by walley** [comment]
je potreba napsat nejaky komparator mezi body v databazi fotek a body v osm a nekam vyjet seznam osm bodu co nemaji v dosahu fotku, jeho soucasti by melo byt i vytvoreni tabule na svazani id fotky a id rozcestniku v osm.

**Comment by zbycz** [comment]
Souhlas, pokročilejší řešení výhledově.. jak bude čas :)

**Comment by mkyral** [comment]
Na to by asi byl nejlepší nový repozitář - rozcestníky backend / server api nebo tak nějak. Na serveru by se udělal nějaká stránka, na kterou by pak vedl odkaz z frontendu.

**Comment by zbycz** [comment]
Souhlas. Walley potvrdil v #20, že by to na github nahrál.
