### ISSUE TITLE
Položky v popup vrstvě POI lze rozevřít, ale ne zavřít

### ISSUE THREAD

**Issue by vop-cz** [osmcz/osmcz#111]
Lista detailu POI nabizi rozkliknout sdruzene polozky jako napr. "Dalsi jmena". Rozevreny seznam vsak nelze zase zavrit. V nekterych pripadech jako je napr. POI "Praha" se "vysype" asi 40 novych radku s narodnimi variantymi slova Praha, ale uz to nejde zarolovat...

**Comment by zbycz** [comment]
To bude asi oříšek, protože mě to funguje na desktopu i na mobilu (iphone5). Zkuste asi ostatní nareportovat, komu se povedlo zreplikovat.

viz http://rawgit.com/osmcz/osmcz/master/index.html?node=1601837931

**Comment by walley** [comment]
firefox nefunguje, odkaz zobrazit zmizi a misto nej nic nenaskoci.

**Comment by mkyral** [comment]
@walley Která verze FF? Desktop nebo mobil? Mně to funguje normálně FF38 na linuxu.

**Comment by walley** [comment]
seamonkey 2.39 
Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0 SeaMonkey/2.39
jeste to muzu prozkoumat na vic verzich, ale je to hodne novej engine

**Comment by walley** [comment]
original browser na cm 13 aneb android 6 taky nefunguje.

**Comment by mkyral** [comment]
Máš nějaké divné prohlížeče ;-)

Ad vnitřní prohlížeče... No ony jsou určeny na prohlížení html stránek, ale osmap.cz je spíše javascriptová aplikace. Takže pokud nemají js implementován správně, tak budou mít s osmap.cz problémy. Zkus FF pro mobily, nebo chrome. Ve FF mi všechno funguje správně.

Nicméně teď to zkouším v konqueroru na KDE4 a tam to taky nefunguje. Akorát nevím jak zjistit kde je problém :-(

**Comment by walley** [comment]
poslete odkaz na obrazek jak to ma vypadat aby to fungovalo:), asi delam neco spatne. Nefunguje to ani v chromiu  37.0.2062.120. V mobilnim ff taky ne (aktualni beta). 

pred a po tady: http://map.openstreetmap.cz/bug/

**Comment by mkyral** [comment]
Však to je ono ne? Měl by se otevřít ten levý panel s detaily. Co se ti na tom nezdá? :-D

Ale ještě by to asi chtělo patřičně upravit přiblížení mapy a nastavit daný bod do středu obrazovky.

**Comment by walley** [comment]
neexistuje moznost jak schovat seznam dalsich jmen po tom co se da zobrazit. Tak chapu tenhle bugreport.

`<p style="display: none;">`
`<b>Další jména:</b>`
`<a onclick="$(this).parent().hide().next().show();return false" href="#">zobrazit</a>`
**^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tady k tomuto neexistuje odpovidajici schovat**
`</p>`
`<div style="">`
`<h5>Další jména:</h5>`

**Comment by mkyral** [comment]
Ahá. No tohle tam není, tak to fungovat nemůže. Ale @zbycz narážel na "POI "Praha" se "vysype" asi 40 novych radku s narodnimi variantymi slova Praha, ale uz to nejde zarolovat..."

Na to "zobrazit" se chystám. Mělo by to být úplně stejně jako u otevírací doby:

``` js
ret.push(' <a href="#" onclick="if ($(\'.oh-extended\').is(\':visible\')) {$(\'.oh-toggle\').html(\'&#9660;\');} else {$(\'.oh-toggle\').html(\'&#9650;\');} $(\'.oh-extended\').toggle(200); return false"><span class="oh-toggle">&#9660;</span></a></h5>');
```

**Comment by zbycz** [comment]
"Its not a bug, its a feature"

Ale že to byla oprava na půl řádku, tak doplněno :)

**Comment by zbycz** [comment]
A příště pokud možno bug-report s obrázkem rovnou :D

**Comment by walley** [comment]
no skoda ze obrazky nejdou vkladat rovnou sem

**Comment by mkyral** [comment]
@walley Jdou - myší je musíš přetáhnout do editoru.

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by walley** [comment]
nojo sem slepej primo pod textboxem je odkaz, na pretahovani nemam funkcni nastroje, mozna nautilus by sel spustit ale buhvi ...

**Comment by mkyral** [comment]
Hehe. Ono stačí kliknout na "selecting them", otevře se normální souborový dialog a po potvrzení je soubor vložen do editoru - to jsou mi novinky. To tam myslím předtím nebylo.
