### ISSUE TITLE
cz_foto_ref

### ISSUE THREAD

**Issue by vop-cz** [osmcz/osmcz#116]
K diskusi - další vývojový krok k současné Wallyho databázi rozcestníků.

1) jde o možnost uživatelského pořizování fotek k jednotlivým POI (autorizovanými uživateli = mappery)
2) fotky neslouží k mapování, ale k zobrazování u POI jako další level služby uživatelům (vidim, jak rozhledna vypada)
3) jeden POI může mít více než jednu fotku, mělo by to ale podléhat nějaké editorské práci, aby se z toho nestala fotogalerie blabolu
4) technicky by to mohlo byt realizovane pomoci specialniho tagu, napr. cz_foto_ref=_, jehoz hodnotu by bylo mozne generovat po uploadu fotky (uzivatel ma na vyber, zda chce k fotce priradit novou hodnotu = POI jeste foto nema, nebo naopak zadat stavajici, drive generovanou hodnotu = POI jiz foto ma a pridavame k nemu dalsi). Vygenerovanou hodnotu tagu by pak priradil jako cz_foto_ref=_ k patricnemu POI.
5) datove to znamena jednoduchou MY-SQL databazi pro ukladani hodnoty cz_foto_ref=\* a maleho mnozstvi editorskych informaci (napr. "smazano", "nevhodne" apod.), mozna typove rozliseni (ve fyzicky stejne databazi by pak mohly zustat soucasne rozcestniky a podobne fotky sesbirane Wallym) vstupni processing pri prepocteni fotky do omezeneho rozliseni a do nahledu a pak take rozhrani editacni spravy (mazani nebo pridavani fotek, zmena typoveho tagu apod.)
6) hardwarove by to znamenalo hostovany stroj nebo napr. vlastni stroj (coz by melo byt jednim z cilu pravniho subjektu) v housingu. Nebo minimalne nejaky maly NAS - 1 TB datoveho objemu = ca 250.000 fotografii

**Comment by mkyral** [comment]
A proč ne wikimedia commons? Jediné co mně napadá je trochu složitější nahrávání na commons - nutnost zjistit azimut, pokud fotka nemá gps souřadnice. A ta hromada kategorií při nahrávání spíše mate než pomáhá.

Ale jinak to má výhodu v tom, že není nutný vlastní server, nemusíme fotit všechno sami, můžeme využít spolupráce s wikipedisty. Na nás je jen přidání příslušných wikipedia/wikimedia/wikidata tagu(ů) k příslušným POI.

**Comment by vop-cz** [comment]
No ja Wikimedia commons znam jen povrchne, ale chapal jsem to jako databazi fotek primarne pro wiki hesla. A kdyz chci dat fotku kaplicky a ta kaplicka nema wiki heslo, tak je to z pohledu wiki ztracena fotka, protoze az nekdo bude to heslo psat, tak nebude vedet, ze ta fotka k tomu existuje...

Druhy duvod je motivace mapperu - neco jako gamifikace... Viz stejna situace s rozcestniky...

**Comment by mkyral** [comment]
Tak je sice pravda, že všechny fotky na wikipedii jsou z [wikimedia commons,](https://commons.wikimedia.org) ale už to neplatí naopak. Ne vše, co je na wikimedia commons musí být na wikipedii. To by tam nemohly být třeba [rozcestníky,](https://commons.wikimedia.org/wiki/Category:Hiking_and_footpath_fingerposts_in_%C4%8Cesk%C3%A1_L%C3%ADpa_District), které samostatná hesla ve wikipedii nemají.

A sice nevím, jaká jsou pravidla pro psaní článků, ale konkrétní obrázek lze dohledat přes systém kategorií, podle polohy, případně dle názvu.

Ono by to asi chtělo nějaký jednoduchý nástroj na párování commons a osm. Něco jako je wikipedia plugin v josm. A nebo jako tool na osmap.cz. V aktivní vrstvě vyberu POI, fotku commons, dám přiřadit a on se přidá wikimedia_commons tag na daný OSM objekt. 

To mi připomíná, že jsem chtěl udělat ten návod na přidávání wikipedia tagů v JOSM.

Ad gamifikace - nejsem sice moc velký příznivec těhle věcí, ale podle mně by to šlo zařídit i s commons.

**Comment by walley** [comment]
pozn: muj duvod pro zalozeni vlastni databaze a tim padem duplikovani commons byl hlavne proces uploadovani fotky na commons, ktery asi v pulce prestane bavit a clovek uz tam nic nahravat nechce.

Asi uz to je dnes lepsi. Taky maji uploadovatko vlastni: https://play.google.com/store/apps/details?id=fr.free.nrw.commons - ted uz vypada docela dobre.

**Comment by walley** [comment]
co by melo byt hodnotou toho referencniho tagu? osm id? jmeno ci jiny klic? Prapuvodni zamer je mit vazbu na osm id s rizikem ze osm id se zmeni. Poloha bude pritomna vzdy a osm id je mozno opravit.

**Comment by zbycz** [comment]
Jsem pro využití nějaké stávající (celosvětové) služby. Ještě se nabizi mapillary, ale Commons je lepší.

Dle mého by vazba měla probíhat tak, že na osm objekt přidáme tag 'image_url' případně další.. Párování přes osmid není systémové.

Výhodou je ze image_url bude moct používat konzistentně kdokoliv na světě. A kdo chce klidně tam může dát mapillary link.

**Comment by walley** [comment]
resime tady pridani reference do osm na fotku, nebo f\do fotky na osm?

**Comment by vop-cz** [comment]
ad vyuziti jineho stavajiciho systemu:
fyzicke ulozeni OK, jde o to, jak se to bude tvarit pro autora navenek. Kdyz bychom pri akci "rozcestniky" vyuzivali stavajici reseni treba wikimedia commons, nikdy bychom nemeli takovy uspech pri sbirani fotek - lide by to nevzali za "svuj" projekt. Tedy reseni navozujici pocit uzivatele (mappera), ze jde alespon castecne o unikatni OSM CZ projekt, je podle me pro uspech sbirani dat klicove.

ad reference:
moje predstava byla, ze POI dostane unikatni referencni udaj (treba 8mistny kod) a ten se pripoji ke kazde fotce toho POI. U jednoducheho kliknuti na POI na osmap.cz se zobrazi rekneme nejnovejsi fotka s danym ref a kdyz by bylo vice fotek k danemu ref, tak by se zobrazil odkaz "Další fotografie místa".

ad konkretne wikimedia commons:
fakt si neumim v praxi predstavit, ze bychom dokazali vytvorit vysledek, ktery by byl plnohodnotny pro obe strany - pri nahravani na commons je proces docela pomaly (kdyz si predstavim, ze bych mel nahravat 10 a vice fotek), protoze aby byl naplnen cil te databaze, je potreba mj. soubor pojmenovat, pridat mu dostatecny pocet kategorii (to je nejvetsi pruda) a jeste pripsat nejaky komentar. Zkusil jsem si to ted u jedne fotky a **ja osobne bych rozhodne zadne fotky nesbiral** a k POI nenahraval, kdyz bych mel postupovat timto zpusobem

ad konkretne mapillary:
nemam zkusenosti - jsme schopni dostat od mapillary ref nebo unikatni URL na ten snimek? A vzhledem k tomu, ze je to maly startup, jaka je jistota zachovani tech dat? Dovolili by nam si to zrcadlit? Asi tezko...

**Comment by mkyral** [comment]
ad konkretne wikimedia commons:
Jop. To nahrávání není zrovna nejideálnější. Nicméně třeba by to šlo nějak zjednodušit. Známe souřadnice, víme co to je za objekt, takže vygenerovat kategorii "kostely v okrese Praha-západ" by nemuselo být až tak složité. Ale to by bylo potřeba prozkoumat, jestli se dá na commons nahrávat dávkově, případně za jakých podmínek.

Add mapillary:
Zkoušel jsem a narazil jsem na tu jejich ochranu identity - rozmazávání obličejů - rozmazávalo mi to i texty na rozcestnících. Dá se to sice vrátit, ale je to opruz. Musíš ty oblasti označit a následně to prochází lidskou kontrolou, takže to trvá trochu déle.

**Comment by mkyral** [comment]
@vop-cz Na rootu se v [Softwarové sklizni](http://www.root.cz/clanky/softwarova-sklizen-25-5-2016/) objevil program Commonist. Je to java program pro nahrávání fotek na commons. Zatím jsem nezkoušel, ale dle screenshotu exif nijak neřeší. Takže když bude, tak bude, jinak nebude :-D

Chtělo by to prozkoumat API k wikimedia commons. Nemělo by být nikterak složité a bylo by možné přidat do aktivní vrstvy tlačítko nahrát fotografii, které by tu fotografii odeslalo rovnou na commons. Akorát by asi bylo dobré zároveň danou fotku navázat na daný OSM objekt.

**Comment by walley** [comment]
zaviram, odkazy na externi zdroje v osm jsou, ale nikdo je neupdatuje, tudiz je lepsi je nemit
