### ISSUE TITLE
presun rozcestniku

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#119]
funkcionalita uz je udelana v guideposts.js, 
zrovna davam dohromady ui, tahle issue by mohla slouzit jako zpetna vazba pro ui a obsah sidebaru atp.

**Comment by mkyral** [comment]
Super. Jsem zvědav na první verzi ;-)

**Comment by walley** [comment]
not to ja taky

**Comment by walley** [comment]
funkcni pracovni verze

http://map.openstreetmap.cz/work2
navod:
vybrat rozcestnik, dule kliknout na move (kde by to melo byt ve finale?)
otevre se sidebar
kliknout do mapy, vzniknuvsim bodem lze dale hejbat
v sidebaru kliknout na cudl
a je to.

**Comment by mkyral** [comment]
Nejde to zrušit - když si to rozmyslím, tak i když popup zavřu, tak mi tam sidebar zůstane trčet.

> vybrat rozcestnik, dule kliknout na move (kde by to melo byt ve finale?)

Dolů jsem chtěl zakomponovat ty tagy.  Možná by se ještě pod ně mohla dát dvě tlačítka - upravit a přesunout.

**Comment by walley** [comment]
zrusit to nejde protoze premazu kompletne vnitrek toho sidebaru, kde je originalne to X.
Musim to tam pridat zpet:)

v te bubline: tlacitka jako opravdovy tlacitka s napisem upravit a presunout?

**Comment by mkyral** [comment]
Ideálně stejně jak jsem to udělal v gp-check.js:

![tlacitka](https://cloud.githubusercontent.com/assets/155542/14781023/3b3bc258-0ae0-11e6-8a9e-fcacbe0f9a83.png)

``` js
            // Edit in iD button
            html_content += '<a href="http://www.openstreetmap.org/edit?editor=id&node=' + feature.id + '"><button type="button" class="btn btn-default btn-xs">';
            html_content += '   <div class="glyphicon glyphicon-pencil"></div> iD';
            html_content += '</button></a> ';

            // Edit in JOSM/Merkaartor button
            html_content += '<a href="#"><button type="button" class="btn btn-default btn-xs"';
            html_content += ' onclick="osmcz.gpcheck.callRemoteEditor(' + feature.geometry.coordinates + ')">';
            html_content += '<div class="glyphicon glyphicon-pencil"></div> JOSM / Merkaartor';
            html_content += '</button></a>';
```

**Comment by walley** [comment]
tak ty butony udelam stejne i s obrazkama.

**Comment by walley** [comment]
tak cudliky a Xko opraveno.
Kdyz ten sidebar ale zavres, tak uz nejde ukoncit akce presouvani. 
To je nutno nejak vyresit (zatim koukam na to jak pridat sidebaru event na close:).

**Comment by walley** [comment]
zavreni krizkem zrusi i proces presouvani
pridan cudl zrusit, dela to same

**Comment by hynekcz** [comment]
pekny vecer, vcera jsem nahral par rozcestniku bez kontroly GPS v exif  a zjistil jsem, ze jsou souradnice spatne.. chtel jsem opravit pomoci presunu fotky rozcestniku, ale nejak mi to nefunguje.. nejde mi ani vlozeni ID rozcestniku, i kdyz uz jsem zkousel 2x editovat. delam neco spatne? jeden z rozcestniku zde: http://api.openstreetmap.cz/table/id/6199

**Comment by walley** [comment]
Vsechny zmeny probehly v poradku. Ony se neprojevi hned, musi se rucne schvalit nez se naimplementuje oauth. Pak to  prihlasenym pujde hned.

**Comment by mkyral** [comment]
:+1:

**Comment by walley** [comment]
Zkousim to na mobilu a funguje to. Dokonce je centimeter mista na soupani s  markrem. Supr. Jen text v sidebaru je  na  vysku o kpusek delsi a cudly se nevlezou.

**Comment by mkyral** [comment]
Takový nápad. Bylo by možné, namísto vytvoření extra markeru, umožnit rovnou přesun toho rozcestníku? Původní polohu by pak mohlo ukazovat třeba nějaké barevné kolečko (jako u aktivní vrstvy)

Bylo by to více intuitivnější - nemuset klikat do mapy aby se objevil marker, ale rovnou by se posunul rozcestník. Akorát nevím, co s tím otevřeným popupem.

**Comment by mkyral** [comment]
Jo a ještě dvě věci:
1) Aktivní vrstva a postranní panel se nemají rádi. Asi by to chtělo buď ten box aktivní vrstvy skrýt, nebo jej posunout doprava, aby byl vedle panelu.
2) Tlačítka v panelu by chtěla nastylovat: `class="btn btn-default btn-xs"`

![side_panel](https://cloud.githubusercontent.com/assets/155542/14898463/2792a09c-0d87-11e6-9821-73f265908930.png)

**Comment by walley** [comment]
ta bublina aktivni vrstvy by mela byt fixovana na mapu nejak at to je vedle sebe, sidebar si mapu posune.
to bych resil v nake uplne jine issue.

k tomu napadu presouvani rozcestniku misto extra markeru - to by asi mozne bylo, ale zas to necham na jinou issue. tohle zaviram nebot presun presunuje.
