### ISSUE TITLE
Úvodní splashcreen je celkem otravný

### ISSUE THREAD

**Issue by Krakonos** [osmcz/osmcz#12]
Jeho existence mi nevadí, ale:
- Není zřejmé, jak se ho zbavit (chvíli jsem hledal křížek, než mě napadlo scrollnout jinde; ani klik jinam nepomohl)
- Nemusel by se zobrazovat pokaždé, třeba jenom při první návštěvě, nebo až po nějakém intervalu...

**Comment by jzvc** [comment]
Souhlas, priklanim se ke krizku + timeout (aby zmizel sam i bez akce) + cookie aby se nezobrazoval pokazde ... ze je treba s mapou zahybat/zoom nedojde kazdemu.

**Comment by mkyral** [comment]
Nebo místo křížku nějakou šipku s textem "Přejít na mapu". Plus samozřejmě automatické sbalení po nějaké době.

Zároveň by ale mělo být jasné, že tam nahoře něco je. To bych asi řešil podobně jako mají mapy.cz ten boční panel - malá šipka na okraji, která je stále vidět a buď zobrazí, nebo schová ten obsah.

**Comment by zbycz** [comment]
To je relikt toho původního rozložení, kde se mapa dala posouvat jako easter-egg :-)

Psal jsem, že v tuhle chvíli proběhly jen malinké úpravy a že se jedná o draft, čili mnoho věcí (včetně téhle, či třeba pamatování polohy..) jsou jasné, že potřebují změnit :-)  Ikdyž dobře, že issuečka tvoříte, dá se ta práce potom líp prioritizovat. :runner:

**Comment by zbycz** [comment]
Opraveno v rámci kompletního přestylování.
Výsledek viz odkaz DEMO na https://github.com/osmcz/osmcz
