### ISSUE TITLE
gc-check - formulář pro nahrání fotografie rozcestníku

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#120]
Diskusní a TODO issue k nové funkcionalitě z commitu: 8bfaf425bc37dd3dd92b69b0eac3cc5bd45883d4

![dgbegbjh](https://cloud.githubusercontent.com/assets/155542/14844043/ea4b1bca-0c54-11e6-83d4-46a833b9f57b.png)

Formulář má kontrolu na velikost souboru a meze souřadnic, vyžaduje vyplnění autora (ten se následně uloží do cookies). Pokud je nějaký problém, upload nepovolí.

Souřadnice a ref jsou předvyplněny z OSM (ref jen pokud je).

TODO:
- [x] Chybí indikace, že probíhá nahrávání - nějaká animace?
- [x] Přidat kontrolu, zda má fotka souřadnice v exifu a umožnit jejich použití místo souřadnic z OSM

**Comment by mkyral** [comment]
@walley @tkas - můžete na to mrknout z funkční stránky?
@zbycz Můžeš prosím mrknout na kód, jestli tam nemám nějaké blbosti? Skládal jsem to z různých kousků, co jsem na netu našel a sice to funguje, ale třeba ne ve všech prohlížečích.

Díky

**Comment by mkyral** [comment]
Tak jsem včera zabil hodně času s tím Exifem a zatím se nepovedlo :-(

Když si ten kód krokuji, tak je vše OK, ale když to běží normálně, tak se mi vygeneruje náhled a exif se nenačte. Dle všeho je problém v těch asynchronních voláních, ve kterých jsem se ztratil. Potřeboval bych odborníka na js ;-)

Viz: https://github.com/bartvanderwal/exif-js/blob/master/README.md

> **Important:** Note that you have to wait for the image to be completely loaded, before calling getData or any other function. It will silently fail otherwise.

**Comment by mkyral** [comment]
Tak dobrá zpráva. Exif se povedlo zkrotit. Člověk by nevěřil, že taková drobnost, jako je pořadí atributů v tagu <img /> může mít takový katastrofální vliv na funkčnost. Správně je nejprve `onload="..."` a až pak `src=""` :-(

Akorát se k tomu teď nedostanu, takže pokračování snad příští týden.

Mimochodem, ještě uvažuji o přesunu formuláře z popupu do levého panelu. Stejně jako udělal @walley přesun rozcestníku. Umožní to zobrazení polohy fotky z exifu na mapě. Bude pak vidět, co je přesnější.

**Comment by zbycz** [comment]
Vypadá to velmi užitečně! Z hlediska kódu připomínky nemám. :-)

**Comment by mkyral** [comment]
Tak jsem doplnil exif, zobrazení vzdálenosti OSM vs. Exif a upravil vzhled formuláře. Bylo s tím hodně sra*í, pořád mi to dělalo něco úplně jiného, ale nakonec to vypadá docela slušně.

![gc-check-form](https://cloud.githubusercontent.com/assets/155542/15161966/cff513d2-1700-11e6-963d-640b41d21bcf.png)

Ještě by se mi líbil ukazatel, kde přesně jsou ty exif souřadnice na mapě.

**Comment by mkyral** [comment]
Základní verze funguje, na chyby a požadavky na rozšíření otevřete prosím extra issue.

TODO: vyřešit marker pod popupem.
