### ISSUE TITLE
Stránka o nahrávání rozcestníků

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#123]
Hledal jsem hledal, ale ještě nemáme žádnou stránku pojednávající o vrstvě "Fotky rozcestníků". Ta by měla obsahovat jednak obecné informace o projektu, dále by mohla obsahovat:

statistiky: http://api.openstreetmap.cz/table/count plus věci jako počet rozcestníků bez přiřazeného tagu (s možností rozkliknout si seznam - nutno dodělat v API), seznam tagů a jejich četnost, předvybrané některé tagy (například: `rozmazané`), které mi třeba rovnou vygenerují seznam fotek, které je potřeba přefotit.

žebříček: http://api.openstreetmap.cz/table/leaderboard

Různé podivnosti na dořešení - třeba fotky se souřadnicemi 0,0 - na to se dá využít api call http://api.openstreetmap.cz/table/close?lat=0&lon=0&distance=1000 - stačí z toho geojsonu udělat nějakou tabulku s dvěma okýnky Lat/Lon a tlačítkem přesunout. Uživatel jen vloží správné souřadnice a změnu odešle.

Ta poslední část by mohla být třeba dostupná pouze pro přihlášené mappery.

**Comment by vop-cz** [comment]
Ja trouba mam neco na toto tema rozepsano, ale ma to uroven dulezitosti (jen v OSM sfere) asi tak 20... Tedy si na danou stranku bookuji tematicky blok jak fotky delat a jak nedelat, jak je postprodukovat apod. Zebricky a odkazy na editaci chybnych rozcestniku ponecham na nekom jinem...

**Comment by walley** [comment]
tak uz to je na strance tak to tady zavreme

**Comment by vop-cz** [comment]
Mam dojem ze to tam neni cele. Chybi jeste popsat postup uplodu. Viz wiki:

**Co s nafocenými snímky**
Příklady postprodukčních úprav jsou na této stránce v galerii. Postup 
uploadu do databáze, nebo správa snímků v databázi, bude popsán později.

vop

**Comment by vop-cz** [comment]
...a docela se mi zamlouva mylenka v prvnim prispevku v issue - na podstranku (tedy na OSMcz ne na wiki) pridat nejake generovane statisticke informace, bud jen informativni, nebo i analyticke (tedy generovane odkazy na necim podivne fotky apod.)
