### ISSUE TITLE
Aktualizace šablony stránky - OSM id

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#124]
Na hlavní stránce nám funguje přihlášení k OSM. Tato možnost ovšem v šabloně v repozitáři chybí a tím chybí i na rawgitu. Takže momentálně není možné vyvíjet funkcionality, které by byly dostupné pouze pro přihlášené mappery.

Napadá mne například přidání speciálních vrstev, které mappeři ocení, ale normální uživatelé je nepotřebují. Například všechny RUIAN vrstvy z poloha.net, LPIS.

@zbycz Bylo by možné tu šablonu aktualizovat?

Díky

**Comment by vop-cz** [comment]
Ano, od zacatku se uvazuje v te rovine, ze mapperi (zalogovani jedinci) budou mit k dispozici jine nastroje (nazyvame to analyticke vrstvy).

V dalsim levelu pak moznost osobniho nastaveni, napr. co chci a nechci videt, protoze nektere veci (vrstvy) me fakt nezajimaji (zvlaste kdyz jich je moc), ne/zobrazovani ruznych (napr. napovednych) hlasek apod.

**Comment by zbycz** [comment]
Duplikát k hotovému #166 ... info o přihlášeném je v `osmcz.user`.

Ovšem i tak si myslím, že by mělo jít navrhnout UI jednotný nehledě na přihlášení (například jak jsi to vyřešil v layer switcheru).
