### ISSUE TITLE
Odkaz na wikipedii nefunguje z mobilního browseru

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#128]
Wikipedia si tam hodí prefix "m." a pak to neběží:

https://www.m.wikipedia.org/wiki/cs:Morov%C3%BD%20sloup%20(Brno)?uselang=en

Díky za report: aceman444 na sotmu

**Comment by mkyral** [comment]
Tak správný odkaz pro mobily je: https://cs.m.wikipedia.org/wiki/cs:Morov%C3%BD%20sloup%20%28Brno%29?uselang=en

Teď bych jen potřeboval detekovat mobily. Ideálně stejně jako wikipedie.

Nebo pomocí:
http://stackoverflow.com/questions/11381673/detecting-a-mobile-browser
https://github.com/kaimallea/isMobile

Ale když tak na tím uvažuji, je docela možné, že je problém na straně wikipedie. Když už se musí vrtat v url, měli by to přesměrování udělat pořádně.

**Comment by walley** [comment]
jquery umi detekovat mobily

**Comment by mkyral** [comment]
@walley Tak zdá se, že už ne:

> The jQuery.browser() method has been deprecated since jQuery 1.3 and is removed in 1.9. If needed, it is available as part of the jQuery Migrate plugin. We recommend using feature detection with a library such as Modernizr.

http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed

**Comment by mkyral** [comment]
Hmm, tak jsem myslel, že stačí vykopnout www, ale na mobilu si klidně dosadí www.m.xxx => mají tam bug v přesměrování.

**Comment by mkyral** [comment]
Tak jsem nakonec našel, kam se hlásí chyby ve wikimedia skriptech: https://phabricator.wikimedia.org/T137242

**Comment by mkyral** [comment]
Druhý pokus zdá se vyšel.
