### ISSUE TITLE
HTTPS verze blokuje mixed content, tím se nenačítá mapa (=úvodní stránka)

### ISSUE THREAD

**Issue by Piskvor** [osmcz/osmcz#129]
Při načtení webu přes HTTP se nepodmíněně přesměruje na HTTPS (to je samo o sobě Dobře), ale pak se stane tohle, a stránka je prázdná (z konzole):
- (index):1 Mixed Content: The page at 'https://openstreetmap.cz/' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js'. This request has been blocked; the content must be served over HTTPS.
- leaflet.markercluster.js:6 Uncaught ReferenceError: L is not defined

Jistěže není definován - páč ho o řádek výše zařízla bezpečnostní politika browseru. Bohužel nejde jen nahradit za HTTPS, je třeba použít https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js

Fonty a CSS lze nahradit prostým přidáním "HTTPS".

**Comment by Piskvor** [comment]
Google Chrome: Verze 50.0.2661.102 m
Firefox: 38.0.5

Už jsem si udělal fork, zkusím na to kouknout. (otagoval bych to, leč tu nemůžu)

**Comment by Piskvor** [comment]
Hmm, tak tohle bude asi problém: https://tile.poloha.net/ NET::ERR_CERT_AUTHORITY_INVALID - to je možná na samostatnou issue...sem? Nebo kam?

**Comment by Piskvor** [comment]
Hm, aha - koukám, že někdo ;) už byl rychlejší.

https://github.com/osmcz/osmcz/pull/127

**Comment by mkyral** [comment]
> Hmm, tak tohle bude asi problém: https://tile.poloha.net/ NET::ERR_CERT_AUTHORITY_INVALID - to je možná na samostatnou issue...sem? Nebo kam?

@pedro042 Máš čas a znalosti to opravit? 

> Hm, aha - koukám, že někdo ;) už byl rychlejší.
> 
> #127

Mám to mergnout? Ale na prod to stejně nedostanu. To až @zbycz

**Comment by Piskvor** [comment]
No, asi jo. Já si to pullnu a zaintegruju do tý svý - ještě jsem tam  našel nějaký další věci. podobného ražení.

**Comment by mkyral** [comment]
ok.

Myslíš třeba api.openstreetmap.cz? To je zase @walley  ;-)

**Comment by Piskvor** [comment]
Jo, to taky:
- api.openstreetmap.cz (fotky)
- map.openstreetmap.cz (rozcestníky)
- tile.poloha.net (GeoJSON tiles pro aktivní POI :( )
- osm.fit.vutbr.cz (OsmHiCheck)

Všechno to buď nemá HTTPS vůbec (lepší varianta), nebo tam má certifikát na jinou doménu.

**Comment by Piskvor** [comment]
No a ještě je otázka, jak řešit tu zkrácenou doménu (osmap.cz) - tam dostanu SHA-1 cert a navíc pro něco úplně jiného.

**Comment by Piskvor** [comment]
A jestli tu #127 budeš mergovat, můžeš mrknout i na #130 a #131 ? Takto za sebou by to mělo být zcela nekonfliktní.

**Comment by mkyral** [comment]
Ok. Mrknu na to. Ten link na školení je myslím problém jen verze v gitu, kde je jen kostra redakčního systému aby bylo kde vyvíjet.

**Comment by mkyral** [comment]
Tak jsem to zmergoval a teď bych potřeboval poradit, jak vysvětlit FF, že na openstreetmap.cz nemá lézt přes https, ale přes http. Zmetek mi to teď vždy přepíše na https :-(

**Comment by mkyral** [comment]
A mám pocit, že to u https nějak pokazilo aktivní vrstvu, rozcestníky i chybějící rozcestníky. Minimálně na https://rawgit.com/osmcz/osmcz/master/index.html Možná problém https vs. rawgit. Na localhostu mi to blblo stejně, ale myslel sem, že to je způsobeno špatnou konfigurací lighttpd.

V konzoli vidím hromadu hlášek:
`"[Exception... "<no message>"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js :: .send :: line 5"  data: no]"`
a nevím co to znamená :-(

**Comment by Piskvor** [comment]
Jo, to jsem někde v tomhle vlákně komentoval, že používáme cca 4 domény,
který nemají HTTPS, a tudíž nepojedou. (Než budou mít funkční certifikáty,
asi bych doporučil vypnout ten redirect na HTTPS - nefunkční overlay mi
připadá v tomto konkrétním  případě horší než absence zabezpečení)

**Comment by mkyral** [comment]
@zbycz  Pavle? Co myslíš?

**Comment by Piskvor** [comment]
Ping. Lidi si všímají: https://lists.openstreetmap.org/pipermail/talk-cz/2016-June/014282.html , fakt chceme prezentovat "OSM je prázdná stránka, jděte pryč"? :(((

**Comment by jzvc** [comment]
Je to jeste mnohem horsi ... staci tam vlizt jednou jedinkrat pres https, a zjevne neexistuje (uzivatelsky) zpusob, jak zpatky browser donutit na http.

**Comment by mkyral** [comment]
jo. to jsem už bohužel zjistil a recept na návrat zpátky nemám. Ale to je o nastavení na serveru. To by mohl @zbycz změnit. Akorát se teď asi věnoval něčemu jinému.

**Comment by mkyral** [comment]
Tak to vynucené https přesměrování způsobí, že přímé linky na objekty ( například: http://openstreetmap.cz/node/1601416132 ) selžou s chybou:

```
Smyčka při přesměrování

Server přesměrovává požadavky na tuto adresu sám na sebe, a to takovým způsobem, který zabraňuje jejich dokončení.

    Tento problém může být způsoben zakázáním nebo odmítnutím cookies.
```

**Comment by zbycz** [comment]
Díky za upozornění mailem, Mariáne, teď se naplno učím na státnice...
U mě v prohlížeči se to neprojevovalo, ale asi jen na homepage. 
Jako provizorní fix jsem nastavil, aby vždy z https přesměroval na http. 

Pomohlo to?

**Comment by Piskvor** [comment]
Super, funguje, díky! (Držím palce)
Dne 9. 6. 2016 13:52 napsal uživatel "Pavel Zbytovský" <
notifications@github.com>:

**Comment by mkyral** [comment]
Tak nevím. Já se teď na openstreetmap.cz vůbec nedostanu. Vždycky skončím na hlášce "Smyčka při přesměrování". A je jedno, jestli to zavolám s http:// nebo https://.

Potřeboval bych zjistit, jak FF přesvědčit, aby zapomněl na https.
Nebo, nedá se to přesměrování úplně vypnout? Nebo alespoň nastavit limit na maximální počet přesměrování? Bohužel té problematice okolo https moc nerozumím :-(

**Comment by mcepl** [comment]
Hmm. https://openstreetmap.cz skončí s

```
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by mkyral** [comment]
No to je o tom. že prohlížeč si http přesměruje na https, server vrátí, že bylo přesunuto na http, prohlížeč si to iniciativně zase změní na https a tak pořád dokola :-(

**Comment by zbycz** [comment]
Mám pocit že by to mohlo být keší prohlížeče, zkuste ještě někdo smazat Keš / vyrovnávací paměť / F12+pravý klik na reload tlačítko.

Ale moc nechápu proč se toho váš prohlížeč drží.. A co s případnými dalšími návštěvníky..

**Comment by mkyral** [comment]
Zmetek si někde něco uloží a pak se toho drží. Pokud se nepletu, tak je to brano jako vlastnost. Nedávno proběhla nějaká zpráva, že snad rusové chtěli po Wikipedii, aby pro ně vypnuli https. Odpověď byla, že nechtějí a vlastně to ani není možné vypnout.

Jsem teď jen na mobilu, zítra to vyzkouším.

**Comment by mkyral** [comment]
Tak nakonec mi pomohlo až toto: http://stackoverflow.com/a/34033592

**Comment by Piskvor** [comment]
V Chromu staci Ctrl+Shift+Del a zaskrtat Cookies i Ulozene preference (nebo
jak se to jmenuje), pak to jde.
Dne 10. 6. 2016 6:50 napsal uživatel "Marián Kyral" <
notifications@github.com>:

**Comment by walley** [comment]
prave hodlam prepnout volani rozcestniku na https:)

**Comment by zbycz** [comment]
Tak jsem aplikaci přepnul na https a vyrobil proxy na stejné doméně. Tedy asi jediné funkční řešení, byť výrazně zpomalí načítání dlaždic..

Ovšem začíná mě to trochu štvát - třeba mapillary má vadý certifikát, takže se fotky neukzaujou. https://github.com/mapillary/mapillary_issues/issues/2419 A foto na wikipedii též může zlobit. 

Hlavní důvod proč potřebujeme https je, že Chrome>=50 bez něj neumožňuje geolokaci, což je myslím dost stěžejní funkce. (A hrozí že další browsery se přidaj.) Nadruhou stranu když koukám na ten všechen opruz, možná by šlo udělat nějaký hack ve formě přesměrování na bezpečnou https "locate me" stránku, která by nás přesměrovala pak zas zpět s fixní geolokovanou polohou. 

Uvítám nějaké řešení, nějak mi došel morál s tím bojovat. :)

**Comment by mcepl** [comment]
> Uvítám nějaké řešení, nějak mi došel morál s tím bojovat. :)

Děkuji moc práci, kterou s tím máte všichni.

Bohužel, Firefox furt není šťasten.

http://pbs.twimg.com/profile_images/1798748906/Juhele_100px_normal.png není po HTTPS .. doufám ale, že to by neměl být zas takový problém ... pbs.twimg.com samozřejmě funguje i po HTTPS, takže stačí snad jenom někde přidat jedno `s`.

**Comment by zbycz** [comment]
dík - to jsem už opravil, spolu s přihlášeným uživatelem osm. Snad. Ale tím jak taháme z tolika zdrojů, tak nám tam zase leccos může skočit. Nebo další problém - někde jim přestane platit certifikát a celý náš web je nahraný. Furt bych to https skoro zahodil a vydal se cestou toho geolocate-hacku.

**Comment by mkyral** [comment]
No jo. Ale jak by to mělo fungovat? Evidentně se počítá, že všichni pojedou po https a certifikáty budou mít vždy validní.

**Comment by mcepl** [comment]
> Nebo další problém - někde jim přestane platit certifikát a celý náš web je nahraný.

No, hmm. Řekl bych, že s LetsEncrypt a certifikáty od StartTLS (a někoho dalšího?) tahle varianta už opravdu pozvolna začíná znamenat někoho, kdo není moc svéprávný (nebo příliš tvrdohlavý ... nechci se teď pouštět do teoretické diskuse o bezpečnosti či nebezpečnosti SSL).

Doporučil bych velké štamprle něčeho dobrého a zopakovat každé ráno třikrát za sebou před zrcadlem „Miluji Velkého Bratra^H^H^H^H^HHTTPS“, protože to je podle mého naše budoucnost ať už si o ní myslíme cokoli.

**Comment by jzvc** [comment]
Spis sou nesvepravny vyvojari browseru (vsichni) ...

Nekolik (malo) prikladu - nejde se pripojit k ddwrt, protoze https pouziva "nebezpecne" sifrovani. Novejsi verze neexistuje, primarni funkci HW plni vpohode, duvod pro vymenu presne nula. Http jim prekvapive neva, poslat tak heslo je tedy zjevne OK. Nebo nejde spustit administraci switche ... protoze pouziva java plugin ... atd atd atd.

Kdyby jim pak slo o bezpecnost, tak by implementovali DANE. Cely chovani k certifikatum je naprosto uchylny a s bezpecnosti nema zhola nic spolecnyho. Libovolna CA si muze vydat certifikat pro libovolnej web, a taky se to bezne deje. Browser neumoznuje omezit komu pro kterej web se duveruje.

Jinak vazne nevim, jestli zrovna geolokace z browseru je neco, bez ceho ta mapa nemuze zit. Podle me se to bude rozbijet neustale dokola, protoze kolik, 20? ruznych zdroju proste nikdy nebude fungovat zaroven.

**Comment by mcepl** [comment]
> Spis sou nesvepravny vyvojari browseru (vsichni) ...

To je přesně ta diskuse které jsem se chtěl vyvarovat, protože to nemá cenu. Pokud chcete psát webovou aplikaci pro reálné browsery tak se musíte přizpůsobit realitě, ať si o ní myslíte cokoli.

A geolokace je samozřejmě naprosto zásadní, pokud chcete mít někdy funkční navigaci (alespoň tak jako mají na `osm.org`).

**Comment by severak** [comment]
Já hlasuji rozhodně pro ten geolokační hack. Jak napsal @zbycz výše:

> Nadruhou stranu když koukám na ten všechen opruz, možná by šlo udělat nějaký hack ve formě přesměrování na bezpečnou https "locate me" stránku, která by nás přesměrovala pak zas zpět s fixní geolokovanou polohou. 

Uvědomte si, že HTTPs (zvlášť u třetích stran) se často rozbíjí. Nejde spoléhat na to, že všechny externí poskytovatelé dlaždic budou mít správný certifikát. I třeba Ministerstvo Vnitra má na stránkách [sekci](https://www.zakazky.mvcr.cz/), kde má nějaký pochybný certifikát a musel jsem udělit bezpečnostní výjimku. 

Navíc, k rozbití HTTPs stačí, aby se vybila baterie na základní desce. Počítač se pak probudí v (např.) roce 2004 a všechny certifikáty jsou rázem neplatné. To je příklad ze života.

Domnívám se, že geolokace není tak zásadní funkce. Sám plánuji cesty spíš před cestou - tj. hledám si místa, kde ještě nejsem a geolokace je mi tak většinou k ničemu.

**Comment by Krakonos** [comment]
No, pokud na portálu bude nějaká funkcionalita vyžadující přihlášení, asi by jsi https měl mít, jinak se bezpečnost zařizuje těžko. Navíc https začíná pomalu být standardem všude, i když není potřeba. Očekávám, že postupně víc a víc věcí bude https podporovat a nebo vyžadovat.

Pokud je problém se službami třetích stran, měli bychom je adresovat, resp. přestěhovat obsah pokud možno k nám nebo na nějaké jedno spolehlivé cdn (tak je to skoro se vším javascriptem teď)

Upřímě se mi ale dost příčí tahat mapové dlaždice po https, navíc u dlaždic máme hodně zdrojů, které neumíme nebo nesmíme přesunout. Zase tahat lokaci, vyhledávání atp. nezabezpečeně nemusí být dobré pro soukromí.

Nejsem si ale jistý, jestli umíme udělat dobrý hack na geolokaci. Podle chromia je to přesně něco, co neradi vidí:

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

Navíc by se mi líbilo, kdyby mapa mohla dostávat živé informace když se třeba pohybuji. Také by bylo dobré se zamyslet, jestli si někde nepřihoršíme později.

Když se podívám na mapy.cz, tak taky jsou https.

**Shrnutí**: Pojďme identifikovat problematické zdroje, které nemají spolehlivé https. Když jsem se na to onehdá díval, určitě jsou problém avatary, které můžou přijít odkudkoliv. To je pěkně hloupé, ale můžeme si napsat avatarovou cache, což je docela dobrý nápad i kvůli tomu, že stačí spojení na jeden server. Je tam nějaký facebook a google, ale ti snad problém nedělají, nebo ho řeší rychle.

Samozřejmě musíme zařídit, aby naše zdroje měly platné certifikáty. Když ale máme letsencrypt, tak by to snad nemusel být problém, ne?

Dál už jsou snad jenom mapové podklady. To je kapitola sama o sobě, ale jenom to značí, že musíme vyvolit několik defaultních mapových podkladů pro běžné uživatele, které mají stabilní zdroje. Věřím, že mapbox má spolehlivé podklady, a že u námi generovaných podkladů to umíme zařídit. Dál si myslím, že potřebujeme už jenom letecké snímky. Současnému ČUZK ortofoto nevěřím, že ho v případdě problému někdo opraví (rychle). Nevíme, jak je na tom mapbox s ortofoto?

Ostatní podklady, které nejspíš běžné uživatele nebudou zajímat, můžeme schovat někam do pokročilých a nefrustrovat běžného uživatele s nějakým nefunkčním certifikátem. Také asi nebude problém detekovat funkčnost podkladu a vedle něj dát ikonku, která na to bude upozorňovat. Teda čekal bych, že to půjde :-)

Sorry za elaborát :-)

**Comment by mcepl** [comment]
Hmm, zajímavé, s "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" (oficiální RHEL-7.3 balíček od Red Hatu). https://github.com/osmcz/osmcz/issues/139

**Comment by zbycz** [comment]
Situace se ustálila, několik zdrojů za tu dobu přeplo na https (https://github.com/osmcz/osmcz/commit/13c142e5246419655204482a29daaa02f58ac0d4) a ty ostatní taháme přes proxy. Sice to není ideál, ale funkční to je - necháváme tedy https zapnuté a doufáme v lepší zítřky :-)
