### ISSUE TITLE
Turistická mapa

### ISSUE THREAD

**Issue by pschonmann** [osmcz/osmcz#13]
Češi jsou vášnivý turisté, určitě by se hodila mapa kde budou zakreslené KCT trasy. Zvyraznene rozcestniky, vrstevnice ( hillshading ), planovani tras ( openroute service, graphhoper)

**Comment by zbycz** [comment]
Máš na mysli nějaký konkrétní server, jehož dlaždice by bylo možné využít?

Napadá mě že by možná šlo použít jen overlay - tj. tak jak to je na old.openstreetmap.cz ([viz](http://map.openstreetmap.cz/kct_tiles/12/2241/1394.png))... @walley jak tyhle dlaždice generuješ? 

Co se týče rozcestníků a routování - na to jsou jiná issuečka. Zde bych se věnoval zejména dlaždicím. Ok?

**Comment by pschonmann** [comment]
Co tohle TMS ?
http://tile.waymarkedtrails.org/hiking/{zoom}/{x}/{y}.png

http://hiking.waymarkedtrails.org/cs/

**Comment by pschonmann** [comment]
Jen je teda ošklivé že třeba žlutá trasa je modrá routa a na ní žlutá značka. Kdyby trasa byla žlutá je to fajn.

**Comment by walley** [comment]
ten muj turisticky overlay je v Maperitive, stahnu si vsechny trasy, nacpu do Maperitive a vygeneruju tileset.
Nicmene ten program je mrtvy a data sou uz stejne prilis velka a funguje to jen na widlich, takze sem v podstate skoncil.

Nicmene overlay turistickych tras rozhodne potrebujeme. 

Chtelo by to nejaky image pro vmware s hotovou instalaci mapniku a nastavenym rendrovanim, pustil bych to nekde na rychle masine a pak akorat nacpal data na internet...

**Comment by Krakonos** [comment]
Waymarked trails umí renderovat i jinou barvou, nepřišel jsem ale na to, podle kterého klíče to tak je :-). Update mají hodně rychlý.

Už jenom proto, že se teď mapuje hodně turistických tras, byl bych raději za něco, co se umí aktualizovat, takže pro vmware image, který se pustí jednou do roka (měsíce) není zrovna dobré řešení.

**Comment by walley** [comment]
masina kteera by to on demand rendrovala by musela byt pravdepodobne rychlejsi nez vps co tu ted mame.

vmware by byl  pustene porad, stejne sem to jeste nikde nevidel, nejake pokusy kdysi byly ale porad je to spis diy.

**Comment by zbycz** [comment]
Pro ČR to asi utáhne i velmi slabá VPS.. Navíc dalo by se to pouštět v noci, čili nikoliv úplně on-the-fly.

openstreetmap.cz mi běží na Standard od http://virt.io - ale mám tam i klientské věci, tak tam nechci instalovat mapnik render :-)

Jinak testoval jsem klasický mapnik pro celé čr (což je mnohonásobně horší než jen trasy) a docela dobře to utáhla free VPSka od Amazonu. Jedna dlažidce se renderovala zhruba vteřinu. Je tam free 512 MB ram a 30GB disku.

**Comment by mkyral** [comment]
@walley A co toto? http://wiki.openstreetmap.org/wiki/Virtual_machine_image

**Comment by mkyral** [comment]
Jinak dočasně (jsou tam teď obrovské rozcestníky) by se daly použít Petrovy dlaždice:

_Samotné turistické trasy jsou na http://tile.poloha.net/kct/{z}/{x}/{y}.png_
Viz: http://www.poloha.net/content/co-je-co-tu-je

**Comment by mkyral** [comment]
@zbycz jedna dlaždice za vteřinu plus x zoomů, každý různě dlaždic = moc sekund ne?
Co vím, tak Petr s tím měl docela problémy - hlavně s vytěžováním disků na té VPS ( a zpomalení ostatních) 

I když, Petr tam toho má více a nevím přesně, co problémy způsobovalo.

**Comment by tkas** [comment]
Podle mne aktualne vyreseno. Zaviram.
