### ISSUE TITLE
Rozcestníky: jiná ikona pro tabule naučných stezek

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#132]
Momentálně mají všechny fotky stejnou ikonu. Ovšem díky tagům je možné odlišit rozcestníky (#rozcestnik) od cedule naučné stezky (#infotabule). Naučné stezky by pak vypadaly mnohem lépe. A uživatele by to třeba motivovalo k doplnění chybějících tagů.

Technicky to není problém, ale potřeboval bych nějakou ikonku. Ideálně vizuálně stejnou jako rozcestník. A to nakreslit nezvládnu :-(

@walley Jak vznikla ikonka rozcestníků? Bylo by možné dokreslit další? Představoval bych si ji nějak takto ;-)

```
----------
|        |
|        |
----------
|        |
```

**Comment by walley** [comment]
vznikla tak, ze sem ji nakreslil.
Tabuli nakreslit by nemusel byt zadny problem. Mimochodem nakreslena byla stejne jako ten tvuj asciiart , akorat pomoci pixlu v gimpu:)

(plus ten stin, to je gimp efekt)

**Comment by mkyral** [comment]
Hmm. Nejsem moc velký umělec. Co třeba takhle?
![infopane](https://cloud.githubusercontent.com/assets/155542/15833631/fed855e2-2c27-11e6-96b1-cbfd44aab8be.png)

Akorát na ten zkosený stín jsem zatím nepřišel. Kdysi jsem to určitě uměl, ale dlouho jsem to nepotřeboval.

Edit: http://gimp.pixtuts.com/gimp-tutorials/effects/realistic-shadow

**Comment by walley** [comment]
super
