### ISSUE TITLE
Nelze přepínat vrstvy mapy v mobilním Firefoxu

### ISSUE THREAD

**Issue by mormegil-cz** [osmcz/osmcz#138]
Vop hlásil na mailing listu problém:

> na mobilním prohlížeči Firefox (Chrome to nedělá) mi nereaguje přepínání vrstev mapy OpenStreetMap.cz - resp. nereaguje na žádnou volbu v celé liště voleb (tedy i zapínání overlay vrstev). Pokud prohlížeči vnutím mód zobrazení pro desktop, pak přepínání funguje (a mohu takto tedy nouzově přepínat, protože při návratu do zobrazení pro mobily si to aktuální přepnutí z desktopu pamatuje).

Dělá mi to totéž, letmým pohledem do ladicí konzole se mi zdá, že by to mohlo být https://github.com/Leaflet/Leaflet/issues/3724 (v konzoli je stejný TypeError), kterýžto byl opraven ve v1.0.0-rc.1, momentálně má leaflet v1.0.0-rc.3, tedy v zásadě žádná ostrá verze s opravou, chápu-li to dobře.

**Comment by mkyral** [comment]
Díky za investigaci. Vývoj Leaflet moc to nesleduji, jen vím, že verze 1.0 je na cestě. Ale i tak bude potřeba nějaké testování aby se zjistilo, co všechno se v 1.0 změnilo a teď nefunguje :-D

Přinejhorším můžeme opatchovat verzi 0.7 a linkovat tu.

**Comment by walley** [comment]
muzem zkusit prepnout na 1.0.0 (a zavcasu zjistit co vsechno prestane fungovat:)
nebo pockat na 0.7.8 pokud ji nekdo udela
stejne z cdn tahame jakousi ultrastarou verzi

**Comment by mkyral** [comment]
No zkusit to můžem, akorát, že já se k tomu teď cca dva týdny určitě nedostanu a i pak to je ve hvězdách :-(

**Comment by walley** [comment]
ja si s tim asi pohraju u sebe, nebot markerclustercosik ma nejspis v nove verzi chunkloader a dokaze loadovat mnohem vetsi mnozstvi dat nez mame u nas neuveritelne rychle a to bychom potrebovali.

taky by me zajimalo jestli to ff rozbil kvuli oprave nejake chyby, nebo to je chyba ff.

**Comment by walley** [comment]
http://map.openstreetmap.cz/work2

uz mi to zobrazuje mapu na leaflet 1.0.0 rc3 a adekvatne novy merkerclustercosik

zkusim zjistit co ruzne nepude a budu to reportovat sem nebot cilem je odstranit tu ff chybu i kdyz to v procesu cely predelame:)

**Comment by walley** [comment]
glenrobertson/leaflet-tilelayer-geojson#27 na tomhle zavisi aktivni vrstva

**Comment by mormegil-cz** [comment]
Hlásím, že přepínání vrstev mi na work2 v mobilním FF funguje.

**Comment by mkyral** [comment]
Vyřešeno aktualizací leaflet knihovny. Je možno vyzkoušet v [Demu](http://rawgit.com/osmcz/osmcz/master/index.html).
