### ISSUE TITLE
S Firefoxem nemohu najít aktuální souřadnice

### ISSUE THREAD

**Issue by mcepl** [osmcz/osmcz#139]
Když se pokusím najít svoji současnou polohu dostanu v konzoli tuto chybovou hlášku:

```
00:01:05.148 Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to
load this URL, add all domains and subdomains of your app to the App Domains field in your
app settings.1 ping:1:51
```

Používám Firefox 45.3.0 (Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0), z balíčků Red Hatu pro RHEL 7.3 (`firefox-45.3.0-1.el7_2.x86_64`).

**Comment by zbycz** [comment]
Je to ještě aktuální? Pokud ano, prosím o znovu otevření. Dík!

**Comment by Piskvor** [comment]
V aktuálním FF funguje.
