### ISSUE TITLE
hledani prez nominatim

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#14]
prenest ze starych map
vymyslet nejake pekne ui

**Comment by walley** [comment]
https://github.com/stefanocudini/leaflet-search

**Comment by zbycz** [comment]
Ten se mi moc nelíbí, ale je snadné ho přidat a pak iterovat nad vylepšením
:-)​

**Comment by walley** [comment]
zakladni hledani je primitivni, co je relativne slozite je vytvorit nejaky pekny seznam vysledku.

nicmene tenhle ma vyreseny autocomplete

**Comment by zbycz** [comment]
Jj, přidám ho během večera.​

**Comment by zbycz** [comment]
Duplikát #2 - zavírám.
