### ISSUE TITLE
Opensnowmap - změna politiky poskytování dlaždic

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#140]
http://blog.opensnowmap.org/post/2016/08/23/Opensnowmap-Tile-Usage-Policy

**Comment by zbycz** [comment]
Díky za info.

Napadá mě k tomu taková obecná úvaha - rád bych aby na osmcz bylo více užitečných mapových vrstev, aby BFU návštěvník viděl sílu a užitečnost dat - celosvětově. O vrstvu míň je zase o krok zpátky :)  .. a řešení asi není snadné - designovat pěknou vrstvu je mega těžké a provozovat tileserver pro celý svět zas mega drahé.

**Comment by mkyral** [comment]
Tak jestli jsem to dobře pochopil, pro zobrazení zimních sportů stačí přidat http referer.  Co přestane fungovat bude reliéf a vrstevnice. To můžeme tahat odjinud.

Plus přijde mi zvláštní mít na zimní mapě zelené louky. Chtělo by to vyladit do bíla ;-)

**Comment by zbycz** [comment]
Aha, no tak to je dobré. Já jsem si nepřečetl to "relief" a vypadalo to že tedy v listopadu konec. Přidat referrer bude v pohodě.

**Comment by yvecai** [comment]
I'm not really versed in Czech, but I think I know what you are discussing here.
Please note that the Hillshade Geotiff (~150 GB)and contour lines shapefiles (~500GB) from Opensnowmap are available for download if you want to make your own relief layer. Of course it would be way smaller if you only cutout Czech Republic.
Contact me in private for download links.
Yves - webmaster at opensnowmap.org

**Comment by mkyral** [comment]
@zbycz - tak už je to tady, už to nefunguje
@yvecai - thanks for your offer. I'll work on it later this winter ;-)

**Comment by mkyral** [comment]
Asi vyřešeno, na speciální zimní podklad bych udělal separátní issue.
