### ISSUE TITLE
Aktivní vrstva: přidat možnost aktualizovat fotku rozcestníku

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#141]
Ideálně stejný formulář jako pro nahrávání chybějících rozcestníků.

**Comment by walley** [comment]
slovo aktualizace je trosku zavadejici
pokud je stavajici fotka spatna ve smyslu kvality, pak se smaze a nahraje nova, jinak se pouze nahraje nova a stara tam zustane. 

aktualnost se asi bude muset resit datumem, takze pokud udelate formular, dodelam moznost ziskani data fotky aby to cele vubec slo udelat.

**Comment by mkyral** [comment]
Tak aktualizace v tom smyslu, že se začne přednostně zobrazovat ta nová fotka. Stará by mohla dostat nějaký tag "zastaralé" nebo "nekvalitní". Tyhle fotky by byly normálně schovány a objevily by se pouze po kliknutí na odkaz "zobrazit vše".

Ale jestli půjde mazat, tak proč ne.

**Comment by tkas** [comment]
S Fody se resi zakazanim starsich fotek, casem bude i nejak "polo" automaticky. Zaviram.
