### ISSUE TITLE
Hledání, úzké pole

### ISSUE THREAD

**Issue by pschonmann** [osmcz/osmcz#143]
Vyhledávací pole je hrozně uzke, neni videt co tam píšu.
![hledat](https://cloud.githubusercontent.com/assets/6333844/19574306/f313f2a0-9709-11e6-825d-53b256dd24ff.png)

**Comment by mkyral** [comment]
Hezkýýýýý. Tohle je novinka. Asi to někdo rozbil.

**Comment by pschonmann** [comment]
Mám pocit že se to stalo s posledním releasem rozcestníků

Dne pá 21. 10. 2016 9:16 uživatel Marián Kyral notifications@github.com
napsal:

**Comment by mkyral** [comment]
Tak vrátil jsem to zpátky. Něco už je vidět, ale pořád to není optimální.
