### ISSUE TITLE
Aktualizace js knihoven

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#145]
Jsou dostupné nové verze knihoven:
- [x] Leaflet 1.0.1 http://leafletjs.com/download.html
- [x] Opening hours

**Comment by walley** [comment]
uz sme vyresili upgrade na leaflet 1?

**Comment by mkyral** [comment]
Ne. To je právě potřeba vyřešit a otestovat. Jediné co vím, tak že jsi to nasadil někam na map2.openstreetmap.cz, ale v gitu to není, takže to nelze jednoduše opravovat a testovat.

Až se k tomu dostanu, tak udělám novou větev v gitu a zkusím to otestovat.

**Comment by walley** [comment]
jen sem zkousel co prestane fungovat a jedine co prestalo je ten geojson laywr co pouzivate v aktivn vrstv. jinak sou zmeny trivialni

**Comment by mkyral** [comment]
OK. To už je snad opraveno. Vyzkouším.

BTW: co s těmi  fotkami rozcestníků? Vypadá to, jako by došlo místo. Lidi na konferenci jsou netrpěliví a já s tím nic dělat nemůžu :-(

**Comment by walley** [comment]
uz sem naky musto uvolnil. musi se koupit novy. taky musim smazat ty fotky z commons. quota u wedos disk funguje divne ma to naky zpozdeni nez to zaregistruje volny msto.

**Comment by walley** [comment]
jak sme na tom s pripravenosti na update na leaflet 1.0?

**Comment by mkyral** [comment]
Blbě. Ten plugin stále není aktualizován (a asi hned tak nebude). Chtěl jsem zjistit, kde je problém, abych to mohl opravit, ale zatím jsem pohořel. Javascript není mé hobby :-(

**Comment by mkyral** [comment]
Tak jsem zatím vyhrabal jen toto:

_TileLayer has been heavily refactored, so there's no exact corresponding method in 1.0. You might want to look at GridLayer's ```_update```, ```_addTile``` and ```_wrapCoords```, which have parts of the same logic, from a quick look at things._

-- https://github.com/Leaflet/Leaflet/issues/5103

**Comment by mkyral** [comment]
Inkriminovaná funkce, prosté zakomentování jejího volání nepomohlo 

```js
	_adjustTilePoint: function (tilePoint) {

		var limit = this._getWrapTileNum();

		// wrap tile coordinates
		if (!this.options.continuousWorld && !this.options.noWrap) {
			tilePoint.x = ((tilePoint.x % limit.x) + limit.x) % limit.x;
		}
		if (this.options.tms) {
			tilePoint.y = limit.y - tilePoint.y - 1;
		}

		tilePoint.z = this._getZoomForUrl();
	},
```

**Comment by mkyral** [comment]
Tak co jsem na to koukal, bude potřeba kompletní přepis :-(

**Comment by walley** [comment]
na to samy sem prisel taky

map2 uz asi nefunguje, ale byly to trivialni zmeny, jestli to jeste nandu hodim sem diff.

**Comment by mkyral** [comment]
Chlape neštvi. Ty to opravíš a necháš si to pro sebe? :-D

**Comment by walley** [comment]
ono to asi nekam zmizlo, nebo se to prepsalo, ale bylo to vazne jednoduchy. 

dokud nekdo neprepise ten geojson layer tak to ani nema cenu resit.

**Comment by mkyral** [comment]
Vyřešeno, vypadá to, že to funguje.
