### ISSUE TITLE
Nejbližší foto - není vidět.

### ISSUE THREAD

**Issue by pschonmann** [osmcz/osmcz#146]
Fotka při kliknutí na poi - Nejbližší foto není vidět.

![osmap](https://cloud.githubusercontent.com/assets/6333844/21799160/68dd5668-d718-11e6-8e5c-e6e91c6716af.jpg)

**Comment by mkyral** [comment]
Zase rozbité https.

Požadavek https://images.mapillary.com/1N4esS19Z9u47FI9u8RE3g/thumb-320.jpg
vrací:
```
images.mapillary.com uses an invalid security certificate. 
The certificate is only valid for the following names: cloudfront.net, *.cloudfront.net 
Error code: SSL_ERROR_BAD_CERT_DOMAIN 
```

**Comment by zbycz** [comment]
Už jsem to chtěl půl roku nahlásit a teď před týdnem jsem se k tomu dokopal :-D
viz https://github.com/mapillary/mapillary_issues/issues/2419
Bohužel kašlou na nás. Commitnul jsem tedy do masteru fakehttps.

btw, teď jak jsem opravoval ty nefunkční https zdroje v layers, tak mi přijde docela zvláštní, že nikomu to od června nevadilo.. Asi to moc lidí nepoužívá, just sayin :)
