### ISSUE TITLE
Sekce "Konference" se neaktualizuje

### ISSUE THREAD

**Issue by xkomczax** [osmcz/osmcz#147]
Na hlavní stránce openstreetmap.cz se sekce "Konference" neaktualizuje, ukazuje (k dnešnímu dni) osm dní staré příspěvky, přestože se v mailing listu intenzivně diskutuje

**Comment by zbycz** [comment]
Teď jsem to načetl manuálně, a je to ok. Takže nám na nové VPSce chybí cron.. prosím @tkas o opravu.

**Comment by tkas** [comment]
Problem po zmene VPSky a prenastaveni certifikatu. Upraveno doplnenim CA do instalace VPS.
