### ISSUE TITLE
Přihlášení redirectuje na escapovanou URL

### ISSUE THREAD

**Issue by Piskvor** [osmcz/osmcz#148]
Firefox 50.1.0 a Chrome 55.0.2883.87 (64-bit), Ubuntu Linux

1. smažu cookies
2. otevřu openstreetmap.cz
3. přihlásím se přes OSM.org
4. po přihlášení se browser pokusí redirectovat na https://openstreetmap.cz%2f/ - to vypadá, že se moc escapuje lomítko
5. pokud naklepu adresu openstreetmap.cz ručně, jsem už přihlášen

**Comment by zbycz** [comment]
U mě na Win/Chrome 55 (64bit) ok, zvláštní, čím to může být?

**Comment by Piskvor** [comment]
Už to vidím:

`<a href="http://openstreetmap.cz/oauth/login/?backUrl=%2F">Přihlásit přes OSM.org</a>`

`http://openstreetmap.cz/oauth/login/?backUrl=%2F` -> **301 redirect**
`https://openstreetmap.cz/oauth/login/?backUrl=%252F` -> 302 redirect
`https://www.openstreetmap.org/oauth/authorize?oauth_token=...`

**Comment by zbycz** [comment]
Hezký objev!! Opravím :-)

**Comment by zbycz** [comment]
Myslím že opraveno - testoval jsem a neprojevuje se. Kdyžtak prosím otevřít.

**Comment by severak** [comment]
mě to nově taky funguje
