### ISSUE TITLE
OSM v CZ médiích

### ISSUE THREAD

**Issue by pschonmann** [osmcz/osmcz#149]
Ahoj, mohlo by na českém portále vziknout okenko kam by mohl prihlaseny uzivatel pridavat zminky o OSM na ceskych mediich ? Pak by na stránce mohl vznikat seznam odkazů. Napadlo me to v souvislosti s http://zpravy.e15.cz/domaci/udalosti/cesi-zacali-mapovat-zapomenuta-mista-planety-zvladne-to-i-babicka-1327999
Jako propagace dobrý.

**Comment by zbycz** [comment]
Dobrý postřeh, je na to už delší dobu k dispozici stránka https://openstreetmap.cz/press
Ale zatím není zařazena do struktury a chce ji to nějak zkrášlit :-)

Přidal jsem ti k té stránce práva, prosím poedituj :-)  (možná to bude chtít odhlásit přihlásit, nevím).

**Comment by pschonmann** [comment]
Při odhlášení z webu ... jen tak mimochodem
Smyčka při přesměrování

Server přesměrovává požadavky na tuto adresu sám na sebe, a to takovým způsobem, který zabraňuje jejich dokončení.

    Tento problém může být způsoben zakázáním nebo odmítnutím cookies.

**Comment by zbycz** [comment]
dík. Vím o tom, je to tím zatroleným https. Mělo by to být opraveno v dalším releasu -- aka https://github.com/osmcz/osmcz/projects/1

**Comment by zbycz** [comment]
Obojí opraveno v pondělí 
(viz https://openstreetmap.cz/talkcz/c2355 )
