### ISSUE TITLE
chunkProgress

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#151]
prozkoumat a aktivovat chunkProgress v markerClusterGroup

**Comment by walley** [comment]
chunkloading seems to work:)

**Comment by mkyral** [comment]
Pěkné. Možná to je přesně to, co je potřeba pro to, aby aktivní vrstva nepůsobila zamrzání prohlížeče.

**Comment by zbycz** [comment]
Myslím že aktivní vrstvu by šlo napsat dobře - akorát ten 1 den práce nějak nemůžu vyšetřit. Chunkování/clusterování podle mě není řešení - resp. pak to je menší UX použitelnost...

**Comment by walley** [comment]
v tom markerclusteru to je jen konfiguracni volba, dokonce ani neni poznat jestli to je lepsi. 
spis mi prijde leaflet 1 obecne rychlejsi.

umi to ovsem progresbar, kdyz se to loadovani protahne, v examplech to zacne kreslit az kdyz je nacitani delsi nez sekundu.

**Comment by mkyral** [comment]
> Myslím že aktivní vrstvu by šlo napsat dobře - akorát ten 1 den práce nějak nemůžu vyšetřit. 

A jak by to tak cca mělo fungovat?


> Chunkování/clusterování podle mě není řešení - resp. pak to je menší UX použitelnost...

Tak pokud u načítání nebude zamrzat prohlížeč, tak to bude významný pokrok.

**Comment by zbycz** [comment]
1) no, napsat to správně - tj. držet si reference jen jednou a po dlaždících. Nepřekreslovat to všechno, ale jen co je potřeba = minimalizovat počet DOM operací a použít CSS transform. Případně použít nějaký quadtile algoritmus. Prostě napsat to from-scratch přímo pro naše použití. JS je na to výkonný dost, aby to fungovalo.

2) možná by v mezičase šlo aplikovat hack - když je více než X bodů, zobraz jen X náhodných. To by měl být one-liner. Můžu zkusit..

(možná bychom tuhle diskusi měli přesunout do #100, přesuň případně svůj comment a přesunu svůj)

**Comment by mkyral** [comment]
Co si tak vybavuji, tak největší problém je zapnutí/vypnutí a pak změna zoomu. Tam stejně musíš všechny zahodit a načíst znova, protože na různých zoomech se posílají různá data. Posouvání po mapě v rámci jednoho zoomu už takový problém není.

**Comment by walley** [comment]
zaviram, je to davno zaple, bar se nezobrazuje, ale to je na novou issue
