### ISSUE TITLE
Brát v potaz guidepost:ref nebo ref:guidepost

### ISSUE THREAD

**Issue by stoupa-cz** [osmcz/osmcz#155]
Pokud je bod rozcestníku zároveň např. strom nebo sloup elektrického vedení, specifikuje se referenční číslo rozcestníku atributem "guidepost:ref". V tomto případě ale aplikace říká, že daný rozcestník nemá referenční číslo, např.: https://openstreetmap.cz/node/2615622726#map=20/49.15914/16.26377&layers=kGB

Proto také nedojde ke spárování s fotkou.

Je možné, že mám špatně tagování - to mě případně opravte a přetaguji.

**Comment by tkas** [comment]
Doplnim do OsmHiCheck.

Aktualne platny priklad je https://openstreetmap.cz/node/2669348452
taginfo: https://taginfo.openstreetmap.cz/keys/ref%3Aguidepost

ref:guidepost je si vyrazne lepsi varianta, jediny vyskyt guidepost:ref opraven (HB209)

**Comment by tkas** [comment]
https://openstreetmap.cz/#map=20/49.46050/16.27104&layers=kGB - OK
https://openstreetmap.cz/node/2848101160#map=20/49.47380/16.24493&layers=kGB - OK
https://openstreetmap.cz/node/2894389192#map=20/49.65989/15.85533&layers=kGB - OK

Zda se, ze to funguje jak ma. Zaviram.
