### ISSUE TITLE
Tisk - css - ovladaci prvky

### ISSUE THREAD

**Issue by jzvc** [osmcz/osmcz#156]
Pokud se pokusim z openstreetmap.cz tisknout, tak se do toho vlozi i ovladaci prvky (vyhledavani a dalsi) a to vcetne selectoru vrstev, pokud je otevrenej, je tam celej seznam. Pokud je zavrenej tak jen ta ikona ale i to pusobi rusive.

Chtelo by to stylopis pro tisk kterej tyhle prvky odstrani.

**Comment by mkyral** [comment]
Tak snad už to je lepší. Možná by se to dalo ještě trochu vylepšit.
