### ISSUE TITLE
Přepínač vrstev nefunguje pokud je otevřen splash

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#159]
> Ahoj,
> pro BFU je trochu matoucí, že šipka, která ho svádí k použití přepínače mapových vrstev nefunguje, dokud křížkem nezavře to okno uprostřed.
> Chvíli mi trvalo, než jsem na to přišel. Možná by by otevření přepínačevrstev mělo to okno zavřít, tj. "fungovat" ;-)
> Martin M.

Via @talk-cz

Navýšit z-index + zavřít splash a pomocnou šipku.

**Comment by mkyral** [comment]
Se to kapku ukázalo nad mé možnosti. Posunování z-index nikam nevedlo.

**Comment by mkyral** [comment]
Tak jsem nad tím přemýšlel a asi bych se na z-index vybodl. Hlavní problém je, že je ten obrázek mnohem větší než v něm obsažená šipka a neviditelně pak překrývá tlačítko. Myslím, že když se svg ořeže a následně trochu posune, aby byla šipka umístěna správně, tak přestane překrývat tlačítko, které začně fungovat ;-)

**Comment by zbycz** [comment]
Fixnul jsem komplet chování splashe a přidal tlačítko na zobrazení skrytého. 
viz DEMO - nebo též jsem to pro jistotu pushnul na http://devosm.zby.cz/
