### ISSUE TITLE
osm-notes - TypeError: map is null

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#165]
Při posunování mapy se mi začalo stávat, že mi posun zamrzne. Zbytek aplikace funguje normálně (menu, tlačítka), ale mapou nejde posouvat. Dle všeho to má na svědomí vrstva poznámek.

Mám pocit, že to nastane, pokud je vrstva zapnutá a já ji vypnu. Následně pak při posouvání dojde k zamrznutí a pomůže až refresh.

![obrazek](https://cloud.githubusercontent.com/assets/155542/24847749/3de52dea-1dc3-11e7-8181-13a524f70b29.png)

**Comment by mkyral** [comment]
onAdd()
```js
        map
            .on('viewreset', this._load, this)
            .on('moveend', this._load, this);
```

Nevidím  onRemove() a tam map.off ;-)

**Comment by zbycz** [comment]
Opraveno. Dík za výborný bug-report včetně příčiny - kdyby tak takhle byly všechny :-)
