### ISSUE TITLE
Využití oauth v javascriptu

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#166]
Jestli jsem to dobře pochopil, tak aktuálně probíhá přihlašování uživatele v php na serveru, přihlášení se drží v phpsession a v javascriptu nemám jak zjistit, zda je uživatel přihlášený, jaké má uživatelské jméno a už vůbec ne token, kterým by se pak aplikace mohla identifikovat dalším službám: zakládání osm notes a v api pro nahrávání fotek.

@zbycz - je možné toto nějak propagovat ze serveru do aplikace, abych si to mohl pak načíst a zpracovat v javascriptu? A pokud ne token, tak alespoň nějakou informaci, že uživatel je přihlášen, jaké má uživatelské jméno a případně i link na jeho profil.

Ideální by bylo použít jedno přihlášení na všechno.

**Comment by zbycz** [comment]
Ano, to jsi pochopil správně. Souhlasím, že JS tohle potřebuje nějak získat.

Bohužel osm.org implementuje pouze oauth-1.0a, tedy navrhuju spíše vytvořit jakousi proxy (to už umíme,ne?), která request podepíše a přepošle na OSM.org.

Inu to není moc práce .. zkusím někdy až se budu vrtat v phpku. Kdyžtak se tu prosím připomeň :-)

**Comment by mkyral** [comment]
Proxy ok, ale js by alespoň měl vědět, že je uživatel přihlášen.

**Comment by zbycz** [comment]
Jo, to jistě - taky to tam tam přidám - i jméno usera .. vždyť už teď by to šlo vytáhnout přes JS selector jestli je vpravo nahoře obrázek nebo ne :D

**Comment by mkyral** [comment]
No jo. Akorát, že v DEMU mám vpravo nahoře prd. To bude chtít nějak upravit index.html. Aby třeba načetl nějaký můj konfigurační soubor a nastavil mi tam ty údaje.

**Comment by zbycz** [comment]
To je zbytečné hackování. Prostě normálně to vyplivnu v @layout.latte do
osmcz.user = {id: 123, username: "zby-cz", ...}  a nepřihlašený bude mít
osmcz.user=false;

Mám tam dát všechno co víme? Vzhledem k tomu že to jsou "jeho data"
přihlášeného uživatele - tak to asi není privacy problém. Ale chtělo by to
promyslet.
```
id username webpages email contact fullname twitter github places tags
projects public account_created img changesets traces description home_lat
home_lon talk_cz_mails first_login last_login oauth
```

**Comment by zbycz** [comment]
To je zbytečné hackování. Prostě normálně to vyplivnu v @layout.latte do
`osmcz.user = {id: 123, username: "zby-cz", ...}`  a nepřihlašený bude mít
`osmcz.user=false;`. Můžeš si to už nafejkovat do index.html někam nakonec.

Mám tam dát všechno co víme? Vzhledem k tomu že to jsou "jeho data"
přihlášeného uživatele - tak to asi není privacy problém. Ale chtělo by to
promyslet.
```
id username webpages email contact fullname twitter github places tags
projects public account_created img changesets traces description home_lat
home_lon talk_cz_mails first_login last_login oauth
```

**Comment by mkyral** [comment]
Jenže při lokálním vývoji žádné latte nemám. A cpát každou změnu na devosm a bít se s ostatními nemám zájem ;-)

Přidej to do latte, já si pak už nějak upravím index.html ať se mi lépe vyvíjí.

**Comment by walley** [comment]
me staci nejakej jednoznacnej identifikator, nepotrebuju nikam nikoho prihlasovat, jen kdyz bude identifikator, tak se veci stanou hned. a v logu bude napsano, kdo to udelal

**Comment by zbycz** [comment]
Hotovo. Stačí nyní přistupovat k `osmcz.user` - buď tam je objekt nebo `false`. Pro vývoj si to můžete simulovat v osmcz.js.

**Comment by mkyral** [comment]
Díky. Ale teď na to není moc času :-(

BTW: mohl bys nasadit ten nový formulář na nahrávání fotek na produkci?

**Comment by zbycz** [comment]
Úplně rozumím, taky mi to trvalo.  
ad btw) nasazena aktuální verze
