### ISSUE TITLE
účel openstreetmap.cz?

### ISSUE THREAD

**Issue by nesnera** [osmcz/osmcz#167]
Natrefil jsem na článek z 2016 o [funkcích Mapy.cz](http://www.zive.cz/clanky/12-tipu-pro-mapycz-pouzivejte-je-jako-profik/sc-3-a-184694/default.aspx#part=1), čímž jsem si uvědomil svou nejistotu v tom, má-li být openstreetmap.cz využívána i běžnými uživateli, nebo je záležitostí čistě maperskou. (Platí-li "B" jsou inspirace z článku mimo mísu.)
Rozhodně bych to rád viděl někde jasně formulováno   ;?

**Comment by tkas** [comment]
Ahoj,

obecne je to urcite zamysleno i pro nemappery, ale vyvijeji to mapperi a
delaji to tak aby to vyhovovalo jim. Tim padem je to automaticky a logicky
orientovano na ne a i funkce ktere jsou zamysleny pro bezne uzivatele bez
jejich zpetne vazby nemusi byt to co tihle lide hledaji.

Bye


Dne 13. května 2017 11:08 Ladislav Nesnera <notifications@github.com>
napsal(a):

**Comment by mkyral** [comment]
Tak tak. Nápadů jsou mraky - viz seznam otevřených issue.

Akorát není dostatek lidí, kteří by to naprogramovali. Takže se dělá hlavně to, co někoho pálí. Třeba ten nový formulář na nahrávání fotek. Ten starý mi prostě nevyhovoval. A na další mi zatím nezbývá čas.

Idea je taková, že by to byl portál jak pro běžné uživatele, kterým ukáže sílu OSM tak i pro mappery, kteří budou mít k dispozici speciální nástroje. Ale než se tam dostaneme, bude to nějakou dobu trvat. Bohužel s mapy.cz, které mají celé oddělení programátorů, soupeřit nemůžeme.

Co jsem koukal na ty tipy, tak něco už máme (gpx), něco bychom rádi (plánovač, nástroje pro měření trasy), něco je o dostupných zdrojích (rekordy a kuriozity, cena benzínu) a něco mít asi nikdy nebudeme - ptačí pohled.

**Comment by mkyral** [comment]
Nové funkce, případně požadavky na ně jsou vítány, ale ideálně jako samostaná issue.

**Comment by nesnera** [comment]
A nešlo by hodit ten odkaz někde do bufferu? Co když jednou bude tolik zdrojů, že nebudeme roupama vědět, co s nima?.. O:-)
Prostě ať zůstane inspirace pro nudící se vývojáře. Zavřením to jen zmizí v propadlišti dějin :-/

**Comment by mkyral** [comment]
Nic ti nebrání ten odkaz projít a vytvořit pro každou funkcionalitu extra issue. Pro případného vývojáře je to mnohem příjemnější a také se otevírá možnost o každém issue diskutovat a hlasovat pro něj.
