### ISSUE TITLE
Obchvat Třince

### ISSUE THREAD

**Issue by tomasolo** [osmcz/osmcz#169]
Nějakou dobu je již v provozu obchvat Třince, v OSMCZ je stále zatím zakreslen ve výstavbě. Aktuální stav odpovídá tomu na www.mapy.cz

[https://mapy.cz/zakladni?x=18.6787456&y=49.6553365&z=13&l=0](url)

**Comment by mkyral** [comment]
Přimo v OpenStreetMap je to už nějakou dobu změněno.

![obrazek](https://user-images.githubusercontent.com/155542/32836519-5b075896-ca0a-11e7-836e-1bafa59385a7.png)

U jiných vrstev to bohužel vždy nějakou dobu trvá. Doporučuji kontaktovat přímo autora daného podkladu. Link vpravo dole.

Zavírám, netýká se to přímo portálu, na externí mapové podklady a periodicitu jejich aktualizace bohužel nemáme vliv.
