### ISSUE TITLE
Přidat autentifikaci přes osm.org

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#17]
- Zejména kvůli adminu statického webu
- ale do budoucna i třeba pro ukládání vlastních bodů, atd

**Comment by pedro042** [comment]
mám vyřešeno přes https://simplesamlphp.org/ (s nepatrným patchem).

http://poloha.net/simplesaml/module.php/core/authenticate.php?as=osm

pošlu.

**Comment by zbycz** [comment]
Budu rád, když pošleš.

**Comment by mkyral** [comment]
Akorát jak tak na to koukám, chtělo by to trochu poladit. Mám tam 37x "Poloha.net". Ale nejsem si jistý, kde přesně je chyba. Jestli chybějící sušenka nebo chybějící automatické odmazávání neplatných záznamů.

![oauth](https://cloud.githubusercontent.com/assets/155542/12228300/9142e43c-b839-11e5-9a4a-419b0dc1088b.png)

**Comment by mkyral** [comment]
Implementace v js použitá v editoru iD.

https://github.com/osmlab/osm-auth

**Comment by zbycz** [comment]
@mkyral, zvažuju, jestli mi to bude stačit pro autentifikaci backendu. Když dostanu asi by bylo potřeba poladit landing page, abych si první ten token využil na BE, a potom až poslal do FE.

O víkendu na tom budu vyšívat :-)

**Comment by zbycz** [comment]
Hotovo. Ovšem bude to vytvářet token při každém přihlášení stejně jako poloha.net. 

Líp to asi nejde ten osmlab/osm-auth to dělá stejně.

**Comment by mkyral** [comment]
Tak to je ovšem škaredá, nepěkná věc :-(

**Comment by zbycz** [comment]
Tak možná to půjde, možná taky ne. Token-revocation je až ve [standardu OAuth2.0](http://oauthlib.readthedocs.org/en/latest/oauth2/endpoints/revocation.html), ovšem osm.org ho [implementuje](https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/test/controllers/oauth_controller_test.rb) - otázkou je jestli funguje jen v rámci používání osm.org website. Nebo i když to bude podepsané novým uživatelovým oauth access tokenem...

**Comment by vop-cz** [comment]
...a pro nás pro blbý to můžeš přeložit do češtiny?

:o)

---------- Původní zpráva ----------

Od: Marián Kyral notifications@github.com

Komu: osmcz/osmcz osmcz@noreply.github.com

Datum: 20. 1. 2016 7:29:55

Předmět: Re: [osmcz] Přidat autentifikaci přes osm.org (#17)

"

Tak to je ovšem škaredá, nepěkná věc :-(

—

Reply to this email directly or view it on GitHub
(https://github.com/osmcz/osmcz/issues/17#issuecomment-173108533). 

"=

**Comment by mkyral** [comment]
No když se kouknu na tu stránku s příkladem oauth (http://osmlab.github.io/osm-auth/) tak vidím. že jsem i po týdnu stále přihlášen. A je docela možné, že stejné to bude i na osmap.cz.

**Comment by mkyral** [comment]
@vop-cz co konkrétně? Oauth nebo Cimmrmana?

**Comment by vop-cz** [comment]
@mkyral ..."bude to vytvářet token při každém přihlášení stejně jako poloha.net."...

**Comment by mkyral** [comment]
Viz můj obrázek výše devět dní zpět. Schválně, kolikrát tam vidíš Poloha.net?

Pro sebe to najdeš v "Moje nastavení" a pod nadpisem klikneš na "nastavení oauth".

**Comment by mkyral** [comment]
Tak ač jsem na http://osmlab.github.io/osm-auth/ stále přihlášen, openstreetmap.cz se tváří, že mne nezná.

**Comment by zbycz** [comment]
Mezi těmi weby se informace o přihlášení nesdílí. Nebo tím chceš říct, že osmcz tě zapomnělo? Je to dost možný, případně to nastavím líp.

**Comment by mkyral** [comment]
_Nebo tím chceš říct, že osmcz tě zapomnělo?_

Jo přesně to chci říct. osm-auth se ke mně stále hlásí, osmap.cz ne. Což znamená, že se musím znova přihlásit a tím pádem si vyžádat další token.

**Comment by zbycz** [comment]
Ok, napsal jsem si do #54.

**Comment by zbycz** [comment]
Ohledně mazání starých tokenů - poslal jsem dotaz na osm.org website github.

Session se zapomínala, protože server je po hodině mazal. Nyní nastaveno `session.gc_maxlifetime` na měsíc.
