### ISSUE TITLE
nevykreslená turistická trasa

### ISSUE THREAD

**Issue by gorn** [osmcz/osmcz#171]
Na mapě
https://hiking.waymarkedtrails.org/#route?id=6722573&map=14!49.7075!13.8008
vede modrá turistická trasa, ale není rendrována na
https://openstreetmap.cz/#map=15/49.7124/13.7865&layers=kKG

**Comment by tkas** [comment]
Chybna (nedostatecna) data v OSM.

**Comment by gorn** [comment]
Co konkretne je na datech nedostatecneho? Obsahuji vse co je treba. Viz 
https://wiki.openstreetmap.org/wiki/Walking_Routes ... pravda je ze neobsahuji cesky (a na SotM velmi diskutovany) tag kct_barva ale jelikoz by jen duplikoval info v existujicich tagach neni duvid trasu kvuli tomu nevykreslit.

**Comment by tkas** [comment]
On Wed, Jan 03, 2018 at 02:35:49AM +0000, Jakub Tesinsky wrote:
> Co konkretne je na datech nedostatecneho? Obsahuji vse co je treba.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/osmcz/osmcz/issues/171#issuecomment-354926464

ahoj, ted uz ano protoze jsem to tam doplnil :-)

-- 

  Tomas Kasparek               e-mail: kasparek@fit.vutbr.cz
  CVT FIT VUT Brno, L127       jabber: tomas.kasparek@jabber.cz
  Bozetechova 1, 612 66        web   : http://www.fit.vutbr.cz/~kasparek
  Brno, Czech Republic         phone : +420 54114-1220

  GPG:    2F1E 1AAF FD3B CFA3 1537  63BD DCBE 18FF A035 53BC

  May the command line live forever!

**Comment by gorn** [comment]
Jsem nějaký zmatený - který je to commit?

**Comment by tkas** [comment]
https://www.openstreetmap.org/relation/7558676/history

Kazdopadne pokud se ti to nezda, je to na Petra vejsadu, on poskytuje ty dlazdice o kterych se bavime.

Bye

**Comment by gorn** [comment]
Tak to jsme si nerozuměli, mě šlo o změnu renderingu, nikoli dat, zkusím toho Petra.

**Comment by mkyral** [comment]
Myslíš tohle? https://github.com/osmcz/poloha.net_mapnik/issues/3 ;-)

**Comment by gorn** [comment]
Seš skvělej :)
