### ISSUE TITLE
Větší zoom OpenTopoMap

### ISSUE THREAD

**Issue by jmacura** [osmcz/osmcz#173]
Koukám, že [OpenTopoMap](https://opentopomap.org) je teď vykreslená do úrovně přiblížení 17. Může někdo upravit maxZoom v layers.js? Teď to máme omezený na 15. Nechci kvůli takový drobnosti dělat fork, pull request,...

Dík

**Comment by zbycz** [comment]
Hotovo. K vidění na demu. Na hlavním webu až někdy..
