### ISSUE TITLE
Foto rozcestníků - neunkční pole Licence

### ISSUE THREAD

**Issue by jmacura** [osmcz/osmcz#174]
Ahoj,

po delší době jsem chtěl dnes nahrát pár fotek rozcestníků (přes openstreetmap.cz, vrstvu Chybné rozcestníky) a když chci vyplnit políčko Licence, tak mi to nic nenabídne. Pamatuji si, že dřív tam byla rozbalovací lišta s možnostmi.

H.

**Comment by mkyral** [comment]
Licence se stahují z api. Takže problém je horší, api.openstreetmap.cz má výpadek, takže i kdybys nakrásně chtěl fotku nahrát, tak se ti to nepovede.

Nahlásil jsem správci serveru.
