### ISSUE TITLE
Dynamicke nahravani typu fotek z Fody

### ISSUE THREAD

**Issue by tkas** [osmcz/osmcz#182]
Fody ma doplnene api o volani tags, ktere vrati json s informacemi o
typech fotek (moznych tazich atd.):
https://osm.fit.vutbr.cz/fody-dev/api.php?cmd=tags

- seznam hlavnich tagu pro kombo box typu fotky
- zda je nebo neni vyzadovan/povolen ref
- sekundarni tagy (podtypy) pro dany typ fotky
- hodnota tagu versus zobrazeny popis

Ted je potreba upravit dialog pro pridani nove fotky aby neobsahoval
tyhle veci natvrdo. Udelal jsem novou vetev:
https://github.com/osmcz/osmcz/tree/gp_tags

Volani api tam uz je, ale bude potreba to hodne prekopat ze
stavajicicho fixniho stavu.

Pokud by se nekomu chtelo na to mrknout, budu jen rad.

**Comment by mkyral** [comment]
Formulář je upravený, více méně funguje. Jediný problém je, že původně se posílal tag "gp" a nově "rozcestnik". Server mi vrátí: bad request, nebo něco takového. Emergency point jsem nahrál úspěšně: https://osm.fit.vutbr.cz/fody-dev/?id=20733

**Comment by tkas** [comment]
> Formulář je upravený, více méně funguje. Jediný problém je, že původně se posílal tag "gp" a nově "rozcestnik". Server mi vrátí: bad request, nebo něco takového. Emergency point jsem nahrál úspěšně: https://osm.fit.vutbr.cz/fody-dev/?id=20733

Ano, to je v poradku, musi se to synchronizovane nasadit na osmap.cz i Fody.

**Comment by mkyral** [comment]
Nebo to můžeš dočasně upravit, aby to akceptovalo oba tagy. Pro instalaci na test pak jednoduše to gp umažeš.

**Comment by tkas** [comment]
Proveden merge vetve gp_tags do master. Zaviram a nasazuji na produkci.
