### ISSUE TITLE
Doplnění ikon pro fotky z Fody

### ISSUE THREAD

**Issue by tkas** [osmcz/osmcz#183]
Budu potrebovat dalsi ikony pro fotky z Fody. V souvislosti s verifikaci fotek bych rad zrusil aktualni default, ze co neni specificky typ, je pesi rozcestnik. Budou potreba:

- znaceni pesi (pruhy znaceni s nejakou barvou)
- znaceni silnicni (+- cyklo rozcestnik)
- znaceni ostatni (lyze, vozickar, cyklo)

- rozcestnik ostatni (ted mame pesi a silnicni - neco jako pesi s otaznikem?)
- prehledova fotka (neco jako ikona pro bod rozhledu v mape?)
- neznamy/ostatni typ (otaznik?)

**Comment by mkyral** [comment]
A tohle má být do které vrstvy? Rozcestníky nebo chybějící rozcestníky?

**Comment by tkas** [comment]
Tento seznam je do Rozcestniku, ted uz ale bude vhodne udelat nejake upravy i pro 'chybejici rozcestniky'

**Comment by tkas** [comment]
Aktualne jen doplnim, ze predpokladam, ze z ikon pro fotky rozcestniku se "hromadne" udelaji fotky pro chybejici rozcestniky tiz, ze se z barev prevedou do stupnu seti ( a pridaji varianty s fotakem a vykricnikem).

**Comment by tkas** [comment]
znaceni a rozcestniky doplneny v fa0f2a15322fd7466522bfa512c7c0516bbfb8e5, chybi vygenerovat vysledne ikony a doplnit prehledovou fotku.

**Comment by tkas** [comment]
Fixed by 62e845551cd400
