### ISSUE TITLE
Po přidání fotky do Fody zůstane v mapě nový špendlík

### ISSUE THREAD

**Issue by jmacura** [osmcz/osmcz#185]
Po delší době jsem zase přidal foto rozcestníku.
Po dokončení (objeví se zelená zpráva o úspěšném načtení) jsem zavřel formulář, ale v mapě zůstal modrý špendlík, který jinak slouží k označení souřadnic polohy pořízení fotky. A to i po vypnutí vrstev Fody a OsmHiCheck. Při kliknutí do mapy ho můžu libovolně přesouvat. Řekl bych, že je to spíš bug, než feature ;-)
Přikládám printscreen se špendlíkem, aby bylo jasný, co tím myslím, a s výpisem v konzoli.
![osmcz_bug_spendlik](https://user-images.githubusercontent.com/5598693/62429635-5f238080-b711-11e9-8f57-ae121562d1d5.PNG)

**Operační systém**
Windows 10 v1903

**Prohlížeč**
Firefox 67.0 (68.0 taky)

**Comment by mkyral** [comment]
Ahoj,
@vop-cz  si už na to taky stěžoval, ale nepodařilo se mi to reprodukovat :-(

**Comment by tkas** [comment]
Honzo muzes prosim jeste doplnit operacni system a prohlizec? Diky moc.

**Comment by jmacura** [comment]
OS a prohlížeč doplněny do úvodního příspěvku.

**Comment by mkyral** [comment]
Ahoj,
Ještě drobnost: jak jsi ten formulář otevřel? Pomocí ikony "Přidat foto" nebo přes chybějící rozcestníky?

**Comment by jmacura** [comment]
Přes chybějící rozcestníky (nově "Kontroly OsmHiCheck").
Druhá věc (možná nesouvisející) je, že při otevření nahrávacího formuláře (po kliknutí na modré tlačítko "Vložit fotografii") se mi nejprve zobrazí hláška "Chyba získání typu fotek z Fody!" a až na druhý pokus se normálně načte formulář.

**Comment by mkyral** [comment]
Ahoj,
jen pro info - jsem na stopě. Snad se mi to podaří během týdne opravit - podle toho jak v práci půjde migrace, která startuje zítra.

Ta druhá chyba - asi nějaká dočasná nedostupnost serveru. Zkusím ten formulář projít a lépe ošetřit chyby.

**Comment by jmacura** [comment]
Ahoj,

neřekl bych, ta druhá chyba se projeví úplně pokaždý když poprvé načtu osmap.cz. Stačí dát refresh stránky a objeví se to znova (jen při prvním pokusu o přidání fotky).

**Comment by mkyral** [comment]
Nic takového se mi neděje. Klikám na refresh, pak přidat fotku a vše funguje správně. Žádná chyba. Ani v gui ani v konsoli.

**Comment by jmacura** [comment]
Koukni sem:
https://youtu.be/B_pvSOON2PA

Do konzole se chyba vypíše až při zavření okna (což opět může souviset, ale nemusí). Zajímavý je, že chyba se vypíše i při zavření okna se správným obsahem, ale není to "t is undefined", nýbrž "undefined has no properties". Každopádně obě tyhle chyby vznikají na stejným místě kódu, přikládám i traceback:
![osmcz_bug185_console_detail](https://user-images.githubusercontent.com/5598693/63299970-61700800-c2d7-11e9-9916-3678ecdf10bc.PNG)

**Comment by mkyral** [comment]
Dík. Zkusil jsem teď v práci a tady se mi to stává taky. A je to proto, že jsem si zapnul jen vrstvu Kontrol OsmHiCheck. Běžně mám zapnutou i vrstvu Fody. Něco jsem opravil, ale ještě to musím více otestovat.

**Comment by mkyral** [comment]
Ahoj, něco jsem fixnul, ten špendlík mi ta teď nezůstává. Je to nasazené na produkci, můžeš otestovat?

**Comment by jmacura** [comment]
Mnohem lepší, teď už v mapě zůstane označen jen ten rozcestník modrým kolečkem (které se přemístí jinam, když vyberu jiný).
Zároveň zmizely i ty další chyby ("Chyba získávání...") 👍

**Comment by tkas** [comment]
To bych mozna povazoval uz za korektni chovani - zustane oznacen posledni rozcestnik, s kterym se pracovalo.

**Comment by jmacura** [comment]
Souhlas, nemám s tím problém :-) Možno zavřít issue.
