### ISSUE TITLE
Jediný rozcestník se vygeneruje jako dva ve vrstvě OsmHiCheck

### ISSUE THREAD

**Issue by jmacura** [osmcz/osmcz#187]
V OSM je jen jeden rozcestník, ale ve vrstvě OsmHiCheck se objeví dva, se stejnými daty na stejném místě. Možná je to tím, že je zároveň ski=yes i foot=yes? Je to bug nebo (nedotažená) feature?
Je to vidět na začátku videa tady: https://youtu.be/fW_xE29615M

**Operační systém**
Windows 10 v1903

**Prohlížeč**
Firefox 68.0

**Comment by tkas** [comment]
OsmHiCheck dela kontroly po jednotlivych typech, takze on vidi dva chybne rozcestniky, jeden ski a jeden foot, proto dve fotky, takze je to +- v poradku, slo by asi zobrazit lepe, ale neni to asi uprava na par radku a minut. Driv to bylo videt v titulku, ze jeden je foot a jeden ski ale to jsem na Marianovu zadost odstranil, a asi je to bez toho lepsi.
