### ISSUE TITLE
Change OSM to OpenStreetMap in the attribution text

### ISSUE THREAD

**Issue by joostschouppe** [osmcz/osmcz#189]
Hi,
It's a really minor thing, but could you please change OSM to "OpenStreetMap contributors" on line 9 of js/layers.js? On line 35 you should also include the CC BY-SA license of the osm.org tiles you're using.

**Comment by tkas** [comment]
Thanks for this push. I have this on my TODO based on CZ local chapter application process mail communitation (you are there too), but I lack free time last few months. Updated in 5e0e30037411e32436e77fbc9467038dbd27a45f.

**Comment by joostschouppe** [comment]
Thank you!
