### ISSUE TITLE
Nastavit CORS pro http://map.openstreetmap.cz/table/all

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#19]
Mohl bys prosím nastavit allow CORS hlavičky pro http://map.openstreetmap.cz/table/all ?

Pokud má mapa běžet na openstreetmap.cz, bylo by potřeba, aby všechny responsy vracely hlavičku 

```
Access-Control-Allow-Origin: *
```

Více viz http://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

**Comment by zbycz** [comment]
Jinak v b5185fa295453d9836d367f7cb9307eb4c036f4c jsem překopal rozcestníky, aby šly zapínat/vypínat v chooseru a vyčlenil je do modulu. Je to ok?

**Comment by walley** [comment]
jo  to udelam, stranka je api.openstreetmap.cz. to rozdeleni je ok

**Comment by walley** [comment]
hotovo

**Comment by zbycz** [comment]
Opravdu běží, nyní rozcestníky už i na http://openstreetmap.cz :-)
