### ISSUE TITLE
Archiv talk-cz: chybějící zprávy v rámci vlákna

### ISSUE THREAD

**Issue by kudlav** [osmcz/osmcz#198]
V některých konverzacích se nezobrazují všechny zprávy.

Příklad: [Talk-cz] Moderní komunikační kanál?
https://openstreetmap.cz/talkcz/c3222

Chybí první zpráva z vlákna:
https://lists.openstreetmap.org/pipermail/talk-cz/2020-November/023046.html

Vlákno je totiž rozděleno na dvě, kvůli přelomu měsíce (tohle může být příčina??), zde zobrazovaná část:
https://lists.openstreetmap.org/pipermail/talk-cz/2020-December/thread.html

`bug` `osmcz-web`

**Comment by tkas** [comment]
Ahoj, zkoumal jsem a podle vseho je to vyjimka zpusobena tim, ze mail poslal koncem listopadu, ale tim, ze neni clenem konference, tak cekalo na schvaleni moderatorem a to probehlo az v prosinci. Behem nacitani mailu pro listopad v listopadu tam tedy mail jeste nebyl a v prosinci uz se listopad nezkontroloval. Zkusim dotahnout rucne a popremysle, jestli to jde nejak jednoduse upravit aby k tomu nedochazelo (to same bude na prelomu roku). Vis jeste o jinem pripadu nez je tento?

Upraveno reseni, naimportovano, viz. commit [https://github.com/osmcz/osmcz-web/commit/a75bac467fad2d31e84cf326a6a3d833c219c263](url)

**Comment by kudlav** [comment]
Díky moc!
Zpětně se mi to moc prohledávat nechce, ale až na něco příště narazím, dám vědět.

**Comment by kudlav** [comment]
Ahoj,
Michal Putějovský mi odpověděl na Železniční linky a email mi dorazil s textem, ovšem na https://openstreetmap.cz/talkcz/c3268 se text nezobrazuje.

**Comment by tkas** [comment]
Koukal jsem a ten mail byl HTML only bez textove casti. HTML prilohy se ale neparsuji, takze nejdena se o chybu, chovat se to "tak jak ma". Pokud nekdo najde vhodnou knihovnu na parsovani HTML, ktera bude rozumne bezpecna, tak se da nasadit a neco s tim provadet. Neni to ale prace na 5minut.
