### ISSUE TITLE
old.openstreetmap.cz na github

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#20]
Z jakých částí se vlastně skládá old.openstreetmap.cz? Můžeš to prosím nějak popsat? Přijde mi, že tam máš hodně užitečných věcí, skriptíků, atd.

Byl bych rád, kdybys třeba i bez dalšího zpracování nahrál na github zejména to co se týká rozcestníků. Jednak ze zájmu a pak by to taky šlo líp rozšiřovat.
Klidně to vytvoř jako repo v github.com/osmcz

Šlo by?

**Comment by walley** [comment]
http://svn.openstreetmap.cz/svn/walley/osmcz/

rozcestnikove api je v 
http://svn.openstreetmap.cz/svn/walley/osmcz/p/Guidepost/Table.pm
upload je v guidepost.php, upload*, exifme.pl
zbytek je web

klidne to sem nahraju

**Comment by mkyral** [comment]
Tak jsem zkusil zdejší importér. Může být takto?
https://github.com/osmcz/old_osmcz

A není mi jasné, kdo má teď práva commitovat.

**Comment by zbycz** [comment]
Supr! @walley jestli vyhovuje můžeš používat nyní tento nový.

Commitovat můžeš ty jako Admin + owneři organizace (zatím já a walley). Ještě umí github týmy - čili můžeme vytvořit tým lidí, kteří budou moc commitova kamkoliv - dělal bych asi na základě pullrequestů, které přijdou - tím se pozná jestli člověk fakt umí a nepotřebuje commity doupravovat.

**Comment by mkyral** [comment]
No v každém případě bych stejně nejprve vypreparoval backend rozcestníků do extra projektu.

Ještě by se mi hodil nějaký úvod do toho kódu. Narazil jsem tam na nějakou sqlite databázi - tam jsou ty rozcestníky? Nebo jen struktury tabulek?

**Comment by walley** [comment]
soubor guidepost je komplet databaze, tak uz holt sqlite funguje;)

**Comment by walley** [comment]
taky se to musi v podstate cely smazat,  krome adresare p a uload\* a editor.html a guidepost.php a exifme.pl

**Comment by mkyral** [comment]
Jasně. Jak funguje sqlite vím. Jen jsem netušil, že tam je aktuální databáze :-D

**Comment by walley** [comment]
jojo svn zaroven dela zalohu:)

**Comment by walley** [comment]
v tehle podobe je to hotovej a ukoncenej projekt, zaviram. Na API udelame novy repo.

**Comment by zbycz** [comment]
:+1:
