### ISSUE TITLE
🔒 Chybí bezpečnostní hlavičky – Strict-Transport-Security

### ISSUE THREAD

**Issue by R3gi** [osmcz/osmcz#201]
Webu chybí některé bezpečnostní hlavičky. Například `Strict-Transport-Security`, která říká prohlížeči aby stránku načítal výhradně přes https.
Implementace může vypadat následovně:
`Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS`

Následně je možné doménu zařadit do [preload listu](https://hstspreload.org/?domain=openstreetmap.cz).

Použití aktuálních hlaviček si lze ověřit v prohlížeči nebo nástrojem [SecurityHeaders.com](https://securityheaders.com/?q=https%3A%2F%2Fopenstreetmap.cz&followRedirects=on).

**Comment by tkas** [comment]
A nezkusil jsi se zamyslet proc by to tak mohlo byt? Treba to ma nejaky rozumny duvod...

**Comment by R3gi** [comment]
Díky za vstřícný přístup :-) Dám se podat. Jaký rozumný důvod to má?

**Comment by tkas** [comment]
Co treba obsah tretich stran, ktery neni pristupny pres https, he? Jinak vstricny pristup si necham pro ty, co ho sami pro ostatni maji. Pokud nekdo zacne tim, ze vsechny kolem pourazi a rekne, ze se maji vratit do hrobu, tak nevim, proc bych k nemu mel byt vstricny.

**Comment by R3gi** [comment]
Chápu, byť je to dost subjektivní. Mrzí mě, že se tě má kritika používaných nástrojů a nastavení komunitní komunikace dotkla. Nicméně, myslím že mé hlášení možné chyby je věcné a relevantní. Zavřít defekt bez uvedení důvodu mi přijde hloupé, jakkoliv mi může být nahlašovatel problému osobně sympatický.
