### ISSUE TITLE
Přidání Matrix kanálu na stránku o mapě

### ISSUE THREAD

**Issue by okias** [osmcz/osmcz#203]
$subj

**Comment by tkas** [comment]
Ahoj, to neni problem, prosim ale o navrh kam presne a text s patricnym URL na ktere se odkazat.

**Comment by okias** [comment]
Nápady:

1. https://img.shields.io/matrix/osmcz:matrix.org?style=social hodit někam do horní lišty na pravou stranu (je to takové nepříliš nápadné, ale zase viditelné pokud se člověk rozhlíží)
2. záložka "O Mapě", vedle Zjistit více o OSM přidat tlačítko https://img.shields.io/matrix/osmcz:matrix.org?style=plastic
3. "Máte dotaz, nápad nebo by jste rádi něco probrali? Přijďte mezi nás do <a href="https://matrix.to/#/#osmcz:matrix.org">chatu</a>." nad box "Konference".

volbu 1. je případně možno i zkombinovat s 2. a 3.

URL je pokaždé: https://matrix.to/#/#osmcz:matrix.org

**Comment by tkas** [comment]
Nakonec jsem dal zatim na stranku s informaci o komunite, kde je prehled kanalu, ktere komunita pouziva. Tam mi to dava nejvetsi smysl. Jinde to nezapada - prijde mi hloupe vypichovat nekde jeden z kanalu (navic aktualne minoritni) a jine nezminit:

https://openstreetmap.cz/komunita

**Comment by okias** [comment]
Rozumím, každopádně ač minoritní (i když byl zavedený před pár dny), lidé přibývají. Matrix je dneska standard napříč OSS a Free projekty (Mozilla, GNOME, KDE, milion malých projektů). Donutit dneska někoho k Jabberu je marné a kvůli drobné nejasnosti - ne každý píše hned na mailing list.

Pokud časem dojde k prudčejšímu nárůstu uživatelů, dovolím si znovu otevřít, pokud nevadí?
