### ISSUE TITLE
[feature req.] Přejít na Plausible Analytics nebo Matomo

### ISSUE THREAD

**Issue by okias** [osmcz/osmcz#204]
V rámci uchování soukromí uživatelů webu, bylo by hezké nepoužívat soukromí nerespektující Google Analytics.

Dalším argumentem je, že část uživatelů používá uBlock případně nativní blokování reklam a trackingu Firefoxu, které blokuje GA. To musí vést k nepřesnostem v analytice.

**Comment by tkas** [comment]
Ahoj, uz jsem to chtel kdysi uplne odstranit, ale tehdy s ozvaly hlasy proti. Asi to zkusim znovu nadhodit. Spis jsem pro uplne odstraneni, osobne nevidim uplne duvod to na tomto webu nejak monitorovat. Tebe napada, k cemu by to bylo dobre?

**Comment by okias** [comment]
Vzhledem k tomu, že aktuálně nevidím do toho co se děje dnes s GA (či to nějak vyhodnocujete nebo s tím dál pracujete), tak nevím. Každopádně odstranění a v případě potřeby rozběhnutí [Plausible](https://blog.elementary.io/leaving-google-analytics-is-finally-plausible/) nebo něčeho jiného je taky řešení. Každopádně třeba veřejná statistika se zdá býti [pěkná](https://plausible.io/elementary.io)

**Comment by tkas** [comment]
GA odstraneno.
