### ISSUE TITLE
Nefunkční odkazy

### ISSUE THREAD

**Issue by kudlav** [osmcz/osmcz#205]
## https://openstreetmap.cz/ vlevo dole v sekci MAPS.ME
- https://maps.me/iphone-app-pro
- https://maps.me/android-app-pro
- https://maps.me/amazon-app-pro
- https://maps.me/get

## https://openstreetmap.cz/vyuziti
- text _garmin.openstreetmap.cz_ -> http://garmin.openstreetmap.cz/
- text _Další videa zde_ -> https://openstreetmap.cz/admin/pages/edit/25https://openstreetmap.cz/videa

## https://openstreetmap.cz/galerie
- text _Parkování v Praze_ -> http://zby.cz/parkovani/
- vespod text _ITO Maps_ -> https://www.itoworld.com/map/

## https://openstreetmap.cz/quickstart
- vespod text _anglicky_ -> https://www.mapbox.com/blog/making-the-most-josm
- text _konvence mapování_ -> https://openstreetmap.cz/wiki.openstreetmap.org/wiki/WikiProject_Czech_Republic/Editing_Standards_and_Conventions

**Comment by kudlav** [comment]
maps.me objeven náhodou, ostatní odhaleny nástrojem: https://www.deadlinkchecker.com/website-dead-link-checker.asp

**Comment by tkas** [comment]
Diky, jak bude chvilka casu, tak to projdu a zkusim s tim neco udelat.

**Comment by tkas** [comment]
Prosel jsem, neco aktualizovalm nejake mrvoly odstranil. Jeste jednou diky!
