### ISSUE TITLE
taginfo "Chronology" nepocita lokalni data

### ISSUE THREAD

**Issue by mahdi1234** [osmcz/osmcz#208]
K dnesku mame v CR 13903 kontejneru na tridenej odpad - https://taginfo.openstreetmap.cz/tags/recycling_type=container#overview

Po prepnuti na zalozku "Chronology" graf dosahuje k 240K https://taginfo.openstreetmap.cz/tags/recycling_type=container#chronology tzn bere celosvetovy data a ne pouze lokalni.

Asi by melo stacit upravit "chronology" cestu (prevzato https://github.com/taginfo/taginfo/blob/master/taginfo-config-example.json ).

```
        "db": {
            // The OSM planet file or extract where we read the OSM data from.
            "planetfile": "/osm/planet/var/current-planet.osm.pbf"
        },
        "chronology": {
            // The OSM history planet file or extract where we read the OSM data from.
            "osm_history_file": "/osm/planet/var/current-history-planet.osh.pbf"
        }
```

**Comment by tkas** [comment]
Zkontaktoval jsem autora taginfo, uvidime, co k tomu rekne. Evidentne to nesedi, podle prvniho pohledu je chronology DB jen jedna pro vsechny taginfo instance.

**Comment by tkas** [comment]
Tak uz pocita ;-)
