### ISSUE TITLE
Rozcestniky - nabodenicka

### ISSUE THREAD

**Issue by jzvc** [osmcz/osmcz#21]
Tam kde je pachatel nebo obrazek s nabodenicky to je rozbite, zjevne nejaky problem pri prevodu kodovani.

http://map.openstreetmap.cz/img/guidepost/Mile%C3%85%C2%A1ov.jpg

**Comment by mkyral** [comment]
Ahoj, kde na mapě je tenhle rozcestník?

**Comment by Krakonos** [comment]
Tady je třeba můj, který má jenom špatně zobrazené jméno:

http://openstreetmap.cz/#map=18/50.20452/14.36506

**Comment by walley** [comment]
v databazi je to dobre, api to vraci dobre do editoru, pravdepodobne nekde dochazi k nejakemu prevodu, ac to ma byt vse v utf8 a zadne prevadeni se konat nema.

**Comment by jzvc** [comment]
Ten co sem odkazoval je v Milesove ... 

nastaveni connection do databaze? Nebo nejake bydefault konverze api?

**Comment by mkyral** [comment]
@walley Tak to vypadá, že problém je v tom, že server tvrdí, že se jedná o text/html. Prohlížeč pak nadává, že není deklarována znaková sada a použije ascii.

```
  HTTP/1.1 200 OK
  Date: Mon, 11 Jan 2016 16:41:30 GMT
  Server: Apache/2.2.22 (Debian) DAV/2 SVN/1.6.17 PHP/5.4.45-0+deb7u2 mod_ssl/2.2.22 OpenSSL/1.0.1e mod_perl/2.0.7 Perl/v5.14.2
  Access-Control-Allow-Origin: *
  Keep-Alive: timeout=15, max=100
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Content-Type: text/html
Délka: neudáno [text/html]
```

_The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol._

**Comment by walley** [comment]
ok zkusim si pohrat s hlavickama

**Comment by mkyral** [comment]
Podle mne bude stačit poslat 

```
Content-type: text/json
```

**Comment by jzvc** [comment]
utf-8 by to asi posilat melo ... at uz tam bude cokolil.

Jop a jinak kdyz uz tak `application/json`
http://www.ietf.org/rfc/rfc4627.txt

**Comment by walley** [comment]
hmm application/json zpusobi ze to uz nefunguje vubec

**Comment by walley** [comment]
na testovani abych to nemusel furt hledat lynx -head http://api.openstreetmap.cz/table/id/4766?output=geojson

**Comment by walley** [comment]
udelal sem nejaky pokrok, problem byl v databazi, nebyla prepnuta do utf8 a ty modyly ktere trvaji na use utf8 pak nefungovaly, protoze dostaly stringy s nenastavenym utf flagem. ted se zatim zda ze to jede

**Comment by walley** [comment]
funguje. (prozatim)
