### ISSUE TITLE
Strava záznamy mizí při detailnějším pohledu

### ISSUE THREAD

**Issue by nesnera** [osmcz/osmcz#210]
Strava záznamy mizí při detailnějším pohledu viz. srovnání:
- [osmap.cz](https://osmap.cz/?mlat=49.4486&mlon=17.5830&zoom=17)
- [freemap.sk](https://www.freemap.sk/?map=18/49.448554/17.582889&layers=Xn1s0)

**Comment by tkas** [comment]
Strava podklady josu max. do zoom 16 (a jeste i to tusim omezili a jsou to mozna jen starsi data a nove jen do 15). Feeemap pouzije pro vetsi zoomy prepocitane dlazdice z mensich zoomu (zde pro zoom 17 jsou data ze zoom 15). S timhle asi nic moc nenadelame, tahle moznost tam u nas asi neni.

**Comment by nesnera** [comment]
@tkas Tudíž [větička](https://www.reddit.com/r/openstreetmap/comments/i32p6i/strava_heatmap_on_id_editor/?context=3): "As for license, Strava and Strava employees have said a number of times that they intend for the heatmaps to be used for OSM mapping, but that doesn't mean they've made it easy." v reálu až tak žhavá není?
Slůvko "asi mi v "tahle moznost tam u nas asi neni" dává naději, zavření ji zabíjí i pro budoucí rozvoj 🥴

**Comment by tkas** [comment]
No pokud najdes nekoho, kdo se tomu bude ochoten venovat, klidne otevru tohle i ruzna dalsi, ale bohuzel, lidi nejak nejsou (viz zbycz). Jinak proc to strava omezila (drive to bylo) tezko rict, duvody mohou byt ruzne.

**Comment by nesnera** [comment]
Důvod je jasný. Spíš mi šlo o to, aby se neobjevovalo objevené a když už naopak někdo chuť a čas má, aby měl kam sáhnout.
