### ISSUE TITLE
Archiv talk-cz: problém s kódováním

### ISSUE THREAD

**Issue by nesnera** [osmcz/osmcz#211]
U některých zpráv je rozhozené kódování:
- např. Značkař KČT podruhé - https://openstreetmap.cz/talkcz/c123
  - jinde OK např.  https://openstreetmap.cz/talkcz/c3483
- Pipermail 0.09 (Mailman edition) tím netrpí - https://lists.openstreetmap.org/pipermail/talk-cz/2021-May/thread.html

Možná související #200

**Comment by nesnera** [comment]
Podivný mix je též v první sekci tady - https://lists.openstreetmap.org/listinfo/talk-cz

**Comment by tkas** [comment]
Souvisi to s tim, ze spravci mail serveru jednou za cas meni kodovani. Moc nechapu proc, ale proste to delaji. Na informacich o konferenci jsem to opravil. Na maily se podivam, tam bude potreba zahodit a naimportovat znovu.

**Comment by tkas** [comment]
Zkusil jsem znovu naimportovat, ale je tam nejaky dalsi problem, ktery driv nebyl. Mrknu na to jeste v tydnu.

**Comment by nesnera** [comment]
Zachovají se při reimportu odkazy? Třeba tento mi aktuálně nefunguje - https://openstreetmap.cz/talkcz/c3483

**Comment by tkas** [comment]
Ted reimport nedopadl dobre, kazdopadne odkazy ma zby udelane dost blbe, takze obecne se zachovat nemuseji.

**Comment by tkas** [comment]
Proveden druhy reimport s upravou vstupu, ted uz by kodovani melo byt dobre vsude, bohuzel diky opravam chyb v datech nesedi odkazy. S tim ale nic nenadelam.

**Comment by nesnera** [comment]
Narazil jsem asi na chybku asi v importu. Zkus:
- otevřít https://openstreetmap.cz/talkcz/202201
- tam pak vlákno "Naučné stezky" (to jsem zakládal letos já)
- po otevření z toho je "KeepRight - překřížení bez křižovatky" - někdy z 2013

**Comment by tkas** [comment]
Ahoj, i kdyz to tak nevypada, tak je to "v poradku". Jestli cches technicke detaily, tak mi brnkni, je to dost slozite na vysvetleni detailne - zjednodusene v tom roce 2013 bylo vlakno s predmetem 'Naucne stezky' a proto se to na to napojilo - mrkni uplne dolu na tu stranku - v prubehu diskuze totiz nekdo zmenil predmet z puvodniho KeepRight na tohle.
