### ISSUE TITLE
[ERROR] - Nelze se přihlásit

### ISSUE THREAD

**Issue by inson1** [osmcz/osmcz#221]
![image](https://github.com/osmcz/osmcz/assets/75314629/79c5d8df-f2dd-4105-b2a1-9baf6f249ff4)

**Comment by tkas** [comment]
What is your OSM login please and in what stage does this happen to you (when you click on login link, when you fill OSM data or elsewhere?) Thanks tom.k

**Comment by inson1** [comment]
@tkas 
Kliknul jsem na přihlásit se
![image](https://github.com/osmcz/osmcz/assets/75314629/1c19812f-845d-4315-a2ac-b4b27ff36e22)
Kliknul jsem na Grant access 
(adresa stránky - https://www.openstreetmap.org/oauth/authorize?oauth_token="oauth token")
![image](https://github.com/osmcz/osmcz/assets/75314629/787ad770-fbee-459e-91bb-a0ebd4c56284)
Chyba vykočila 
(adresa stránky https://openstreetmap.cz/oauth/callback?oauth_token="oauth token")
![image](https://github.com/osmcz/osmcz/assets/75314629/7ac999de-ec42-4c76-879f-b3ac62c04655)

Přihlášenej na Open street mapách jsem

Chyba by měla být u vás
![image](https://github.com/osmcz/osmcz/assets/75314629/01f986f5-dc03-43c6-9c78-9190e6767a13)

**Comment by inson1** [comment]
A teda používám Brave, nemůže to být tím?

**Comment by tkas** [comment]
Koukal jsem, ale nic podezreleho jsem nenasel. Muzes to prosim zkusit v jinem prohlizeci? Pripadne se podivat do konzole prohlizece, jestli si tam prohlizec na neco nestezuje.

**Comment by Fejby** [comment]
Mám stejný problém.

**Comment by inson1** [comment]
@tkas 
Edge 
![msedge_hoQL6AwtV9](https://github.com/osmcz/osmcz/assets/75314629/cc0ae751-9d71-4673-847e-ed4a81a7292a)
![msedge_487wOhATcY](https://github.com/osmcz/osmcz/assets/75314629/cf108bc7-a373-4f66-9c23-f72629e45ceb)

**Comment by tkas** [comment]
A prohlížeč? Chyba se objeví při stejném postupu a ve stejný okamžik?

**Comment by inson1** [comment]
@tkas  Brave now
![brave_e8DfrW42ig](https://github.com/osmcz/osmcz/assets/75314629/df04cd88-ee0e-46ff-8fb2-199b6b9dfab8)

**Comment by tkas** [comment]
OK, tentokrat jsem v logu byl schopen neco najit. Mozna to s tim nesouvisi, ale jestli prosim muzete zkusit, jestli se neco zmenilo?

**Comment by inson1** [comment]
@tkas nic, edge/brave oba stejný
![brave_LxwlYbSNSa](https://github.com/osmcz/osmcz/assets/75314629/2b120ea1-12dc-4e3e-801f-430e810cd8ce)

**Comment by tkas** [comment]
OK, budu patrat dal, aspon jsem na stope...

**Comment by inson1** [comment]
určitě by byl zajímavý pohled od @Fejby, kdo ví co jsem mohl po.... když to má víc lidí, tak je to určitě chyba

**Comment by Fejby** [comment]
Mám úplně totožné problémy, včetně toho erroru 500. Ale mohu poslat video, jakým způsobem to nefunguje. 🙂

**Comment by tkas** [comment]
Video ted asi nepomuze, problem je, ze mne to funguje, tak se mi to blbe ladi. Zajimave je, ze na zacatku to nehazelo error 500 ale chybu vevnitr. Zkusim se v tom povrtat a kdyz na neco prijdu nebo budu potrebovat nejaky test, tak dam vedet.

**Comment by inson1** [comment]
@tkas Říkám si to samý. Možná jsou to dva bugy? idk. Uvidíme.

Btw a teď se to nedostane ani na grant access page.

**Comment by Fejby** [comment]
Error 500 to hazí, když se neúspěšně přihlásím a chci to zkusit znovu, abych se toho erroru zbavil, tak se musím odhlásit přes openstreetmap.org v nastavení OAuth 1. Poté se opět přihlašovací stránka načte.

**Comment by inson1** [comment]
@Fejby Takže poprvé moje 1. chyba a pak ta 500 aha
Jo to dává smysl, pamatuju si, že jsem dělal něco navíc a to bylo tohle.

**Comment by inson1** [comment]
@Fejby Ale pořád nám chybí tvůj prohlížeč :)

**Comment by Fejby** [comment]
Brave 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)

**Comment by inson1** [comment]
@tkas Tak jsem zkusil ty práva revoknut a zkusit to na edgy znovu
dosal jsem se na grant access page
![msedge_xRCMYtshGY](https://github.com/osmcz/osmcz/assets/75314629/8bbd901f-1d32-457e-9ecb-ff856819c60e)
zmáčknul jsem refresh
![msedge_xhfT1I1V0j](https://github.com/osmcz/osmcz/assets/75314629/09498749-43e0-4fe4-8f36-f2f444d2efbe)

**Comment by inson1** [comment]
@Fejby Zkusíš taky i jinej prohlížeč? Nejlépe třeba Chrome ten tu ještě nebyl.

**Comment by Fejby** [comment]
Jasně, zkusím Chrome i Firefox. 👍

**Comment by tkas** [comment]
Jeste pro jistotu - jaky je @Fejby tvuj OSM login, je to Fejby?

**Comment by Fejby** [comment]
Ano, Fejby. Jdu zkusit ty jiný prohlížeče.

**Comment by inson1** [comment]
@tkas Librewolf
![librewolf_QRTHQGjJ0a](https://github.com/osmcz/osmcz/assets/75314629/e22082a7-0eff-4efe-a8d0-f1e6fa765518)

**Comment by Fejby** [comment]
Firefox 119.0.1 - stejný problém (Místo erroru 500 je teda prázdná stránka)
Google Chrome 119.0.6045.159 (Official Build) (64-bit) - také totožný problém

**Comment by inson1** [comment]
@Fejby Jak moc dlouho máš účet? Třeba to může mít něco společného s tím? Nebo změna verze něco po.. a tobě to funguje, protože už to bylo připojený v minulosti? @tkas Třeba si zkus založit druhej účet pro experiment? Ať to můžeš zkusit ze stejnými podmínkami jako my :) Ale to vařím z vody.

**Comment by tkas** [comment]
Ano, to jsem ted udelal a novy ucet se chova stejne jako vam. Takze jdu patrat proc, ale asi to nebude hned, neni tam porad nic videt na prvni pohled.

**Comment by jmacura** [comment]
Možná souvisí s https://github.com/openstreetmap/operations/issues/867 ?
Komentáře https://github.com/openstreetmap/operations/issues/867#issuecomment-1745262995 a dále popisují podobný problém (ačkoliv tvrdí, že byl 4. října vyřešen).

**Comment by tkas** [comment]
Tak nakonec jsem opravil nekolik veci, zkuste prosim a dejte vedet. Diky.

**Comment by inson1** [comment]
@tkas už to funguje. Co jsi opravil? :) Btw proč tu není commit? A skvělá práce. 

Co tyhle dvě věci? (Brave - Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit))
Mám zkusit víc prohlížečů?
![brave_uWFpIVrQ29](https://github.com/osmcz/osmcz/assets/75314629/e306aa35-0aa2-4632-ac8d-8c47afd6af58)
![brave_pB4ADExuel](https://github.com/osmcz/osmcz/assets/75314629/ded859c0-3021-497d-8bc1-4cd839c6f398)

**Comment by tkas** [comment]
Asi 5 veci, nektere co se projevily commitem jsou v druhem repozitari. Ty hlavicky Policy jsou divne, nevidel jsem, ze by se u nas neco nastavovalo (nedela v tomhle neco Brave?). Obrazek se musi nastavit, jinak tam asi nema co dat.

**Comment by inson1** [comment]
Dneska - LibreWolf
![librewolf_4oX8gE72p7](https://github.com/osmcz/osmcz/assets/75314629/c4ecdb06-da44-43a0-a781-d9c7ed2d0510)
![librewolf_ERco7X2aFW](https://github.com/osmcz/osmcz/assets/75314629/027eae0b-456c-489f-b018-613f25578744)

**Comment by inson1** [comment]
Dneska - LibreWolf
![librewolf_a8HoZi9654](https://github.com/osmcz/osmcz/assets/75314629/8d506a7a-f9fb-45c2-b1f4-b607509fd2ad)
![librewolf_4oX8gE72p7](https://github.com/osmcz/osmcz/assets/75314629/c4ecdb06-da44-43a0-a781-d9c7ed2d0510)
brave to stejný, co se změnilo?

**Comment by inson1** [comment]
@tkas 
Chtěl jsem otestovat ty policy a ...... 
A co tam teda dělá tohle když obrázek chybí? Je to záměrně?

**Comment by tkas** [comment]
Neco zaplacalo misto na disku, takze to s predchozima vecma nijak nesouvisi. Zjistim co a uklidim to tam.

**Comment by inson1** [comment]
@tkas teď to zase funguje ....
Ale co je tohle ?
![brave_8ppqjX7KF4](https://github.com/osmcz/osmcz/assets/75314629/ee4fb3c3-f71b-4abd-b978-fc573d419572)

**Comment by inson1** [comment]
@tkas jo teď to zase už funguje.

**Comment by inson1** [comment]
@tkas tak ty jsem to otestoval na LibreWolfu a tam to ty policy nepíše, ani ten obrázek tam není. Ale šel by ten obrázek vyřešit? Mám otevřít další issue?

**Comment by tkas** [comment]
Ne, opravil jsem to.

**Comment by inson1** [comment]
@tkas pokud má ta ikona být červená, tak je to správně 😁 skvělá práce

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
