### ISSUE TITLE
Statistiky na kyblsoft nejsou aktualni

### ISSUE THREAD

**Issue by mahdi1234** [osmcz/osmcz#222]
Feedback z chatu:

> 
rejpall (xmpp) » nejak nefunguji statistiky uzivatelu - https://openstreetmap.cz/komunita - odkaz uplne dole - nebylo by lepcejsi odkazovat treba https://osmstats.neis-one.org/?item=countries&country=Czech%20Republic

mahdi - myslen je tento odkaz

`<p>Více statistik <a href="[http://osm.kyblsoft.cz/statistiky/aktivita-uzivatelu](view-source:http://osm.kyblsoft.cz/statistiky/aktivita-uzivatelu)">u Aleše</a>.</p>`

**Comment by tkas** [comment]
Upraveno.
