### ISSUE TITLE
Taginfo - zvazit orezani regionu

### ISSUE THREAD

**Issue by mahdi1234** [osmcz/osmcz#223]
Pokud dam dnes, 11.12. vyhledat vysledky pro `amenity=post_box` taginfo ukazuje vetsi pocet nez overpass

taginfo - 17498
overpass - 17357

Stejnej vysledek jako taginfo dostanu lokalne pres osmium pri pouziti geofabrik pbf - https://download.geofabrik.de/europe/czech-republic.html (ktery zamerne presahuje pres hranice)

Osobne pouzivam pro orez https://github.com/mahdi1234/OSM_CZ_osmium/blob/main/czech_republic.geojson (vytazenej admin level pomoci overpassu, mozna je i neco presnejsiho), nevim, jestli je mozny aplikovat i na taginfo (mam pocit, Tom zminoval, ze to neni primo Geofabrik extract, ale ze pouziva jejich koordinaty).

**Comment by tkas** [comment]
Ahoj, je to tak, ze na serveru, kde se to zpracovava, se stahuje extrakt pro CR na jednom miste a vyuziva to nekolik projektu. Z toho duvodu pouzivam presah hranic (polygon tusim od geofabric). Upravit by to znamenalo generovat dalsi zdroj (byt z toho predchoziho). Je tedy otazka, jestli to realne necemu zasadnimu pomuze, aby to melo smysl komplikovat. Co @mahdi1234 ?

**Comment by mahdi1234** [comment]
Ahoj, v tom pripade bych to nechal, jak je. Toto vlakno muze slouzit jako odkaz, kdyby se nekdo ptal, proc vidi trochu jiny cisla. Zaviram, dik @tkas :)
