### ISSUE TITLE
Rozcestníky se dotahují vícekrát při každém posunu

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#23]
@mkyral: 
 teď se mi ty rozcestníky chovají zajímavě - při každém posunu mapy se znova dotáhnou a po chvíli mám jeden rozcestník klidně i desetkrát :-D

![duplicity](https://cloud.githubusercontent.com/assets/155542/12218573/a1e9e4fa-b723-11e5-97ac-c5510f1955ab.png)

**Comment by walley** [comment]
opraveno
