### ISSUE TITLE
Bublina rozcestníku - zbytečný název souboru

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#29]
V bublině rozcestníku je naprosto zbytečný název souboru. Ten by zrušil a jako klikatelný bych udělal obrázek - pořád na něj klikám a nic to nedělá ;-)

![bublina](https://cloud.githubusercontent.com/assets/155542/12223533/859b68f2-b7da-11e5-8c38-310de1c389e2.png)

Jo a taky bych přeložil "guidepost by" a "edit"

**Comment by mkyral** [comment]
Co třeba takto?

![bublina2](https://cloud.githubusercontent.com/assets/155542/12224028/31ac5280-b7e7-11e5-93a4-6b60f2b786cd.png)

**Comment by walley** [comment]
nekdo tam chtel ikonku tuzky mam pocit :) 
napadlo me udelat editaci primo v te bubline, udelat nad obrazkem taby view a edit a v tom edit by byla editacni tabulka.

to tvoje je lepsi kazdopadne

**Comment by zbycz** [comment]
Jestli to budeš předělávat, doporučuj mrknout na ten bootstrap má jak ikonku tužky, tak připravené komponenty pro horní taby (viz `.nav-tabs`)

//jinak dík za úpravu toho clearLayers - právě jsem to nasadil v rámci release 0.2 na web

**Comment by mkyral** [comment]
@walley Jo tužka. To je nápad - já se tu trápím se stylováním odkazu jako tlačítka. Ale ikonka asi bude lepší.

![bublina3](https://cloud.githubusercontent.com/assets/155542/12224494/8e7c50fe-b7f2-11e5-80fc-ae2dd02477e4.png)

Tu editaci buď rovnou v bublině, nebo v nějakém vysouvacím panelu na straně. 
V tom panelu bych pak určitě udělal vkládání nového rozcestníku.

Taky by to chtělo propojit s rozcestníky z OSM. Takže data by byla z OSM a u toho by byly fotky nebo ikona - přidat fotku. Ale to je asi na jiné issue.

**Comment by mkyral** [comment]
@zbycz To bylo na mne? Já se rád pohrabu v html, ale s .js moc velký kamarád nejsem.

**Comment by zbycz** [comment]
Spíš to bylo na walleyho. Ale vlastně tak obecně,kdo se do toho pustí :)

**Comment by jzvc** [comment]
Kdyz uz to tu probirate, nebylo by od veci do ty bubliny natahovat jen nejakej lowres nahled. Neni asi optimalni, kdyz se do toho pidinahledu stahuje 10MB.

**Comment by mkyral** [comment]
Bylo. Ale to by musel podporovat server a nepamatuji si, jaký je k tomu důvod. 
@walley ?

**Comment by zbycz** [comment]
Až to walley zveřejni tady na githubu, tak se na to můžem mrknout a doprgat
:-)​

**Comment by mkyral** [comment]
Co takhle?
![bublina5](https://cloud.githubusercontent.com/assets/155542/12241132/a186e098-b891-11e5-86fb-6bdfd1e212a0.png)

~~A neví někdo, proč ten obrázek vždy při prvním načtení přetéká? Až druhé zobrazení je v pořádku.~~
![bublina4](https://cloud.githubusercontent.com/assets/155542/12241129/a038c81e-b891-11e5-97cf-dfb6b1ff60bb.png)

Už jsem našel:

```
.leaflet-popup-content {
    width:auto !important;
}
```

**Comment by walley** [comment]
ty nahledy bych udelal necim uz hotovym jako je napr: http://phpthumb.sourceforge.net/

**Comment by mkyral** [comment]
@walley Záleží jak to plánuješ. Jestli během uploadu tak klidně. Jinak bohatě stačí imagemagick:

```
convert -size 180x180 -resize 180x180 -quality 75  -strip "20151107_135102_93.jpg" "tb_20151107_135102_93.jpg"
```

**Comment by mkyral** [comment]
@walley mám poslal pull request těch mých změn? Jediné, co by to chtělo je, že po kliknutí na tužku se stane číslo rozcestníku editovatelné a po potvrzení se změna pošle na server.

**Comment by walley** [comment]
prosil bych zmenu jen toho editu, ja uz ten zbytek ted udelal

**Comment by mkyral** [comment]
Tak přesně tohle nemám ;-)

**Comment by walley** [comment]
tu tuzku? 
editor v bubline bych resil az nejdriv zitra

**Comment by mkyral** [comment]
```
html_content += "<a href='http://api.openstreetmap.cz/table/id/" + b.id + "'><span class='glyphicon glyphicon-pencil' title='upravit'></span></a>";
```

**Comment by walley** [comment]
jojo to je presne ono.
ja bych to ted zavrel a na editor v bubline ci podobne udelal uz novou issue at se to neplete.
ted by to melo vypadat vizualne podle tveho navrhu.
