### ISSUE TITLE
Mapa by si měla pamatovat poslední pozici

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#3]
Vždy když přijdu na stránky, nebo kliknu na něco nahoře v menu, tak se mapa vrátí do Prahy.

**Comment by zbycz** [comment]
Mapa si pamatuje poslední pozici.
Poloha se nastaví primárně dle URL, potom dle zapamatované, jinak defaultuje na ČR.

//do budoucna zvážit jestli není lepší použít [leaflet-hash](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-hash/)
