### ISSUE TITLE
Překryvná vrstva ortofoto

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#30]
Nad ortofoto by se hodila překryvná vrstva, která by obsahovala názvy měst a vesnic, silnice I,II a III třidy, řeky a jejich názvy, názvy přehrad a názvy a nadmořské výšky vrcholů.

Stejně jako současná vrstva turistických tras.

![overlay](https://cloud.githubusercontent.com/assets/155542/12229137/92a0b5d8-b844-11e5-9127-2d7a99a6dbd5.png)

Vrstva by mohla být u některých podkladů automaticky zapnutá - ortofoto, vodovky.

**Comment by zbycz** [comment]
Myslím, že další práce,které se rád ujme @pedro042 :))

**Comment by walley** [comment]
pak to uz budem mit lepsi jak gugl:)

**Comment by zbycz** [comment]
Tak jsem si dovolil vrstvu přidat. Jsme lepší google #yay

**Comment by mkyral** [comment]
No jako začátek by to ušlo, ale jsou to jen popisky. Byly by fajn ty cesty, řeky a vrcholy.

A mimochodem, google maps a mapy.cz to samozřejmě mají, takže lepší nejsme, zatím jen dotahujeme.

**Comment by zbycz** [comment]
Ty teda dokážeš zkazit radost :D 

Založil jsem na to #31 .
