### ISSUE TITLE
Používat "Turistické" místo "KČT"

### ISSUE THREAD

**Issue by j123b567** [osmcz/osmcz#32]
Stejně jako se řešilo pojmenování pro taskman. Všechny turistické trasy nejsou z produkce KČT a navíc vzhledem k jejich "podpoře" OSM bych jim tady nedělal zbytečnou reklamu.

**Comment by zbycz** [comment]
Chápu, použil jsem to zejména kvůli kratšímu textovému popisku. Zatím
necháme takto a až nasadíme lepší přepínač vrstev,tak uvedeme správně.
po 11. 1. 2016 v 11:53 odesílatel Jan Breuer notifications@github.com
napsal:

**Comment by zbycz** [comment]
Viz #33

**Comment by zbycz** [comment]
Edit viz #36
