### ISSUE TITLE
Cyklistické rozcestníky ve vrstvě turistických tras

### ISSUE THREAD

**Issue by Hroch92** [osmcz/osmcz#35]
Bylo by dobré odfiltrovat cyklo rozcestníky (bicycle=yes) ve vrstvě turistických tras z poloha.net. Nemá cenu, aby se vykreslovaly, když se nevykreslují cyklotrasy.

**Comment by mkyral** [comment]
Ale bacha na společné rozcestníky.

**Comment by j123b567** [comment]
To stejné pro horse=yes

**Comment by Hroch92** [comment]
Koňské stezky se v té vrstvě ale vykreslují, takže příslušné rozcestníky bych tam nechal.

**Comment by j123b567** [comment]
Pokud je to ale vrstva turistických tras, tak by tam IMHO koňské stezky být neměly, ne?

**Comment by pedro042** [comment]
No ona je to vrstva tras KČT, tedy původně ... je to orientované na vykreslování, takže kct_barva=*. V talk-cz byly diskuse, jak vykreslovat turistické trasy obecně, ale nedošlo k žádnému rozumnému konsensu.
Momentálně se vykreslují trasy kct_barva, a to koňské, cyklistické, lyžařské a samozřejmě hlavně pěší. Cyklistické mají žluté pruhy, lyžařské mají oranžové pruhy a pěší bílé. Koňské mají kolečko.
Ta diskuse byla o tom, jaké barvy použít.
K věci - jak poznám, že rozcestník je cyklistický? Podle příslušnosti do relace?

**Comment by j123b567** [comment]
Viz: http://wiki.openstreetmap.org/wiki/Cs:Tag:information%3Dguidepost
Např:

``` ini
tourism=information
information=guidepost
bicycle=yes
```

Jinak, koňské mají ve značce lecos. U nás třeba "U" vzhůru nohama, asi jako podkova.

**Comment by VladimirSlavik** [comment]
No, KČT mívá někdy na jedné tyči pěší, cyklo, běžky... Nevím jestli je teda možné ty rozcestníky filtrovat jenom takhle, pokud se často taguje tak že se pěší uvažuje jako default?

**Comment by Hroch92** [comment]
Buď odfiltrovat bicycle=yes, ale ponechat, pokud je tam zároveň hiking, horse, ski=yes. Nebo podle příslušnosti k relaci cyklotrasy, ale opět dát pozor, kdyby byl rozcestník i v pěší, koňské, běžkařské relaci.

Podle mě je chyba, považovat rozcestník za pěší jako default. Každopádně je jasný, že zdaleka ne všechny pěší rozcestníky mají hiking=yes.

**Comment by tkas** [comment]
Rozcestniky filtrujeme ve vrstve fotek, v zde diskutovane mape neprobiha dalsi vyvoj. Zaviram.
