### ISSUE TITLE
Stínování kopců je příliš rušivé

### ISSUE THREAD

**Issue by jkufner** [osmcz/osmcz#39]
Stíny kopců tvoří příliš jasně viditelné fleky. Je potřeba je udělat plynulé a více rozmazané.

Například:
- http://openstreetmap.cz/#map=15/49.0741/13.4005
- http://mapy.cz/turisticka?x=13.4035771&y=49.0720759&z=15&l=0&source=muni&id=2940

**Comment by walley** [comment]
to je vrstva od mapboxu, nad tim asi nemame kontrolu?

**Comment by mkyral** [comment]
@pedro042 
hmm. Jak tak koukám, tak tady někde se ztratil les: http://openstreetmap.cz/#map=14/49.0847/13.4069&layers=k

**Comment by pedro042** [comment]
@mkyral les chybí už dlouho, http://www.openstreetmap.org/relation/1460847 , je to obří relace, která není celá v CZ exportu a Mapnik to nejspíš nemá podle čeho vykreslit.

**Comment by zbycz** [comment]
Aktuálně výchozí mapa je mapbox.street, tu neovlivníme. Šlo by si tam hrát se styly, ale jsou tam limity na map-views, čili asi chceme do budoucna mít výchozí spíš nějakou naší.

ad stínování) Srovnej ještě s "KČT mapou poloha.net" tedy turistickou, kterou renderujeme my. Ta se dá upravovat - stínování tam taky není ideální, ale je to možná lepší než ten mapbox-streets.

http://openstreetmap.cz/#map=15/49.0721/13.4034&layers=k

**Comment by mkyral** [comment]
Co takhle použít mapbox.streets-basic? Ten žádné stínování nemá, tudíž tam nebudou ty fleky ;.)

Případně, dá se nějak zařídit, aby se to třeba od zoomu 13 samo přepnulo na tu basic vrstvu?
Nějak takto: http://makina-corpus.com/blog/metier/archives/leaflet-zoom-switcher

**Comment by zbycz** [comment]
Já, abych se přiznal, tak se mi stíhnování mabox.streets docela líbí. Není to mapa pro turistiku, tak holt jsou stíny jen trochu - co na tom vadí?

Jinak tady mám showcase všech stylů od mapboxu - kdyby chtěl někdo porovnat a vybrat nějaké další: http://zby.cz/parkovani/

**Comment by mkyral** [comment]
Někteří lidé mají zřejmě jiné estetické cítění. Z mého pohledu není stínování na základní mapě potřeba.

Jinak myslel jsem, že bychom mohli případně použít stejný styl jako freemap.sk. Na větších zoomech se mi docela zamlouvá. Ale když se mapa oddálí, tak už to tak slavné není.

**Comment by vop-cz** [comment]
...stinovani na turistickych mapach pomaha pri zakladni predstave o tvaru terenu - zbytek si pak uzivatele s predstavivosti musi "vymodelovat" z vrstevnic...

**Comment by zbycz** [comment]
Vzhledem k tomu, že už máme vrstevnice od pedra, tak může být default vrstva mapbox.streets-basic.
Commitnu a zavřu.
