### ISSUE TITLE
Vrstevnice

### ISSUE THREAD

**Issue by jkufner** [osmcz/osmcz#40]
//edit: 
Na poloha.net vrstvu "vrstevnice + hillshade" (s tím že od <15 nechat jen hillshade)

**Comment by zbycz** [comment]
Věděl bys o nějakém zdroji tile-vrstvy, která by šla použít?

**Comment by jkufner** [comment]
Nemám tušení. Leda se podívat, podle čeho to kreslí například Osmand. Ale ten kreslí z vektorových dat.

**Comment by zbycz** [comment]
Ok, tak počkáme jestli se někdo najde. A kdyžtak poprosíme @pedro042, aby
nám to vyrenderoval na serveru poloha.net :-)

**Comment by pedro042** [comment]
Jako zdroj kopců jsem použil http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm . Je to pročistěný rastr ze SRTM. Alespoň tak před rokem a půl byl rozhodně lepší než z NASA. Vrstevnice jsou odvozené od toho a zvektorizované v PG. Jsou zahrnuté v základní turistické vrstvě, tak není problém je udělat i samostatně. Pak jsou tu lepší zdroje vrstevnic, třeba Geoportál Praha, ale bohužel jen pro Prahu. O zdroji pro celou republiku nevím :(

**Comment by zbycz** [comment]
Výborně, tak časem prosíme jako samostatnou vrstvu "vrstevnice + hillshade" (s tím že od <15 nechat jen hillshade?)

Jinak ještě jsem kdysi používal data [ASTER GDEM](http://gdem.ersdac.jspacesystems.or.jp/), které by měly mít rastr 30m (proti 90m srtm3)

**Comment by pedro042** [comment]
tzn, jedna vrstva stíny a druhá vrstva vrstevnice? Nebo oboje v jedné vrstvě?
ASTER GDEM znám, tak právě nejsou (nebyly) opravené ty díry, hluboké desítky km ;)

**Comment by zbycz** [comment]
Byl bych pro jedna společná vrstva - nevidím usecase kde by mělo smysl vrstevnice bez hillshadu.

**Comment by jkufner** [comment]
> Výborně, tak časem prosíme jako samostatnou vrstvu "vrstevnice + hillshade" (s tím že od <15 nechat jen hillshade?)

Spíš až < 13. Na 14 hodně pomáhají prokreslit tvary kopců (obzvlášť s hillshade). Na 12 se už spíš pletou, pokud mají popisky. Na 13 jsou fajn v horách.

Ale jak se tak dívám na render od MTBMap.cz, tak jemné vrstevnice bez popisků výšky jsou velmi dobré i na oddálenější mapě.

**Comment by pedro042** [comment]
http://tile.poloha.net/hills/{z}/{x}/{y}.png

**Comment by zbycz** [comment]
Paráda, dík! Nasazeno na http://openstreetmap.cz.
