### ISSUE TITLE
wikimedia commons rozcestniky

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#41]
naimplementovat commons rozcestniky, asi jako soucast vrstvy rozcestniku pouze s jinou ikonou

**Comment by mkyral** [comment]
Trochu jsem se na to koukal, jak to je teď a asi bych šel cestou nějaké proxy, která by ty rozcestníky jednou denně stáhla z commons a pak servírovala jako geojson tiles. Viz #4

**Comment by walley** [comment]
to bude jedina moznost pokud kmlexport opravdu neumi bbox nebo se ho nenauci

**Comment by walley** [comment]
fotky bych taky necpal do poi, ale naopak do vrstvy fotografie, ktera by mohla vzniknout a zahrnovat mapillary rozcestniky a dalsi lokalizovane fotky domacich mazlicku, ktere by nekdo treba mel potrebu sdilet na openstreetmap.cz:)

**Comment by walley** [comment]
http://tools.wmflabs.org/kmlexport?l=0&project=Commons&article=Category:Hiking_and_footpath_fingerposts_in_the_Czech_Republic_by_region

url na ziskani vsech obrazku

**Comment by walley** [comment]
eaafb45a5ee5e81b0393e5bfe0825e51a589feb6

done

**Comment by zbycz** [comment]
Good job - to je parádní vylepšení.
