### ISSUE TITLE
Splash: Šipky s popiskem ovládání

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#42]
Představa:
![info-layer-switch](https://cloud.githubusercontent.com/assets/385047/12247546/c647f8e0-b8b4-11e5-8653-a4c5fb694de4.png)

Zde SVG, které je nutno napozicovat do splashe:
[info-layer-switch.zip](https://github.com/osmcz/osmcz/files/86430/info-layer-switch.zip)

**Comment by zbycz** [comment]
Komentář od @mkyral u commitu:
No nevím. I když jsem vědět, že tam ta šipka má být, tak jsem ji nemohl najít. Nakonec jsem zjistil, že tam sice je, ale trochu moc daleko od okraje - mám full HD rozlišení.

![sipka](https://cloud.githubusercontent.com/assets/155542/12255463/3ccd1b78-b8f4-11e5-86d1-dfc1770edfe8.png)

Nebude lepší dát tam nějaký "ComboBox" , který se bude jmenovat "Vybrat mapu"? Samozřejmě včetně té ikony, aby si na ni uživatelé zvykli.

**Comment by zbycz** [comment]
Komentář od @walley u commitu:
me by se libilo neco jak ma gugl a mapy.cz, malej obrazek vyrendrovane mapy s popiskem, nekde sem to i videl s osm datama ale uz nevim kde

**Comment by zbycz** [comment]
Nojo, udělal jsem to trochu nedokonalé, věděl jsem nže na fullhd to bude zlobit. Asi to je dočasné než bude #36 - tam jsou ty vrstvy vidět jak píše walley + by mohl být ten tab defaultně rozbalený.

Otázkou jestli zatím ponechat nebo úplně vyrušit.

**Comment by walley** [comment]
nesla by ta sipka udelat relativne k pravymu hornimu rohu at cestuje zaroven s velikosti okna?

**Comment by zbycz** [comment]
Nojo, já jsem trotl. Přeci position:fixed. Opravím.

**Comment by jzvc** [comment]
:D ...dejte tam k tomu vyskujiciho alzaka, a zmente kurzor na palici, 100% si kazdej klikne aby ho ubil ...

**Comment by zbycz** [comment]
opraveno

**Comment by mkyral** [comment]
Ještě by to chtělo upravit pozici vůči obsahu. Když si zúžíš obrazovku, tak je šipka zobrazena přes text.
![sipka](https://cloud.githubusercontent.com/assets/155542/12392946/f81aeeca-bdf2-11e5-9133-69e6b63bc482.png)

**Comment by zbycz** [comment]
Opraveno, zatím nenasazeno.
