### ISSUE TITLE
Commit message česky nebo anglicky?

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#43]
Možná můžeme nechat obojí, ale pokud jsou na to nějaké názory, klidně můžeme sjednotit. Což?

/cc @walley @pedro042 @JakubOnderka

**Comment by mkyral** [comment]
Za mně anglicky - člověk nikdy neví, kdy mu projekt přeroste přes hlavu a uteče do světa ;-) Totéž proměnné a komentáře v kódu. Z vlastní zkušenosti můžu říci, že třeba luštit francouzské komentáře je děs. Ale zase jsem se za ty roky pár slovíček naučil :-D

Na druhou stranu, hlášení chyb klidně česky - ta po čase zmizí. Ale kód zůstává.

**Comment by walley** [comment]
ja to pisu vsechno anglicky tak nejak ze zvyku ...

**Comment by zbycz** [comment]
Ok, přešli jsme na angličtinu. Své zdrojáky jsem už "přeložil", nyní doplněno do [CONTRIBUTING.md](https://github.com/osmcz/osmcz/blob/master/CONTRIBUTING.md)

Prosím pokud možno dodržovat formát commit message:
`<část aplikace>: <co se děje> #id`
