### ISSUE TITLE
Obecné názvy vrstev

### ISSUE THREAD

**Issue by severak** [osmcz/osmcz#46]
Nebylo by lepší použít v přepínání obecné názvy vrstev (automapa, turistická mapa...)? Bude to více přátelské k nezasvěceným...
Názvy mapových projektů by pak naopak měly zůstat dole v attribution.

Ještě jsem si uvědomil jednu věc - vrstva mapy, která je optimalizovaná pro venkov blbě vypadá ve městě a naopak. Měli bychom to zohlednit a nabídnout oba dva druhy...

**Comment by mkyral** [comment]
Jo. Taky jsem nad tím uvažoval. Možná by nebylo na škodu mít nějaké základní vrstvy a pro pokročilé zájemce pak nějaké speciální vrstvy. Viz #36

**Comment by zbycz** [comment]
Dík!. Zavírám a dávám do #36.
