### ISSUE TITLE
Zimní mapa

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#5]
Nebylo by špatné mít kromě turistické a cyklo mapy i zimní mapu. Nevím, za jdou použít dlaždice z http://www.opensnowmap.org/

V každém případě by přítomnost této mapy na hlavní stránce mohla být impulz k intenzivnějšímu mapování běžeckých tras a sjezdovek.

**Comment by zbycz** [comment]
OpenSnowMap overlay je možné používat - dle jejich [webu](http://www.opensnowmap.org/iframes/data.html#tiles).

Uzavírám issue.
