### ISSUE TITLE
Turistická mapa na Ukrajině

### ISSUE THREAD

**Issue by severak** [osmcz/osmcz#57]
@pedro042 na Ukrajině vypadá turistická mapa poněkud zvláštně - vykresluje se jen terén a ne data.

Viz http://openstreetmap.cz/#map=10/48.4661/38.8140&layers=k

**Comment by mkyral** [comment]
Ono jestli to nebude tím, že @pedro042  generuje pouze ČR. Asi by se tam mohl dát nějaký obrázek "Not available with this layer".

**Comment by mkyral** [comment]
Myslím, že bude stačit tu vrstvu přejmenovat na "Turistická mapa ČR".

**Comment by tkas** [comment]
Vrstva prejmenovana, zaviram.
