### ISSUE TITLE
Projekty - mapování turistického značení

### ISSUE THREAD

**Issue by Krakonos** [osmcz/osmcz#58]
Když máme na webu kategorii projekty, bylo by vhodné tam zařadit projekt mapování turistického značení. Ještě to nějakou chvíli potrvá a i když se nikdo nechytne, bude vidět, že se na tom aktivně pracuje.

**Comment by zbycz** [comment]
Rozhodně! Měl bys případně chuť sepsat nějaký BFU-friendly textít + pár screenshotů? Připadně napiš maila a hodím ti admina na celý web..

**Comment by Krakonos** [comment]
Když už jsem to zmínil, tak se na to mrknu. krakonos@krakonos.org (registrovaný na osm.org)

**Comment by zbycz** [comment]
Hotovo - viz https://openstreetmap.cz/turistika
