### ISSUE TITLE
Rozbité rozcestníky

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#59]
Ahoj,
v aktuální verzi na osmap.cz jsou rozbité rozcestníky, Je chyba u mne nebo na jednom ze serverů?

Po obnovení stránky se rozcestníky ve výřezu načtou, ale v logu je zase chyba s CORS. A když posunu s mapou, tak se rozcestníky ztratí a v logu zůstane chyba s parsováním JSON:

```
Žádost Cross-Origin zablokována: zásada stejného původu neumožňuje načtení vzdáleného zdroje 
na http://api.openstreetmap.cz/table/all?outputFormat=application%2Fjson&output=geojson&bbox=18.25421333312988%2C49.6438460178133%2C18.413944244384762%2C49.6822911785649. 
(Důvod: požadavek CORS selhal). <neznámé>
GET 
http://www.google-analytics.com/r/collect [HTTP/1.0 200 OK 26ms]
GET 
http://map.openstreetmap.cz/img/guidepost/20140829_161546_85.jpg [HTTP/1.0 200 OK 907ms]
true guideposts.js:41:0
GET 
XHR 
http://api.openstreetmap.cz/table/all [HTTP/1.0 200 OK 40ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data 
http://api.openstreetmap.cz/table/all [HTTP/1.0 200 OK 56ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
```

Na starší lokální kopii mi rozcestníky fungují bez problémů.

EDIT: tak zdá se, že aktuální git verze taky funguje správně.

**Comment by walley** [comment]
protoze sem to asi opravil mezitim:)

**Comment by mkyral** [comment]
Myslíš v gitu? Tak to by chtělo vyrolovat. Protože na webu mi to ani po refreshi nefunguje.

**Comment by walley** [comment]
predpokladam ze se update openstreetmap.cz nedeje automaticky, takze musime pockat

**Comment by zbycz** [comment]
nasadil jsem bez releasu aktuální repo a myslím že to pořád buguje. První se načtou dobře, ale pak to hlásí v konzoli toto
![image](https://cloud.githubusercontent.com/assets/385047/12387313/f2c5d394-bdcb-11e5-86ac-c130ff3641e9.png)

Jinak když chcete nasadit zatím pište, ještě jsem to nezautomatizoval :)

**Comment by walley** [comment]
a tak to je divny. me to funguje ( to co je zrovna v gitu) jak v chromiu, tak v seamonkey/firefox, edge funguje a vic toho nemam

**Comment by zbycz** [comment]
Fakt zvláštní tady na rawgitu to nedělá, ale na osmap.cz jo.. Občas mi to prostě házi tuhle hlášku. Podle toho rozbalítka to padá na JSON.parse() .. nechápu.

**Comment by jzvc** [comment]
Me to teda haze toto:

[00:27:01.981] SyntaxError: JSON.parse: unexpected character @ http://openstreetmap.cz/theme/js/guideposts.js:143

To skorem vypada, ze ty opravy nabodenicek ? Ale odsud to funguje. A lokalni verze taky ...

**Comment by mkyral** [comment]
No to háže všem. Myslel jsem, že je problém s hlavičkami - ta co napoprvé projde má `Accept: */*`.
Ty další už pak `Accept: application/json, text/javascript, */*; q=0.01`.

Jenže curl mi s oběma hlavičkami vrátí stejný json soubor :-(

**Comment by walley** [comment]
nefunguje to proto, ze na openstreetmap.cz se do toho json.parse cpe object, kdezto vsude jinde tam de string.

proto ta chyba ze znak 2 je o (nebo unexpected token o) protoze string obsahuje [object Object]
.
proc to tak dela zatim netusim.

**Comment by mkyral** [comment]
No hledal jsem tu chybu na webu a zdá se, že to znamená, že ten json je již rozparsovaný (a je z něj tedy objekt). Nějaké nastavení jquery?

**Comment by walley** [comment]
jquery by melo byt stejne oba weby pouzivaji stejne <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
(btw proc z guglu?:)
a ano presne to co pises ta chyba znamena

pritom ty stranky sou stejne az na nette, to by snad mohlo neco delat, nebot na osm.cz je navic 

```
<script src="/static/js/jquery.nette.js"></script>
<script>
    $("#main").on("click", "a.ajax", function (event) {
        if(!event.ctrlKey){
            event.preventDefault();
            $.get(this.href);
        }
    });
</script>
```

**Comment by zbycz** [comment]
Možná moje chyba - teoreticky za to může ten jquery.nette.js
- http://openstreetmap.cz/static/js/jquery.nette.js :-/ musím ho poladit.​

**Comment by walley** [comment]
troufl bych si rict ze to je presne ono

konkretne ten ajaxsetup
Description: Set default values for future Ajax requests. Its use is not recommended.:))

**Comment by mkyral** [comment]
Co takhle tam udělat fallback - když to spadne, tak se to zkusí znova, tentokrát bez JSON.parse?

**Comment by mkyral** [comment]
Hele co jsem našel: http://www.egoblog.cz/nette-a-ajax-zaludnost/
:-D

**Comment by zbycz** [comment]
Opravil jsem to systémově - viz http://openstreetmap.cz/theme/js/jquery.nette.custom.js

Je to ok?

**Comment by walley** [comment]
to je myslim to nejlepsi reseni

**Comment by jzvc** [comment]
Jen jeste dokomentnu, asi by nebylo od veci aby i krom html i js bylo utf8 ... ;D Chtelo by to proste na tom Apachovi nastavit utf8 vzdy, pokud neni vyslovene receno jinak.

`alert('nen� payload');`

**Comment by zbycz** [comment]
fixnul jsem to narychlo a zapomněl v editoru překliknout utf. Už opraveno. Apache je nastaven tuším dobře - tohle bylo fakt CP1250.
