### ISSUE TITLE
Dopravní mapa

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#6]
Dopravní mapa na osm.org ani po pěti letech stále nepodporuje nové dopravní schéma.
To bych tady rád viděl - pomohlo by to s mapováním dopravy.

//edit
Časem bych určitě viděl nějaká vylepšení - třeba skrýt si jednotlivé vrstvy - zobrazit třeba jen tramvaje, zvýraznění určité linky, zobrazení seznamu zastávek, zobrazení zastávkových jízdních řádů ;-)

**Comment by kamenitxan** [comment]
Já bych rád viděl onclick na zastávku, který ukáže, co tam jezdí. Na to bych se mohl tak za měsíc i podívat.

**Comment by Krakonos** [comment]
Až to uděláte, dám si tu práci a otaguju linkové vedení v Mostě a Litvínově! (Teď nejsou
skoro ani zastávky) :-)

On Sun, Jan 10, 2016 at 11:46:18PM -0800, kamenitxan wrote:

> Já bych rád viděl onclick na zastávku, který ukáže, co tam jezdí. Na to bych se mohl tak za měsíc i podívat.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/osmcz/osmcz/issues/6#issuecomment-170454792

## 

S pozdravem Ladislav Láska                          laska@kam.mff.cuni.cz
Katedra Aplikované Matematiky, MFF UK               tel.: +420 739 464 167

**Comment by mkyral** [comment]
@Krakonos Tak až to budeš dělat, tak bys mohl na wiki sepsat nějaký pěkný návod ;-)

**Comment by zbycz** [comment]
To se v zásadě řeší v #4. A už je to na velmi slibně cestě.

Máte přání jaké mapové dlaždice pro dopravní mapu zobrazit? Ty výchozí z
titulky osm.org?

**Comment by Krakonos** [comment]
Mě bý se asi nejvíc líbila dopravní mapa jako vypínací vrstva, ať se může každý rozhodnout, která se mu líbí. 

Ono už teď je možná těch podkladů dostupných "až moc" (ne že by to vadilo, ale nepřidával bych zbytečně).

**Comment by mkyral** [comment]
Souhlas. Teoreticky by celá vrstva mohla být řešena aktivně - tedy, že server pošle jak data o zastávkach, tak i vedení tras v json a o vykreslení by se pak postaral leaflet. Dal by se i udělat seznam tras a uživatel by si mohl zobrazit třeba jen jednu trasu, která jej zajíma.

**Comment by jzvc** [comment]
Teoreticky by to chtelo nejaky minimalni zaklad, bez detailu ... a pres to mit ruzny overlaye. Viz trebas popisky, ktery sou fajn, ale kdyz se poslou na jinej podklad nez fotomapu, uz to tak fajn neni. Ale dalo by se tak docilit toho, ze by se i za hranicema CR zobrazovaly nazvy v cestine. Napr.

**Comment by zbycz** [comment]
Přidal jsem tedy tu osm.org defaultní, až budeme mít vlastní/jinou - pošlete prosím URL :-)

**Comment by mkyral** [comment]
No doufám, že brzo bude. Když už jsem si začal hrát s těmi vrstevnicemi, tak bych se pak mohl vrhnout na lepší ortofoto vrstvu a dopravní vrstvu. Ještě nevím v jakém pořadí ;-)

**Comment by jkjkjkjkjk** [comment]
osm.org defaultní dopravní mapa sice vypadá pěkně, ale moc toho neumí. V Praze a okolí třeba konkrétně tramvaje, metro nebo vlaky. Ale evidentně to jde, viz http://www.öpnvkarte.de/.

**Comment by mkyral** [comment]
Jo. To vypadá použitelně - až na tmavě modré metro vs. modré tramvaje. Škoda, že ten styl není někde na githubu :-(

A ač přímo na stránkách není žádný odkaz na dlaždicový server, dle [wiki](http://wiki.openstreetmap.org/wiki/DE:%C3%96pnvkarte) to vypadá, že se ty dlaždice dají použít i jinde.

**Comment by zbycz** [comment]
Přidal jsem jí do mapy - můžeme tohle zavřít?
Po čase bych zkusil oslovit všechny nejasné - jeslti jim nevadí využítí u nás..

**Comment by mkyral** [comment]
Jestli ti tak moc vadí, že to je otevřené. 

Časem bych určitě viděl nějaká vylepšení - třeba skrýt si jednotlivé vrstvy - zobrazit třeba jen tramvaje, zvýraznění určité linky, zobrazení seznamu zastávek, zobrazení zastávkových jízdních řádů ;-)

**Comment by zbycz** [comment]
No je fakt, že to je issue na tileserver, tak nechám otevřené :-)

**Comment by tkas** [comment]
Netyka se primo osmap.cz, vhodny zdroj dlazdic asi aktualne neni. Zaviram.
