### ISSUE TITLE
Render neexistujících turistických tras

### ISSUE THREAD

**Issue by Krakonos** [osmcz/osmcz#60]
Ahoj,

chystám se něco zmapovat v Klecanech a všiml jsem si této relace:

http://www.openstreetmap.org/relation/158617

Podle popisku neexistuje, je nějak otagovaná (nevím, jestli správně), a vykresluje se v našich vrstvách, a to jak poloha.net, ale také mtbmap. Bylo by vhodné se na to mrknout a udělat nějaké systémové značení (a případě zdokumentovat, jak se vlastně značí cesty v návrhu).

**Comment by mkyral** [comment]
Jaký popisek? Nikde nic nevidím.

**Comment by Krakonos** [comment]
Ok, jsem zmatený jako lesní včela. Díval jsem se na modrou, ale relaci jsem měl otevřenou cyklo:

http://www.openstreetmap.org/relation/1734128

Nicméně je tam také vyrenderovaná.

**Comment by mkyral** [comment]
Podle mne je to blbě otagováno: http://wiki.openstreetmap.org/wiki/Cycle_routes#Tagging_cycle_route_networks

Na nějakou poznámku nebude renderer brát ohled. A jestli podporuje rcn=proposed se uvidí, až to někdo opraví. Zavírám.
