### ISSUE TITLE
navbar - provedeni a funkcnost

### ISSUE THREAD

**Issue by jzvc** [osmcz/osmcz#63]
1) proc to neudelat samovysouvaci? Nastrel:

```
#main-navbar ul ul {
    display: none;
}

#main-navbar ul li:hover > ul {
    display: block;
}
```

2) po kliknuti se misto vysunuti/zjeveni provede reload stranky z nova se nacita mapovej podklad. Toto plati i pro linky uvnitr tech zobrazenych veci, kde se navic obcas objevi nekonzitentni chovani v tom, ze tam sou zalozky ... a nekdy zustanou jindy mizej.

Imo by to konzitetne melo byt v tom hornim navbaru vse, pripadne by mohl byt viceurovnovy.
Priklad:

![osm_navbar](https://cloud.githubusercontent.com/assets/1904139/12405214/3334f952-be42-11e5-8252-2643cb3da24d.png)
Klik na Skoleni/Brno/Archiv zachova to zahlavi, klik na Stats ho zrusi.

**Comment by zbycz** [comment]
Zkoušel jsem udělat navbar 3 úrovňový - podpora pro to v cmsku už je. Ale pak jsem to zase zrušil, protože to bylo nepoužitelné na mobilech + člověk vlastně nevěděl kde je.

Hlavně když sis otevřel to školení, pak aby ses dostal do podstránky bylo nutné znovu projet dvě úrovně vysouvání. Prostě bylo to moc schované, aby to někdo našel.. Proto pro třetí úroveň je navíc ten top-tabs.

Co se týče reloadu po kliknutí, to budu řešit v rámci #54. 

Statistky měly jinou custom šablonu kde chybělo to top-tabs-menu. Opraveno na webu.

**Comment by zbycz** [comment]
Takže asi uzavírám, případně klidně otevři - rád se budu bavit dál :)
