### ISSUE TITLE
Foto vrstva - různé ikony pro rozcestníky, mapy, informační panely 

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#65]
Bylo by fajn, až se povede doimplementovat kategorie, nastavit každé z nich jiný obrázek, aby bylo hned vidět co je rozcestník a co informační tabule.

**Comment by walley** [comment]
neni tohle uz nahodou hotove? aspon jako zaklad pro dalsi rozsireni?
ja bych to zavrel

**Comment by walley** [comment]
taky to zaviram
