### ISSUE TITLE
Přidat nové vrstevnice z poloha.net

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#66]
Přidat `/contours` a `/contours_ortofoto` aka https://github.com/osmcz/poloha.net_config/commit/371f5293d692303a3f0ca2a9f7af5923d3c3d9af

A zároveň promyslet jak zpracovat aby při zapnuté orotofoto mapě se používalo to jiné url.

//edit: koukám že github má níže chybu - ten commit jsem nepushnul já :-))

**Comment by mkyral** [comment]
Nedá se nějak prohodit adresa v seznamu? Případně skrýt jednu a zobrazit druhou?

Vykoukal jsem:
`setUrl( <String> urlTemplate )   this    Updates the layer's URL template and redraws it.`

**Comment by zbycz** [comment]
Pěkné - udělal jsem release a deploynul.
