### ISSUE TITLE
Cache-Control: max-age=0

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#69]
Nevím jestli to jde nějak ovlivnit, ale přijde mi zbytečné pokaždé znova načítat všechny ty odkazy na boostrap, jquery, leaflet...
Všude tam jsou konkrétní verze a nepředpokládám, že by se ty soubory měnily.

**Comment by jzvc** [comment]
jquery:
Date: Thu, 21 Jan 2016 06:37:09 GMT
Expires: Fri, 20 Jan 2017 06:37:09 GMT
Last-Modified: Fri, 16 Oct 2015 18:27:31 GMT
Cache-Control: public, max-age=31536000

leaflet:
Date: Sat, 12 Dec 2015 03:13:21 GMT
Last-Modified: Thu, 21 May 2015 14:37:20 GMT

... tzn je to vec browseru, za normalnich okolnosti by to nacitat nemel. Koukal sem i na par dalsich, hlavicky ruznorody, ale obecne nic co by jakkoli branilo pouzit cache.

**Comment by mkyral** [comment]
No on to možná nakonec nenačítá, ale minimálně si ověřuje, jestli tam je nějaká změna. A s tím mám občas problém, neb na některých místech, kde se pohybuji, není spojení s těmi servery právě nejlepší (kolize ipv4 adres a ipv6 v nedohlednu). Pak musím čekat, než vyprší timeouty :-(

Ale jestli to nejde, tak to zavřete.

**Comment by zbycz** [comment]
Pokud vím, tak chrome s těmito hlavičkami ani neověřuje. Pouze když dáš F5.

Jinak do budoucna bude fajn rozchodit nějaký build proces. Ovšem zas to
omezuje množinu přispěvatelů..

čt 21. 1. 2016 v 22:56 odesílatel Marián Kyral notifications@github.com
napsal:

**Comment by mkyral** [comment]
Používám FF. Asi není tak chytrý.

Co ten build process přesně obnáší? Možná by neškodilo sepsat jednotlivé kroky na wiki.

**Comment by zbycz** [comment]
build proces jednak minifikuje app javascripty do jednoho filu. A většinou děláme druhý file vendor.js, kde minifikuje všechny cizí závislosti.

Když už by se nahodil, tak se tam dají zapojit preprocesory
1) místo čistého JS psát alespoň EC6
2) místo čisétho CSS používat LESS (že se teď nepoužívá je teď docela otrava :)
3) mohlo by to třeba rovnou commitnout vybuilděnou verzi do repozitáře webu (až bude) :)
4) no a potom integrační/behaviorální testy, aby se nám nerozbíjelo co to už bude umět

.. pro FE vývojáře je to běžné, ale když potom někdo chce přispět do projektu musí si nainstalovat node.js a používat trochu konzoli, aby se podíval jestli to co napsal funguje. Takže jsem to na začátku vynechal, ať se dá líp přispívat.

**Comment by mkyral** [comment]
EC6, LESS - samá cizí slova. To se budu muset dovzdělat :-D

BTW: poslední dobou jsem několikrát narazil na další magické slovíčko: Grunt

**Comment by Krakonos** [comment]
Co se hlaviček týče, prohlížeče pokud vím mají právo je ignorovat a ověřit si, zda se soubor nemodifikoval. Prohlížeče se dají nastavit, aby to nekontrolovaly, na serveru se s tím nedá, pokud vím, nic udělat.

**Comment by zbycz** [comment]
Je to tak, cache v prohlížeči je vždy volitelná.

ad grunt) jojo, to je právě nástroj na automatizaci buildu a preprocesorů. Já mám víc zkušeností s gulpem.

**Comment by jzvc** [comment]
Prohlizec muze zmenit vzdycky cokoli, ale svepravnej browser pouzije cache, pokud muze. Ty hlavicky mu v tom muzou pomoct. Co se tyce zjistovani/nezjistovani novy verze, to je dany prave tim, jaky hlavicky tam sou. V tomhle pripade je to tak trochu kazdej pes jina ves, takze u nekterych scriptu se browsers spokoji s tim, co ma, jinde se mozna zepta na novejsi verzi (coz by i na pomalym spojeni nemelo byt znat) ...

Mozna by spis nebylo od veci to servirovat z jednoho mista. Jestli jeden nebo vic souboru nebude mit zasadni vliv, spis naopak, vic souboru si to sosne zaroven (pokud se tomu srv nebrani). Bezne probiha komprese na urovni http, takze nic dalsiho stim delat netreba, vliv 00nic.

2mkyral: Palici a ISP tlouct (ne obrazne, ale realne) ... vzdycky me pobavi, kdyz je rec o IPv6 a vykladaj jak to lidi nechtej ... lidi nechtej zadny IP, lidi chtej fungujici net.

**Comment by mkyral** [comment]
Je mi jasné, že server neovlivníme. Ale v tom javascriptu bychom s tím mohli něco udělat.

@jzvc Kéž by to bylo tak jednoduché. Není to až tak problém ISP, ale velké sítě využívající kdysi nepřidělené IP prefixy pro privátní účely. No a ty jsou teď přidělené a to je problém. Bohužel IPv6 zatím v nedohlednu a nemám žádnou páku jak to změnit.

**Comment by jzvc** [comment]
Myslis jako natahovat ty scripty scriptem? Tim ale cache vyradis ze hry asi uplne. Navic specielne tohle se bude chovat v kazdym browseru naprosto jinak a celkem nepredvidatelne. 

BTW: ...pokud nekdo pouziva nonprivat IP uvnitr ...

**Comment by mkyral** [comment]
No asi s tím nic udělat nepůjde (kromě výhledového zdrcnutí do jednoho souboru), takže zavírám.

**Comment by zbycz** [comment]
No ještě by třeba šlo si to všechno uložit na náš github a potom to tahat přes cdn.rawgit.com ([viz](https://rawgit.com/))  .. jestli by ti ta IP vyhovovala :smile:  :-1:
