### ISSUE TITLE
Sidebar CSS

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#71]
Dal jsem dohromady CSS sidebaru - prosím o případný testnutí na vašich zařízeních:
http://rawgit.com/osmcz/osmcz/sidebar/index.html

Zásadní je, že na velké obrazovce se chová jinak než na mobilu. Blbé jsou asi ty dva scrollbary, no rád si poslechnu připomínky. **Je to WIP - neřešíme nyní obsah ani JS logiku. Jde jen o CSS zobrazení**

![image](https://cloud.githubusercontent.com/assets/385047/12539602/28c98db6-c2f7-11e5-8c53-e94380fbe1e5.png)

vs 

![image](https://cloud.githubusercontent.com/assets/385047/12539605/3d955478-c2f7-11e5-9b1a-414582bba7b8.png)

**Comment by zbycz** [comment]
Ještě jedna důležitá připomínka - na mobilu bude povolené zobrazit maximálně jeden ze sidebarů. (Zajistí JS logika) ... ovšem i to je ke zvážení :-)

**Comment by mkyral** [comment]
Když oba panel vypnu. tak se mapa posune doleva a vpravo se objeví šedý prostor bez dlaždic, který se ani po posunutí mapy dlaždicemi zcela nezaplní.

A bylo by možné přidat nějakou možnost jak zase ty panely zapnout bez toho, abych musel udělat reload stránky?

**Comment by vop-cz** [comment]
Nevim co presne zkoušet. U mě na mobilu s QHD to technicky jede. Panely prekryvaji celou mapu a vlastne jsou prekryte i castecne i pres sebe...

**Comment by mkyral** [comment]
A docela dobře si dokáži představit, že na mobilu bude panel jen jeden a bude se vysouvat ze spodní (horní) hrany. Stejně jako to mají maps.me. Jen nevím, jak moc náročné na implementaci to je ;-)

**Comment by zbycz** [comment]
Díky za report. Šlo mi o to jestli to někde neulítá úplně do háje / či třeba nejde scrollovat.
S tím vyjížděním dobrý nápad, je to vpodstatě jeden řádek v css :-)

Šedý prostor se u mě projevuje taky, takže to nebude problém odladit.

**Comment by mkyral** [comment]
Mimochodem:
![napoveda](https://cloud.githubusercontent.com/assets/155542/12556460/4627bc40-c386-11e5-9fc0-2b9b9264979b.png)

Já věděl, že s tou šipkou budou furt nějaké problémy :-D

**Comment by vop-cz** [comment]
Šlo by pro mobilni verzi nastavit tak, aby zavření bylo možné i kliknutím mimo? Tedy do mapy?

**Comment by vop-cz** [comment]
...upřesnění, hovořím o pravé liště, tedy výběru vrstev - levá se tak už chová...

**Comment by zbycz** [comment]
To co je nyní vlevo není sidebar, nýbrž jen "poi-popup" - ten se zavírá kliknutím do mapy.

Zavření sidebaru Vrstvy na mobilu je docela dobrý nápad, ale low-priority. Pokud chceš vytvoř na to specificky issue.

> Když oba panel vypnu. tak se mapa posune doleva a vpravo se objeví šedý prostor bez dlaždic, který se ani po posunutí mapy dlaždicemi zcela nezaplní.

Stává se vám to ještě někdy? Pokud ano - prosím nové issue.

> S tím vyjížděním dobrý nápad, je to vpodstatě jeden řádek v css :-)

Neprioritní - pokud to ještě někoho interesuje - prosím nové issue.

---

Kdyby někdo chtěl toto issue otevřít - prosím o přečtení #108  :-)
