### ISSUE TITLE
Rozcestníky vs. mapillary

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#82]
V souvislosti se [zprovozněním](https://github.com/osmcz/osmcz/commit/a567dcbf337d5c1885095b731cdf9799f7b762c0#diff-18a6af6b31264213fcbc35940bfb7efdR280) "nejbližší" mapilaří fotky, by stálo za diskusi, jestli by to nedokázalo nahradit "naše rozcestníkové api", resp. v čem to nedostačuje, jestli to nějak přihonout apod. Chce to asi promyslet víc do hloubky. 

Víme akorát, že nahrát skriptem vše od nás do mapillary je lehké.

Zejména až bude #16, tak by to bylo opět konzistentější. Plus aplikace Mapillary je ve více směrech dobrá pro BFU, tak abychom předešli zbytečnému dublování.

Příklady:
![image](https://cloud.githubusercontent.com/assets/385047/12745460/a3b21a0e-c999-11e5-9dac-4d24f572e454.png)

![image](https://cloud.githubusercontent.com/assets/385047/12745571/2e24770e-c99a-11e5-8112-0b61d7e65c08.png)

**Comment by walley** [comment]
v podstate chces naimplementovat tohle api volani /im/close? pokud by stacilo omezeni vzdalenosti na ctverec (a ne korektne na kruh) tak to muzu udelat prakticky hned

**Comment by zbycz** [comment]
To můžeš, čtverec není problém. Ideálně na to vytvoř issue :+1: 

Ale o to mi nešlo. Moje myšlenka směřovala k tomu, jestli by bylo technicky možné nahradit naše stávající rozcestníkové API beze zbytku tím mapillary. Ne že bych to chtělo dělat, je škoda zahodit tvojí práci, jen bych nad tím rád zapřemýšlel.

Tj. fotky v MP jsou včetně polohy a úhlu. U příslušeného guidepost by šlo referencovat 
`mapilary:photo=key123412312` -> čímž by se zajistilo správné vykreslení u správného guidepostu. 
Vlastně by tam šlo referencovat i `osmcz:photo=současné_idčko`, či  `commons:photo=name`. 

Tím bychom dostali data do OSM databáze pro širší použití.

Současná rozcestníková vrstva by pak vlastně mohla být řešena dotazem na overpass (resp. pedra), a vykreslení pouze node rozcestníků s příslušnými `photo` tagy. Co by nešlo je vykreslit fotky rozcestníků, které nejsou přiřazeny k osm-node. Potřebujeme to?

**Comment by walley** [comment]
moje idea je mit jednoduse vrstvu fotografii a v ni fotky z ruznych volnych zdroju. clovek by si zapnul co by chtel. Pristim kandidatem je pro me wikimedia commons jako celek, jsou tam tuny zajimavych fotek. 

active layer by pak zobrazoval veci ktere sou v osm + fotky z *:photo tagu (to ovsem nikdy nebude nikdo updatovat, s tim se musi pocitat)

**Comment by mkyral** [comment]
Mapillary jsem zkoušel - problém byl, že ten algoritmus na rozmazávání obličejů rozmazával i texty na rozcestnících. Dají se sice označit oblasti, které není nutné rozmazat, ale je potřeba každou nahranou fotku kontrolovat a nějakou dobu to trvá - každou žádost posuzuje člověk.

**Comment by zbycz** [comment]
Jo, tak to je zásadní nedostatek. Dospěl jsem postupně k tomu, že máme dvě věci:
- aktivní vrstvu + fotky k poi (nejbližší mapillary, rozcestníky, wikimedia, panoramio, ...)
- vrstvu všelijakých fotografií (přesné pozice přímo těch fotek - zobrazené na mapě)

Čili dává smysl provozovat naši "open fotko/rozcestníko databázi". Tím asi tohle issue uzavírám, stálo by za to otevřít nové obecně o "fotkové vrstvě".
