### ISSUE TITLE
Využití domény osmap.cz 

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#83]
Nazdar,

V souvislosti se zobrazením názvu openstreetmap.cz vždy nahoře v liště, si říkám, že by možná bylo na čase přepnout jako primární doménu osmap.cz.

Dle mého je důležité propagovat ve všech materiálech zejména celé openstreetmap.cz, protože lidem se to spojí. "Jo, openstreetmap, to už jsem slyšel,nevěděl jsem že mají český web ." Nebo "Jo, to jsou ta data pod mapy.cz" ;))

Ale zároveň se líp píše to kratší, plus bylo by fajn naučit lidi ten kratší název používat. 

Varianty:
1. Nechat současný stav/přesměrování, kratší doménu nabízet pouze v nějakém tom dialogu "sdílet mapu" jako to má google 
2. Pro mapovou aplikaci pouzivat osmap.cz ale pro informační stránky okolo dlouhou variantu. Tohle ovšem jde blbě,neboť to je celé jedna Ajax aplikace..
3. Provozovat vše paralelně na obou doménách ... To teda ne :)

**Comment by Krakonos** [comment]
Ahoj,

osmap se mi líbí, rád to píšu (narozdíl od openstreetmap.cz). Docela mi vyhovuje redirect osmap.cz -> openstreetmap.cz, stejně jako třeba osm.org -> openstreetmap.org, nebo coord.info -> geocaching.com/šílený_hash :-)

Ale chápu, že propagovat dvě jména je komplikované... Líbí se mi varianta ehm.. 11, tedy mít extra mapovou aplikaci a extra jiné stránky. Uf. Upřímě, neumím se rozhodnout ;-)

**Comment by walley** [comment]
osm.org je jen presmerovani na openstreetmap.org a coord.info taky, melo by to byt stejne i u nas. malokdo si ty zkraceniny stejne pamatuje. a taky to komplikuje https certifikaty. (treba certifikat na osm.org je vydan pro *.openstreetmap.org;))

**Comment by mkyral** [comment]
Taky bych to moc nekomplikoval -> nechal bych to tak jak to je teď s tím, že osmap.cz se v některých případech hodí více, než delší openstreetmap.cz ;-)

**Comment by zbycz** [comment]
Souhlas, výsledek tedy (1) případně nabízet jako krátkou url.
