### ISSUE TITLE
"nejbližší" fotky z guideposts db

### ISSUE THREAD

**Issue by walley** [osmcz/osmcz#85]
implementace obdoby http://api.mapillary.com/v1/im/close?lat=' + lat + '&lon=' + lon + '&distance=30&limit=1 pro rozcestniky

**Comment by walley** [comment]
http://api.openstreetmap.cz/table/close?lat=49.709297&lon=17.07934&distance=1000&limit=1

uz to funguje (melo by)

**Comment by zbycz** [comment]
Super, použíl jsem ho [teď do toho panelu](https://github.com/osmcz/osmcz/commit/022ea2327d8fccd1b8968c5314c0f64e96508517#diff-18a6af6b31264213fcbc35940bfb7efdR437) neboť to ref hodně často chybí. Dal jsem tam ten distance=50, snad to bude ok.

**Comment by mkyral** [comment]
Sákryš. A já chtěl docílit toho, že se to ref začne doplňovat :-)

**Comment by walley** [comment]
zacal sem delat na systemu tagu u fotek, tak se budou moct zacit doplnovat vsechny refy, kdyz uz kct ma pocit ze kazda tabulka muze mit svuj:)

**Comment by zbycz** [comment]
@mkyral hehe, nic nebude :-))  No, ono tomu spíš pomůže až bude editační formulář rozcestníkové fotky v sidebaru. Pak se to bude doplňovat jedna báseň.

@walley btw, napadlo mě že by bylo dobré u fotek se zcela stejnou polohou vracet jen jeden feature, který má více fotek (a v popupu vypsat všechny). Zejména v aktuální funkčnosti "seskupování" v rozcestníkové vrstvě by to dle mého pomohlo k použitelnosti. Což?

**Comment by walley** [comment]
no to bych musel vyrabet naky pole v properties pointu, to by asi bylo zbytecne slozity.

v tom seskupovani to seskupuje prave proto, ze fotky sou prilis blizko u sebe. Kdybych to seskupoval uz na serveru, nebylo by to vubec potreba resit v mape, ale stejne by se musel zbytecne parsovat ten geojson.

**Comment by zbycz** [comment]
No já myslím, že by to dost přidalo na použitelnsti. Protože teď když se chci podívat na jeden rozcestník ze dvou stran, musím rozbalit tu "skupinu s číslem" ono mi to přezoomuje mapu, pak proklikávám ani nevím co.

Zato když by přišly ze serveru prostě "místa" + každé mohlo mít více fotek, tak by to bylo takové logické - odpovídající realitě. Datově by to stačilo řešit asi tak, že by uživatelé mohli k "jednomu rozcestníku" nahrát více fotek a klidně bys mohl cesty oddělené newlinem dát do jednoho velkého TEXT sloupce. To je legitimní..

**Comment by walley** [comment]
zakladni jednotka je fotka, ne rozcestnik. na fotce muze byt cokoliv, ne jen rozcestniky. az tam budou ty tagy, jemne se upravi volani tak aby filtrovalo jen rozcestniky (bez map apod, bude toho pak mnohem min)

protokol by pak sice mohl byt geojson, ale musel by se specialne parsovat, protoze properties pointu je nazev:hodnota - takze by to bud muselo byt nazev1:hodnota nazev2:hodnota nebo nazev:"hodnota hodnota".

vygeneruj mi sem prosimte volani a vracenej geojson, ja to porad moc nechapu v cem by to bylo lepsi.

**Comment by zbycz** [comment]
No, mohla by být základní jednotka "fotografovaný objekt s ref" + může udělat více fotek. 
Ale dá se žít i bez toho.

```
         "properties":{  
            "ref":null,
            "name":"litovel_mesto.jpg",
            "attribution":"walley",
            "url": ["img/guidepost/litovel_mesto.jpg", "druha"] ,
            "id":722,
            "neboimages": [{prvni: "něco"}, {druhy: "něco"}]
```

Ale asi to zatím nech. Až se poustím do mapillary+photo vrstvy, tak to z toho nějak vyplyne.
