### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#87]
V README.md se píše:

> Zdrojové kódy jsou pod licencí MIT. 

Ale v souboru LICENSE je GPL v3. Co je tedy správně?

**Comment by walley** [comment]
co sem napsal ja je gpl plus co chcete. license se vygeneroval automaticky.

**Comment by zbycz** [comment]
Navrhoval bych to tedy dual-licencovat GPL+MIT.  Na GPLku samotném je totiž blbé, že je nakažlivé, v jakémkoliv projektu je využita knihovna GPL, musí celý projekt být GPL.. tuším..

Jestli souhlas tak to zavřeme a upravíme popisky.

**Comment by Krakonos** [comment]
Eh. Pokud bundlujeme nějakou GPL knihovnu, asi máš pravdu. Pokud se jenom na nějakou odkazujeme, jsem si skoro jistý, že GPL mít nemusíš. To skoro je tam proto, že pokud vím, to ještě nikdo nerozsoudil.

Nechtělo by se mi do dual licence proto, že pak není jasné, co mám udělat, když se rozhodnu vzít kód pod MIT. Musel bych potom vyházet všechny části, které používají GPL knihovny a to možná není zrovna užitečné/datelné.

Mimochodem, pokud je problém v námi napsanému kódu, který obsahuje GPL, tak ho samozřejmě můžeme přelicencovat a říct, že poslední GPL verze byla tahle, odteď máte MIT, která je permisivnější, a nikdo se zlobit nebude.

**Comment by zbycz** [comment]
Myslím že v našem kódu problém není, tj. @mkyral a @walley, vadí vám kód pustit pod permisivnější MIT? Nebo jaké jsou důvody pro GPL?

**Comment by mkyral** [comment]
Z Linuxu jsem zvyklý na GPL, takže většinou ani o jiné licenci neuvažuji. Dle [wiki](https://cs.wikipedia.org/wiki/Licence_MIT) je MIT s GPL kompatibilní, takže celkem nic proti nemám. Nevím kam se dostaneme, jestli hrozí, že někomu bude stát za to, vzít náš kód a začít jej prodávat. Ale v licencích se moc nevyznám.

**Comment by Krakonos** [comment]
Zastánci GPL ji maji rádi hlavně kvůli nakažlivosti, protože když začneš všechny knihovny vydávat pod GPL, tak vyhladovíš proprietální software na nedostatek knihoven. Nadruhou stranu to bude znamenat, že si budou psát svoje uzavřené věci. 

Osobně jsem rád, že hodně knihoven je otevřených, alespoň se sdílí nějaké ty standardy a nikdo nemůže říct "ale to my nemůžeme, protože GPL".

Trošku se mi nelíbí vlastnost osm, že nedovoluje snadno asimilaci do jiných databází, prostě mi to přijde hloupé a IMHO bude zamezovat větší spolupráci jiných institucí, protože nebudou schopni splnit ShareAlike bez porušení nějaké jiné licence, nebo vytvářet podivná technická řešení kvůli tomu, že si někdo postavil licenci a udělal ji příliš restriktivní.

Myslím, že v našem případě je to celkem jedno, z nabídky bych volil jednoznačně MIT a slibuji, že už přestávám rantovat. Hezký večer :-)

**Comment by zbycz** [comment]
Volíme tedy MIT a uzavírám. Jestli někomu nevyhovuje, prosím do konce měsíce znovu otevřete. 

Kdo už teď souhlasí, nechť prosím změní své kusy kódu také na MIT (který je pro projekt implicitní)
