### ISSUE TITLE
Zobrazení rozcestníků

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#9]
Na turistické mapě by měly být rozcestníky klikatelné, po kliknutí se zobrazí detaily rozcestníku včetně náhledu fotografie - pokud ji máme. Po kliknutí na náhled fotografie se tato zobrazí v plné velikosti.

Součástí BZ rozcestníku by mohl být i seznam tras (relací), které přes rozcestník procházejí. Po vybrání trasy by se objevily její detaily včetně vysvícení na mapě.

**Comment by walley** [comment]
je nutno vytvorit v db referenci mezi fotkama a id nodu

dale je nutno pridat ikonku rozcestniku do klikacich poi

**Comment by zbycz** [comment]
Myslím, že v aktivní vrstvě by fotky rozcestníků být přímo neměly. Naopak je žádoucí, aby guideposts v aktivní vrstvě měly link na foto rozcestníků. Souhlasíte? Jak na to..?

**Comment by mkyral** [comment]
Teď jsem se trochu ztratil.

1) Máme vrstvu s fotkami rozcestníku - rozcestníky
2) Máme aktivní vrstvu - aktivní vrstva.

Pokud si zobrazím vrstvu (fotek) rozcestníků a kliknu na "rozcestník", uvidím to co teď.
Pokud si zobrazím aktivní vrstvu a kliknu na rozcestník, ten se mi zobrazí v panelu, nahoře budou OSM data (jméno, nadmořská výška, ref) a pod tím bude hromada místa, kam se přes ajax může dle ref dotáhnout fotka (plus attribution).

Když žádná fotka nebude, tak se nic nedotáhne (a zobrazí se možnost přidat foto).

**Comment by zbycz** [comment]
@mkyral jo takhle to píšeš správně. 

@walley už jsem to pochopil "ikonka rozcestníku" myslíš prostě obrázek. Založil jsem issue #79

**Comment by vop-cz** [comment]
@zbycz je na case zacit rozlisovat zobrazeni rozcestniku pro usery a pro mappery:
- Pro usery bych rozhodne nabidnul na POI vrstve v popup okne jednu fotku (zmenseninu s moznosti dalsiho prokliku - zde pak jeste debata kterou fotku, je-li jich k tomuto REF vic).
- Pro mappery bych to smeroval tak, ze budou mit moznost zapnout vrstvu "rozcestniky" jako nyni, ale ta vrstva bude jen graficke doplneni te POI vrstvy a bude obsahovat primarne graficky ztvarnenou informaci o tom, ze
  1) v tomto miste vime o rozcestniku (to je zrejme z toho, ze mame POI)
  2) u rozcestniku nemame info o REF (nemuzeme rozumne parovat s dalimi informacemi jako jsou fotky)
  3) u tohoto rozcestniku NE/MAME alespon jedno foto
  4) nejnovejsi foto je stare vice nez x roku, nebo bylo foto oznaceno za nevhodne, nedokonale, nespravne
  5) k tomuto rozcestniku mame reportovanou nejakou vadu v datech, nutno zasahnout
  Kdyz bude mit user aktivovanou vrstvu ci zobrazeni pro mappery, tak se mu popup okno rozcestniku bude zobrazovat asi s trochu jinym obsahem (prohlednuti vsech fotek, moznost prechodu k editoru fotek apod.)
  Pokud mluvim o "graficky ztvarnene informaci", pak mam na mysi napr. to, ze bude ikona rozcestniku v teto vrstve ruzne barevna, preskrtnuta, ruznobarevne podtrzena, zakrouzkovana apod..... Aby bylo na pohled zrejme, co s ni (s nim) je.

**Comment by walley** [comment]
to uz je vse udelane.
