### ISSUE TITLE
Přeryv ovládacích prvků s poiinfo

### ISSUE THREAD

**Issue by pschonmann** [osmcz/osmcz#90]
Takhle to vypada ted.
![neniok](https://cloud.githubusercontent.com/assets/6333844/12865715/598f9fc8-ccb4-11e5-86c8-cfe7404bb5d9.png)
Moje predstava je ze by melo okno byt soupnuto trosku vedle.
![ok](https://cloud.githubusercontent.com/assets/6333844/12865716/5fec6838-ccb4-11e5-9079-e537f4b2ce27.png)

OT: poi private swimming_pool by se nemusela generovat jako poi :)

**Comment by mkyral** [comment]
Ono toho chybí trochu více. V tomhle případě by pomohlo, kdy ten bod měl tag name=

Patche jsou vítány :-)

**Comment by mkyral** [comment]
Jinak ten panel je zatím dočasný, počítá se s něčím lepším.

**Comment by zbycz** [comment]
Mně vlastně přijde i v pořádku, že to ovládací prvky zakrývá. Když chce člověk pracovat s POI, ať s ním pracuje. A až nechce,ať si ho schová. Což?

To posunutí vedle prvků je takové nepěkné, třeba osm.org to řeší přesunutím ovladačů vpravo, možná to bude taky náš případ - zejména po dokončení #36. Souhlas?

**Comment by vop-cz** [comment]
+1 za přesunutí vpravo, ale asi jen na desktopu, na mobilu to sezere strasne moc mista a z mapy nic nezbyde...

**Comment by zbycz** [comment]
Rozhodně bych nelišil zobrazení na desktopu a mobilu.

Je správné, že na mobilu nejde mít otevřeno všechno - pokud chci pracovat s mapou měl bych POI-popup zavřít.

Panel měl být dočasný - ale vlastně mi teď dává smysl a už bych to bral takto finálně.
Když by se totiž zobrazovalo obsah poi-popupu v levém full-height sidebaru, zabíralo by to zbytečně moc místa. Tohle řešení je lepší?

Někdo pro/proti? Jinak bych toto issue zítra zavřel.
