### ISSUE TITLE
Nefunkční odkaz u tagu wikipedie:<country>=*

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#94]
Pokud je použit tag wikipedie:cs=\* namísto wikipedia=cs:*, vygeneruje se nesprávný odkaz na www.wikipedia.org namísto cs.wikipedia.org

Například: basilika minor Navštívení Panny Marie Frýdecké
http://openstreetmap.cz/#map=19/49.68962/18.34691&layers=dA

**Comment by zbycz** [comment]
Pro usnadnění stačí odkazovat na http://www.wikipedia.org/cs:Bazilika...  --> myslím že to bude méně kódu :)

**Comment by mkyral** [comment]
ee. tohle mi nefunguje.

**Comment by zbycz** [comment]
To není možné - u mě to běží...

https://www.wikipedia.org/wiki/cs:Bazilika%20Nav%C5%A1t%C3%ADven%C3%AD%20Panny%20Marie%20(Fr%C3%BDdek-M%C3%ADstek)

**Comment by mkyral** [comment]
Aha. To byla chyba mezi klávesnicí a židlí. Dneska ve vlaku na to mrknu.

**Comment by mkyral** [comment]
Fixed in  f757d4b
