### ISSUE TITLE
Odkaz na POI

### ISSUE THREAD

**Issue by mkyral** [osmcz/osmcz#97]
Hodila by se možnost poslat odkaz na konkrétní POI (třeba restaurace) a to tak, že by se otevřela mapa v místě POI a to by se rovnou načetlo do panelu.

Mohlo by to vypadat nějak takto:
`#map=13/49.8383/18.2958&layers=dA&show_poi=node:123`

Mapa by se otevřela na konkrétním místě, načetla by se vrstva POI a požadované POI by se rovnou zobrazilo v panelu.

**Comment by zbycz** [comment]
Rozhodně! Dík za issue, pracuji na tom. Ale chci zachovat kompatibilitu s
osm.org, čili něco jako osmap.cz/node/123

Souhlas?
so 20. 2. 2016 v 9:02 odesílatel Marián Kyral notifications@github.com
napsal:

**Comment by mkyral** [comment]
S tím nemám problém, ale v tom případě budeme potřebovat nějaký API dotaz pro získání souřadnic. Buď z OSM nebo bude potřeba vytvořit nový API call na poloha.net

**Comment by mkyral** [comment]
A bude potřeba se vypořádat se situací, kdy požadované OSM id není součástí aktivní vrstvy.

**Comment by zbycz** [comment]
Jojo, to mám promyšlené. Normálně se to dá tahat z public osm api.

**Comment by zbycz** [comment]
Tohle zdá se funguje už dobře: http://osmap.cz/node/1601837931
