### ISSUE TITLE
Vrstva s fotkami rozcestniku v mobilni verzi

### ISSUE THREAD

**Issue by xsuchy** [osmcz/osmcz#98]
Kdyz pouziji openstreetmap.cz na mobilu tak nemam moznost zapnout vrstvu s fotkama rozcestniku. Kdyby to slo, tak by to bylo super protoze bych mohl v terenu zjistovat zda rozcestniky v mem okoli jsou nafocene nebo ne.

**Comment by walley** [comment]
nojo, driv to slo, ale ted je dialog se seznamem vrstev prilis maly a neda se scrollovat.

**Comment by zbycz** [comment]
řeší to #36, hrozně rád bych ho udělal, ale nějak poseldní dobou není čas. Nevím kdy se k tomu dostanu, snad o víkendu..

**Comment by vop-cz** [comment]
VYRESENO vcera, pravou listu lze scrolovat
