### ISSUE TITLE
vrstva "Bez popisků"

### ISSUE THREAD

**Issue by severak** [osmcz/osmcz#99]
Vrstva bez popisklů je nesmyslně označená, protože popisky obsahuje.

Doporučuji ji přejmenovat nebo nasadit skutečnou vrstvu bez popisků, kterou poskytuje zřejmě někdo z Wikipedie, viz [map compare](http://mc.bbbike.org/mc/?lon=13.38885&lat=52.51703&zoom=11&num=2&mt0=osm-no-labels).

**Comment by zbycz** [comment]
Ta vrstva mapnik-nolabels je ošklivá.

Neměl bys návrh jak pojmenovat tu současnou? "nevýrazná"?

**Comment by severak** [comment]
Jmenuje se to Positron, že? Buď tak nebo spíš něco jako "nerušivá".
